### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by CHOK9938** [pmmp/PocketMine-MP#4207] opened 2021-05-04 14:07 UTC
[21:01:44] [Server thread/CRITICAL]: InvalidStateException: "Attempted to create tile pocketmine\tile\Sign in unloaded chunk 7 -12" (EXCEPTION) in "pmsrc/src/pocketmine/level/Level" at line 2609
[21:01:44] [Server thread/CRITICAL]: #0 pmsrc/src/pocketmine/tile/Tile(169): pocketmine\level\Level->addTile(object pocketmine\tile\Sign)
[21:01:44] [Server thread/CRITICAL]: #1 pmsrc/src/pocketmine/tile/Spawnable(62): pocketmine\tile\Tile->__construct(object pocketmine\level\Level, object pocketmine\nbt\tag\CompoundTag)
[21:01:44] [Server thread/CRITICAL]: #2 pmsrc/src/pocketmine/tile/Tile(116): pocketmine\tile\Spawnable->__construct(object pocketmine\level\Level, object pocketmine\nbt\tag\CompoundTag)
[21:01:44] [Server thread/CRITICAL]: #3 pmsrc/src/pocketmine/level/format/Chunk(723): pocketmine\tile\Tile::createTile(string[4] Sign, object pocketmine\level\Level, object pocketmine\nbt\tag\CompoundTag)
[21:01:44] [Server thread/CRITICAL]: #4 pmsrc/src/pocketmine/level/Level(2683): pocketmine\level\format\Chunk->initChunk(object pocketmine\level\Level)
[21:01:44] [Server thread/CRITICAL]: #5 pmsrc/src/pocketmine/level/Level(2295): pocketmine\level\Level->loadChunk(integer 5, integer -10, boolean 1)
[21:01:44] [Server thread/CRITICAL]: #6 pmsrc/src/pocketmine/level/Level(2957): pocketmine\level\Level->getChunk(integer 5, integer -10, boolean 1)
[21:01:44] [Server thread/CRITICAL]: #7 pmsrc/src/pocketmine/Player(1065): pocketmine\level\Level->populateChunk(integer 5, integer -10)
[21:01:44] [Server thread/CRITICAL]: #8 pmsrc/src/pocketmine/Player(1861): pocketmine\Player->sendNextChunk()
[21:01:44] [Server thread/CRITICAL]: #9 pmsrc/src/pocketmine/Server(2399): pocketmine\Player->checkNetwork()
[21:01:44] [Server thread/CRITICAL]: #10 pmsrc/src/pocketmine/Server(2152): pocketmine\Server->tick()
[21:01:44] [Server thread/CRITICAL]: #11 pmsrc/src/pocketmine/Server(1992): pocketmine\Server->tickProcessor()
[21:01:44] [Server thread/CRITICAL]: #12 pmsrc/src/pocketmine/Server(1586): pocketmine\Server->start()
[21:01:44] [Server thread/CRITICAL]: #13 pmsrc/src/pocketmine/PocketMine(291): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[46] C:\Users\...\Desktop\...\, string[54] C:\Users\...\Desktop\...\plugins\)
[21:01:44] [Server thread/CRITICAL]: #14 pmsrc/src/pocketmine/PocketMine(321): pocketmine\server()
[21:01:44] [Server thread/CRITICAL]: #15 pmsrc(11): require(string[101] phar://C:/Users/.../Desktop/.../PocketMine-MP.phar/src/pock)
[21:01:44] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[21:01:44] [Server thread/EMERGENCY]: Please upload the "C:\Users\Administrator\Desktop\SERVER\Skyblue\crashdumps/Tue_May_4-21.01.44-+07_2021.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
[21:01:45] [Server thread/EMERGENCY]: The crash dump has been automatically submitted to the Crash Archive. You can view it on https://crash.pmmp.io/view/4916077 or use the ID #4916077.

**Comment by dktapps** [comment] 2021-05-04 15:10
Duplicate of #4195

**Closed by dktapps** 2021-05-04 15:10 UTC
