### ISSUE TITLE
Spawners / Items with meta

### ISSUE THREAD

**Issue by splexpe** [pmmp/PocketMine-MP#2763] opened 2019-02-14 15:54 UTC
Alright so basically 52:20 (IG Spawner) wont allow me to place (nor any other spawner) and it wont lwave my inventory unless i /suicide

**Comment by dktapps** [comment] 2019-02-14 15:55
Nearly-duplicate of #2754 . Also, spawners don't take damage values, and magic damage values are not supported by any means.

**Closed by dktapps** 2019-02-14 15:55 UTC
