### ISSUE TITLE
Certain blocks have incorrect drops

### ISSUE THREAD

**Issue by JavierLeon9966** [pmmp/PocketMine-MP#4572] opened 2021-11-14 01:09 UTC
### Issue description

- Expected result: All blocks should have drops exactly as in vanilla
- Actual result: Some blocks have incorrect drops

### Steps to reproduce the issue
1. Explode a block that requires a tool for it to be dropped (Ex: Stone, Diamond Ore, Netherrack, etc)
2. You will see there are no drops

### OS and versions

* PocketMine-MP: 4.0.0-BETA13
* PHP: 8.0.13
* Using JIT: no
* Server OS: Linux
* Game version: iOS

### Plugins

- This bug is not caused by plugins 

### Crashdump, backtrace or other files

https://user-images.githubusercontent.com/58715544/141663706-0e87d3f7-5b78-428e-a789-97a67f183843.mp4

**Comment by dktapps** [comment] 2021-11-14 01:23
Duplicate of #2102.

**Closed by dktapps** 2021-11-14 01:23 UTC
