### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by gamegam** [pmmp/PocketMine-MP#5528] opened 2023-01-24 17:10 UTC
[01:08:04.291] [Server thread/CRITICAL]: pocketmine\network\mcpe\protocol\PacketDecodeException: "Reached limit of 500 packets in a single batch" (EXCEPTION) in "pmsrc/vendor/pocketmine/bedrock-protocol/src/serializer/PacketBatch" at line 43
--- Stack trace ---
  #0 pmsrc/src/network/mcpe/NetworkSession(368): pocketmine\network\mcpe\protocol\serializer\PacketBatch->getPackets(object pocketmine\network\mcpe\protocol\PacketPool#29852, object pocketmine\network\mcpe\protocol\serializer\PacketSerializerContext#26534, int 500)
  #1 pmsrc/src/network/mcpe/raklib/RakLibInterface(182): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[2251] ..9..E.G.{.e...<...=.mr.-bv.....)$.F.B%.....B...U...G.....w.......[..xh'....?G..)
  #2 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[2260] ....rn........5.........6&.x..$.&..NE..E..c>....`..@l..Qu..9O!..a..>`.x..w..<...)
  #3 pmsrc/src/network/mcpe/raklib/RakLibInterface(112): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#31499)
  #4 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #5 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
  #6 pmsrc/src/Server(1703): pocketmine\snooze\SleeperHandler->sleepUntil(float 1674580084.0737)
  #7 pmsrc/src/Server(1061): pocketmine\Server->tickProcessor()
  #8 pmsrc/src/PocketMine(328): pocketmine\Server->__construct(object BaseClassLoader#4, object pocketmine\utils\MainLogger#3, string[38] C:\Users\Administrator\Desktop\server\, string[46] C:\Users\Administrator\Desktop\server\plugins\)
  #9 pmsrc/src/PocketMine(351): pocketmine\server()
  #10 pmsrc(11): require(string[82] phar://C:/Users/Administrator/Desktop/server/PocketMine-MP.phar/src/PocketMine.p)
--- End of exception information ---
[01:08:04.293] [Server thread/ERROR]: [NetworkSession: plug Plugins] Bad packet (error ID 7be058fbcaf4): Packet batch decode error: Reached limit of 500 packets in a single batch

**Comment by gamegam** [comment] 2023-01-24 17:11
Example: Collision when combining 5 watermelons at once

**Comment by dktapps** [comment] 2023-01-24 17:48
Duplicate of #3954

**Closed as completed by dktapps** 2023-01-24 17:48 UTC
Labels: Resolution: Duplicate, Category: Gameplay, Category: Client
