### ISSUE TITLE
Multi-colored grass (biome issue?)

### ISSUE THREAD

**Issue by Bestaford** [pmmp/PocketMine-MP#3687] opened 2020-07-08 22:32 UTC
This thing random changes position with every join to world. Seems like many bioms (but snowy) and grass change color. Idk, is this client bug or pocketmine.
note: map from old (9 years ago) Minecraft Java versions.
![Скриншот_20200708-004454](https://user-images.githubusercontent.com/59061055/86976770-e419e400-c183-11ea-929f-261655f2e731.png)
I try to change biome on MC 1.1.5 version with command /biome set 1, but not works.
Client version: latest 1.16
Pocketmine version: latest
Platform: Android 7.0

**Comment by IceCruelStuff** [comment] 2020-07-08 22:47
That is a plugin issue because PMMP does not have /biome command

**Comment by dktapps** [comment] 2020-07-08 22:51
duplicate of #3584

**Closed by dktapps** 2020-07-08 22:51 UTC

**Comment by Bestaford** [comment] 2020-07-08 22:58
@IceCruelStuff, I try to change biome in old PMMP version (and fork, yes, Russian community still updating GenisysPro)
