### ISSUE TITLE
login timeout/Skin Bug

### ISSUE THREAD

**Issue by TarochanChannel** [pmmp/PocketMine-MP#4347] opened 2021-08-04 01:36 UTC
### Issue description

- Expected result: All people can join the server normally.
- Actual result: People who are not classic skins cannot join (Login timeout)

### Steps to reproduce the issue
1. Joining a server with a non-classical skin

### OS and versions

* PocketMine-MP: 3.22.1
* PHP: 7.4.21
* Server OS: Ubuntu 20.04.1 LTS (Focal Fossa)
* Game version: Win10

### Plugins
AllSigns v1.0.13, AntiSpamPro v1.4.1, AutoClearLagg v3.1.0, AutoEXP v0.0.1, BanItem v2.3.3, CommandBlock v1.0.0, DevTools v1.14.2, EasyCommandAutofill v1.0.8, FormAPI v1.3.0, FrameGuard v1.2.0, JukeBox v1.0.1, KeepInventory v1.0, MCPEToDiscord v1.4.1, MOTDShuffle v1.1.6, MSUI v1.0.2, MentionSound v0.0.1, Mineflow v2.0.3, MoneySystem v13.4, MoneySystemAirport v1.0.1, MoneySystemJob v4.42, MoneySystemLand v0.1.3, MoneySystemShop v5, MultiWorld v1.6.0-beta1, PiggyCustomEnchants v2.4.2, PlayerSelectors v1.0.8, PocketMoney v4.0.1.12, RegularlyMessage v2.2.0, RenorariPlug v1.0.46, ReplenishResources v2.6.0, SignPortal v1.1.4, SignServerStats v1.1.1, SimpleCape v1.0.0, SimpleHome v1.0.3, SpawnParticle v0.1, Texter v4.0.7, UBans v5.2.1, VanillaElytra v1.0.2, VanillaPickBlock v1.1.0, WChestShop v3.0.0, WorldEditPlus v3.1, height v1.0.0, if v3.9.1

- If you remove all plugins, does the issue still occur?
Yes

**Comment by TarochanChannel** [comment] 2021-08-04 01:38
![image](https://user-images.githubusercontent.com/56919233/128108109-cf922c72-d588-45cd-a168-a0a20fe757cc.png)
![image](https://user-images.githubusercontent.com/56919233/128108139-79da687f-959b-49c5-8932-fac50f5418ca.png)

**Comment by TarochanChannel** [comment] 2021-08-04 01:40
![image](https://user-images.githubusercontent.com/56919233/128108268-deebd9a8-ef91-4cf0-a41a-23508b9d3226.png)
![image](https://user-images.githubusercontent.com/56919233/128108283-7d352574-8aaf-4e9c-aa55-0245ad8c63ee.png)

**Comment by dktapps** [comment] 2021-08-04 14:32
Duplicate of #3733.

**Closed by dktapps** 2021-08-04 14:32 UTC
