### ISSUE TITLE
Can't jump/fast bridge

### ISSUE THREAD

**Issue by AkmalFairuz** [pmmp/PocketMine-MP#3820] opened 2020-09-08 07:15 UTC
### Issue description
Block disappear when jump bridge. I think this bug cause prevent spam interact packets from client

### Steps to reproduce the issue
1. Jump bridge or fast bridge

### OS and versions

* PocketMine-MP: 4.0.0
* PHP: 7.3
* Server OS: Ubuntu 16.04
* Game version: PE/Win10 (delete as appropriate)

**Comment by Gianluxx** [comment] 2020-09-08 07:17
Remove all your plugins and get good internet. Then try again

**Comment by Jviguy** [comment] 2020-09-08 07:20
if im not wrong this type of thing should be good. fast bridging is placing blocks on a non visual aabb of the block this could have been patched or (been messed with) as of recently so that could be why. interaction packets wouldnt cause the blocks to not place. what would cause that would be that the aabb stuff has been fixed or improved (hence why u can still sprint bridge).

**Comment by AkmalFairuz** [comment] 2020-09-08 07:26
No, you must know "Jump bridge".

**Comment by AkmalFairuz** [comment] 2020-09-08 07:27
> Remove all your plugins and get good internet. Then try again

I try on localhost.

**Comment by AkmalFairuz** [comment] 2020-09-08 07:29
NetherGames should already known this bug, because they already fix that bug

**Comment by dktapps** [comment] 2020-09-08 11:35
Duplicate of #2730

**Closed by dktapps** 2020-09-08 11:35 UTC
