### ISSUE TITLE
Attack cool down glitch

### ISSUE THREAD

**Issue by Nerahikada** [pmmp/PocketMine-MP#2939] opened 2019-05-26 11:59 UTC
### Issue description
When players switching 2 tools and attack, attack cool down does not work.
(This is a rare occurrence.)

### Steps to reproduce the issue
1. Get different 2 tools.
2. Switch them quickly and attack player.

### OS and versions

* PocketMine-MP: 3.8.2
* PHP: 3.7.5
* Server OS: Ubuntu 19.04
* Game version: PE/Win10

### Plugins

```
Plugins (0):
```

### Crashdump, backtrace or other files

Videos:
Attacker side: https://youtu.be/4pTf5lQb3X4
Victim side: https://youtu.be/SOqsjNr2-nA

**Comment by dktapps** [comment] 2019-05-26 12:08
Duplicate of #2642

**Comment by dktapps** [comment] 2019-05-26 12:08
whoops, the original was closed by its author ...

**Comment by xSkele** [comment] 2019-05-26 12:28
Yep i am having the same issue too

**Comment by dktapps** [comment] 2019-05-26 12:44
https://github.com/pmmp/PocketMine-MP/issues/2881#issuecomment-486571658

**Comment by dktapps** [comment] 2019-06-10 16:34
This bug is caused by the following code:
https://github.com/pmmp/PocketMine-MP/blob/2e0dd574e0ca8e8fa81606b0124b18744ac1d6c3/src/pocketmine/entity/Living.php#L544-L549

This code has been placed here intentionally, so I am not sure what the correct logic for this is, or what might be broken by changing it. This needs further investigation.

**Comment by T14Raptor** [comment] 2019-10-21 07:36
I don't know if this is needed or not, but this is how abuseable it is: 

https://youtu.be/5DOfC_fbNcs

**Comment by dktapps** [comment] 2020-05-31 16:43
For posterity: The intended behaviour (as seen in vanilla) is that "switching" allows dealing additional damage, but the damage from the previous attack is subtracted from it, so you can't get overpowered hits like we've seen on PvP servers.

e.g.
- hit with hand = 1 point
- hit with sword = 5 points
- still on cooldown due to hand hit, so subtract 1 = 4 points during cooldown

**Closed** 2020-05-31 18:48 UTC
Labels: Category: Gameplay, Status: Debugged

**Comment by knzvgxd** [comment] 2020-06-06 00:22
Switching is also present
