### ISSUE TITLE
Client Crash after world transfer from void world to plots world

### ISSUE THREAD

**Issue by Kjenium** [pmmp/PocketMine-MP#2421] opened 2018-09-01 10:56 UTC
### Issue description

When you teleport you or a player from a void (empty) world to a Myplot world the client crashes

### Steps to reproduce the issue

1. Connect to the server with Win10 Edition
2. Teleport you to a void (empty) world
3. Teleport you to the MyPlot world

### OS and versions

* PocketMine-MP: 
* PHP: 7.2.7-0ubuntu0.18.04.2 
* Server OS: PocketMine-MP 3.2.1 for Minecraft: Bedrock Edition v1.6.0 (protocol version 282)
* Game version: Win10

### Plugins
I have tried by removing all plugins included MyPlot but it still crashes
- Have you asked for help on our forums before creating an issue? YES
-  MineReset v3.2.0, FormAPI v1.2.0, EconomyAPI v5.7.2, CobaltGuns v1.2.0, PocketVote v2.1.4, PurePerms v1.4.2, MysteryCrate v6.4.2, DevTools v1.13.0, CustomAlerts v2.1, EssentialsPE v2.1.0, ManyWorlds v2.2.0, PiggyCustomEnchants v1.2.0, BankNotes v1.0.0, AdvancedKits v5.2.3, MyPlot v1.3.6, PureChat v1.4.11, Prison v1, DEVirion v1.2.5-ALPHA12, MagicWE v0.4.0, CustomBar v1.3.1, PlayerVaults v2, LuckyBlock v1.0.0

**Comment by dktapps** [comment] 2018-09-01 11:50
duplicate of #2222

**Closed by dktapps** 2018-09-01 11:50 UTC
