### ISSUE TITLE
Timings v1 no more works!

### ISSUE THREAD

**Issue by Striker209** [pmmp/PocketMine-MP#398] opened 2017-03-05 19:23 UTC
https://timings.aikar.co/?url=11111111

"Timings v1 is no longer supported here, as Spigot forcefully moved it away from my server, so almost no one is even hitting this URL anymore, so it doesn't make sense for me to keep supporting it.
I strongly recommend you to not use Spigot, as Timings v1 contains many bugs and lacking lots of info. Timings v2 is a huge upgrade and contains exponentially more information.

You may switch to a faster and better server by downloading Paper. It is a drop in replacement for Spigot, and all of your plugins should still work.

Plus, we have Tacos."

Something must change in order to use /timings paste back!

**Comment by dktapps** [comment] 2017-03-05 19:24
Duplicate of #364

**Closed** 2017-03-05 19:23 UTC
