### ISSUE TITLE
The server does not start if the path to the directory contains Cyrillic characters 

### ISSUE THREAD

**Issue by Gaprix** [pmmp/PocketMine-MP#4353] opened 2021-08-07 12:37 UTC
### Issue description
The server does not start if the path to the directory contains Cyrillic characters 

### Steps to reproduce the issue
1. start the server in the directory, the path to which contains cyrillic characters 

### OS and versions
* PocketMine-MP: 4.0.0+dev
* PHP: 8.0.8
* Server OS: Windows 10

### Plugins
none

### Crashdump, backtrace or other files
![изображение](https://user-images.githubusercontent.com/45711510/128600342-a475fa8b-0d3a-4891-9f63-cfef18079266.png)
![изображение](https://user-images.githubusercontent.com/45711510/128600348-359d5528-4fea-49d2-b77d-3bef71432816.png)
https://pastebin.com/B3c0n27p

**Comment by SOF3** [comment] 2021-08-07 14:28
Can you upload a fresh server.log?

**Comment by Gaprix** [comment] 2021-08-07 14:32
server.log does not contain the errors that are displayed in the console 

[server.log](https://github.com/pmmp/PocketMine-MP/files/6949244/server.log)
![изображение](https://user-images.githubusercontent.com/45711510/128603608-d9d3ec8d-bb81-4515-b6f8-0f2e5297a868.png)

**Comment by dktapps** [comment] 2021-08-07 16:50
Can you paste the file path you used as text here in the issue? I'd like to test some things.

**Comment by Gaprix** [comment] 2021-08-07 16:51
C:\Users\acpla\OneDrive\Рабочий стол\rgrgr\y\PocketMine-MP

**Comment by dktapps** [comment] 2021-08-07 16:59
I'm not able to reproduce this on a machine using en-GB locale. What locale is your machine using?

**Comment by Gaprix** [comment] 2021-08-07 17:02
ru-RU

**Comment by dktapps** [comment] 2021-08-07 17:08
I'm not able to reproduce this even after switching Windows language to Russian. I'm not sure what else can be done to debug this.

Do you have any plugins which are changing the locale via `setlocale()`?

**Comment by Gaprix** [comment] 2021-08-07 17:11
No

**Comment by dktapps** [comment] 2021-08-07 17:17
Have you tried running the server from a different folder (not in OneDrive)?

**Comment by Gaprix** [comment] 2021-08-07 17:18
I tried to start the server in C:\PocketMine-MP and there were no errors

**Comment by dktapps** [comment] 2021-08-07 17:19
I mean a path with Cyrillic characters in it (e.g. `C:\Рабочий стол\rgrgr\y\PocketMine-MP`

**Comment by Gaprix** [comment] 2021-08-07 17:24
Checked in the C:\Тест directory and got the same error 
![изображение](https://user-images.githubusercontent.com/45711510/128608786-842d6356-4475-44e5-a77b-33cf66ac4764.png)

**Comment by dktapps** [comment] 2021-08-07 17:25
Can you run `chcp` in cmd.exe and post the output?

**Comment by Gaprix** [comment] 2021-08-07 17:26
```
C:\WINDOWS\system32>chcp
Текущая кодовая страница: 866
```

**Comment by Gaprix** [comment] 2021-08-07 20:10
The error disappeared after I enabled beta unicode support in the regional settings. But I think it's not okay that I had to turn it on 
![изображение](https://user-images.githubusercontent.com/45711510/128612696-c901fbf7-4368-49a4-9b6e-9235b69a2c87.png)

**Comment by dktapps** [comment] 2021-08-07 20:27
Thanks for the information. I'm still not able to reproduce the problem, whether or not I enable/disable that setting.

**Comment by dktapps** [comment] 2021-08-08 12:37
Please try https://github.com/pmmp/PocketMine-MP/commit/853222c26075ba7b9bb4b2dfb1a75b4f07986ba1 and see if it resolves your issue.

**Comment by Gaprix** [comment] 2021-08-08 14:36
It did not help.

My actions:
1. Turned off "beta unicode support".
2. Rebooted the computer.
3. Confirmed that the error appears again.
4. Downloaded your commit and ran it.

Result:
![изображение](https://user-images.githubusercontent.com/45711510/128635724-6ac971a9-8d1a-43eb-8f1b-38cbcfcc436e.png)

**Comment by dktapps** [comment] 2021-08-08 14:41
I guess some base64 hack will be needed for this after all. Windows sucks >.<

**Comment by dktapps** [comment] 2021-08-08 15:07
Please try again with https://github.com/pmmp/PocketMine-MP/commit/baf1f1315acaa29d077bd2556cbf17ab61631788.

**Comment by Gaprix** [comment] 2021-08-08 15:14
This fixed the error. Thanks!
![изображение](https://user-images.githubusercontent.com/45711510/128636761-42d6ed00-2b7a-4cab-96b4-f35a69367e28.png)

**Comment by dktapps** [comment] 2021-08-08 15:17
Excellent. May I ask what version of Windows 10 you're using? I wonder if this might have been resolved by updating to a newer version (I haven't been able to reproduce it at all on 21H1).

**Comment by Gaprix** [comment] 2021-08-08 15:21
I have 21H1 (19043.1110)
![изображение](https://user-images.githubusercontent.com/45711510/128636991-cc298a15-c456-4d5e-81f1-33a90a7cf5dc.png)

**Comment by dktapps** [comment] 2021-08-08 15:23
How bizarre. That's the exact same version I have.

The fix has been merged to master, so I'm going to close this, but if anyone knows a better way to solve this problem, please let me know.

**Closed by dktapps** 2021-08-08 15:23 UTC
Labels: Category: Core, Status: Unconfirmed
