### ISSUE TITLE
Setting entity to immobile doesnt work

### ISSUE THREAD

**Issue by MINTEDCLICKS** [pmmp/PocketMine-MP#5736] opened 2023-05-04 16:58 UTC
### Issue description

- Expected result: entity to be set immobile
- Actual result: it didnt, however it works for players

### Steps to reproduce the issue
1. try set entity to immobile
2. it wont

### OS and versions

* PocketMine-MP: 4.20.1
* PHP: 8.0.15
* Using JIT: no
* Server OS: linux
* Game version: All?

### Plugins

you need a plugin to set to immobile so there is a plugin

**Comment by dktapps** [comment] 2023-05-04 20:08
Duplicate of #3130

**Closed as completed by dktapps** 2023-05-04 20:08 UTC
Labels: Resolution: Duplicate, Category: API
