### ISSUE TITLE
Sneaking while flying can still open interfaces

### ISSUE THREAD

**Issue by dadodasyra** [pmmp/PocketMine-MP#6083] opened 2023-10-09 20:29 UTC
### Issue description

- Expected result: The block should be placed but not the UI
- Actual result: The block is placed (client side only) and the UI is opened

### Steps to reproduce the issue
1. Place a chest/crafting table/furnace/any UI opener
2. Go in creative mode, activate fly mode
3. Sneak until touching the ground
4. Place a block B while sneaking (still in fly mode) on the UI opener 
5. You can now see the block B placed on your side, but not on the server side, and the UI is opened

### OS and versions

* PocketMine-MP: 5.6.0
* PHP: 8.3
* Using JIT: no (delete as appropriate) 
* Server OS: Debian 11
* Game version: tested on Windows 11

### Plugins

- If you remove all plugins, does the issue still occur? 
Probably, test.pmmp.io is not up to date so unable to test

**Comment by dadodasyra** [comment] 2023-10-09 20:30
Guess it's related to #5792, not sure if it's still a duplicate or if it worth it mentionning it. I leave the choice to maintainers

**Comment by dktapps** [comment] 2023-10-10 10:02
Yeah this is a duplicate. Thanks anyway though.

Duplicate of #5792

**Closed as completed by dktapps** 2023-10-10 10:02 UTC
Labels: Resolution: Duplicate, Category: Gameplay
