### ISSUE TITLE
Crashed because of non-existent furnaces?

### ISSUE THREAD

**Issue by jasonwynn10** [pmmp/PocketMine-MP#528] opened 2017-04-07 00:30 UTC
### Issue description

Server crashes whenever a specific _not corrupted_ world is joined.
### Steps to reproduce the issue

1. Attempt to join the linked world (seems to crash by saving tiles)

### OS and versions

* PocketMine-MP: 1c2895e
* PHP: 7.0.3
* Server OS: Win10
* Game version: N/A

### Crashdump, backtrace or other files

* ![screenshot 41](https://cloud.githubusercontent.com/assets/16521025/24780149/1b5aa330-1b03-11e7-9b18-a5881936942e.png)
* ![screenshot 42](https://cloud.githubusercontent.com/assets/16521025/24780150/1b5cf8a6-1b03-11e7-97d0-aec4091cd944.png)
* [#1 Spawn by FierceNinja Pink&Purple theme.zip](https://github.com/pmmp/PocketMine-MP/files/904190/1.Spawn.by.FierceNinja.Pink.Purple.theme.zip)

**Comment by madecode15** [comment] 2017-04-07 00:35
Duplicate of #490

**Comment by dktapps** [comment] 2017-04-07 09:31
^

**Closed by dktapps** 2017-04-07 09:31 UTC
