### ISSUE TITLE
Query does not always return data

### ISSUE THREAD

**Issue by zKoz210** [pmmp/PocketMine-MP#2303] opened 2018-07-12 10:29 UTC
### Issue description
For unknown reasons, there is often an error: "Failed to receive challenge.", but if I use the server based on [Steadfast2](https://github.com/Hydreon/Steadfast2/blob/master/src/pocketmine/network/query/QueryHandler.php), the server works well. I've tried many libraries and I get this error only with PM-MP.

Using library: https://github.com/xPaw/PHP-Minecraft-Query
I found the similar issue in this repository: https://github.com/xPaw/PHP-Minecraft-Query/issues/129

I use a dedicated server MC-16-V (OVH) and the site is on the same server as pocketmine. 

### OS and versions
* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/06b80a9536cc4cffd39d3cc22a5701337fea4a1a
* PHP: 7.2.7
* Server OS: CentOS 7

**Comment by Qeis984** [comment] 2018-07-12 11:13
I think because its library has designed for Minecraft : Java Edition and PocketMine dont support it.

**Comment by dktapps** [comment] 2018-07-12 13:11
that's funny because it's designed to be compatible........

@zKoz210 if you can provide further reproducing information that would be great.

**Comment by zKoz210** [comment] 2018-07-12 13:22
@dktapps Of course, I will provide any information that is required to solve the problem

**Comment by zKoz210** [comment] 2018-07-12 14:04
I can't give accurate information to reproduce the problem. Will any dumps be useful to you? This problem occurs intermittently, so it is extremely difficult to determine a specific sequence.

Try to get online several times in a row with 

SimplexLand: sxland.ru:19132 (Steadfast2)

and with

PocketLife: pocketlife.ru: 19132 (PM-MP)

and more than likely, with PocketLife you will get such an error.

**Comment by dktapps** [comment] 2018-07-12 15:53
that library's code is killing my brain cells... do you have any alternatives that also don't work?

**Comment by zKoz210** [comment] 2018-07-12 23:09
For example:
https://github.com/FunnyItsElmo/PHP-Minecraft-Server-Status-Query/ ([Code](https://gist.github.com/zKoz210/b317369e0b0d932e3cf3ec630f58692a))
https://github.com/sandfoxme/minecraft-query ([Code](https://gist.github.com/zKoz210/ae0c30a2a61727e86f1ca0503fc6ee1a))

**Comment by dktapps** [comment] 2018-07-13 08:09
it's no surprise the first library gives you errors... it tries to ping over TCP, so it's more likely you're getting a response from RCON than anything else...

**Comment by zKoz210** [comment] 2018-07-13 08:11
@dktapps It is strange that PM-MP has it offline and another server is online when I have both RCON and Query enabled

Okay, but the second one doesn't work either.

**Comment by dktapps** [comment] 2018-07-13 08:12
as for the second library, pocketlife does not respond to queries at all, so please check that you actually have query enabled and that the IP address is not banned.

**Comment by zKoz210** [comment] 2018-07-13 08:15
Hmm... But this library returns online perfectly.

https://github.com/pavel-grom/php-minecraft-pe-query

![image](https://user-images.githubusercontent.com/28255085/42680514-edc8a5d2-868d-11e8-9132-764062171f92.png)
![image](https://user-images.githubusercontent.com/28255085/42680532-f7af0906-868d-11e8-92cf-78347cf4f97b.png)

**Comment by dktapps** [comment] 2018-07-13 08:15
that's because that library does not use Query, it uses standard MCPE pings.

**Comment by zKoz210** [comment] 2018-07-13 08:16
In that case, I don't know what to do, do you have any ideas?

**Comment by dktapps** [comment] 2018-07-13 08:18
Enable debug output in pocketmine.yml (in case RakLib is doing something it shouldn't) and add some debug in here to see if the server actually gets the packets: https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/network/query/QueryHandler.php#L77

**Comment by Pub4Game** [comment] 2018-07-13 08:57
It looks weird. In debug there is nothing, and I see no queries to using the following lines
![image](https://user-images.githubusercontent.com/11244874/42682668-eaa7a3a2-8693-11e8-9168-70d8760c3e72.png)

**Comment by fubarpatsharp** [comment] 2018-07-13 09:50
I have the same problem with xPaw's library. When library outputs "Failed to receive challenge" debug output is empty.

**Comment by k3ithos** [comment] 2018-07-14 02:15
I've been using xPaw's library for a while now and it works fine for me, here's an example:
https://api.nethergames.org/query.php?ip=mm.nethergames.org&port=19132
(Server running PMMP)

I'm using the library from around a year ago, not sure if the latest commit in his repository may change anything

**Comment by zKoz210** [comment] 2018-07-14 08:50
@k3ithos so funny 
![image](https://user-images.githubusercontent.com/28255085/42722849-02f162cc-875c-11e8-9f33-1d8a1d299da0.png)

@dktapps I'll try to check again with your changes during the day.

**Comment by lukeeey** [comment] 2018-07-14 09:07
Lmao have you conisdered query is disabled?

https://api.nethergames.org/query.php?ip=play.skyblockpe.com&port=19132

**Comment by zKoz210** [comment] 2018-07-14 09:17
Here I get the answer, this is some nonsense

![image](https://user-images.githubusercontent.com/28255085/42723073-d4af2ea4-875f-11e8-901a-a02cf4fdaadd.png)

**Comment by Muqsit** [comment] 2018-07-14 09:40
Does this work for you? https://gist.github.com/Muqsit/e338435ed3f054f10d81a04bb5a0ec2a

**Comment by zKoz210** [comment] 2018-07-14 09:55
It works, I got an answer

![image](https://user-images.githubusercontent.com/28255085/42723372-24f9d198-8765-11e8-94eb-37b1df56dd89.png)

**Comment by k3ithos** [comment] 2018-07-14 11:04
@zKoz210 server froze and didn't respond to queries then, try again now :)

**Comment by zKoz210** [comment] 2018-07-16 12:52
@Frago9876543210 The point is not receiving data, and the decision of problems of compatibility libraries PC and BE. I do not understand the reason why this is happening

**Comment by dktapps** [comment] 2018-07-22 16:38
I don't think anyone previously considered UDP reliability issues. I've had guys run tests and there is intermittent lacks of responses no matter what server you try to query, because UDP doesn't try to redeliver in case of packet loss. 

This is plausibly (and highly likely) the real explanation, and there is no reason why PocketMine would be causing such a bug, so I'm going to close this.

**Closed by dktapps** 2018-07-22 16:38 UTC
Labels: Category: Network, Status: Unconfirmed
