### ISSUE TITLE
slowness does not going off if amplifier is bigger than 5

### ISSUE THREAD

**Issue by djdisodo** [pmmp/PocketMine-MP#2304] opened 2018-07-13 07:26 UTC
### Issue description

slowness does not going off if amplifier is bigger than 5

### Steps to reproduce the issue

1. type /effect <player> slowness 3 6
2. effect is not showing on inventroy. but still moves slowly

### OS and versions

* PocketMine-MP: 4.0.0+dev.1213
* PHP:
* Server OS: linux
* Game version: PE

**Comment by dktapps** [comment] 2018-07-13 07:34
Duplicate of #1551

**Closed by dktapps** 2018-07-13 07:34 UTC
