### ISSUE TITLE
ItemFrame Bug

### ISSUE THREAD

**Issue by xS91D** [pmmp/PocketMine-MP#5956] opened 2023-08-02 08:31 UTC
1.Put ItemFrame on Chest
2.The ItemFrame will disappear but other blocks not

### OS and versions

* PocketMine-MP: 5.4.0
* PHP: 8.2.7
* Using JIT: no
* Server OS: win
* Game version: Win10 1.12.10

Plugins (0):

**Comment by dktapps** [comment] 2023-08-02 10:20
Duplicate of #5734

**Closed as completed by dktapps** 2023-08-02 10:20 UTC
Labels: Resolution: Duplicate, Category: Gameplay
