### ISSUE TITLE
Duping Glitch

### ISSUE THREAD

**Issue by akaSnapy** [pmmp/PocketMine-MP#1268] opened 2017-08-03 09:23 UTC
### Issue description
2 Clients with same name can login at once and dupe items.
### Steps to reproduce the issue

1. First you need 2 devices, after that all you have to do is to enter the server with same name at same time.
2. Once you're logged in drop the items from a device to other one and leave, you can keep doing this and the items will dupe

### OS and versions
* PocketMine-MP:PocketMine-MP_1.6.2dev-340_8a02dbb1
* PHP:7.0.2
* Server OS:Ubuntu
* Game version: PE/W10(Both)

### Plugins
- Test on a clean server without plugins: Yes, the issue works even on a clean server.
### Crashdump, backtrace or other files

* ...

**Comment by dktapps** [comment] 2017-08-03 09:23
duplicate of #1179

**Closed** 2017-08-03 09:23 UTC
