### ISSUE TITLE
I don't see other players moving, but they are indeed moving

### ISSUE THREAD

**Issue by shyamean4151** [pmmp/PocketMine-MP#3312] opened 2020-02-18 06:51 UTC
### Issue description

- Expected result:Players can move from the perspective of others
- Actual result: Player doesn't move in other people's perspective

### Steps to reproduce the issue
1.Use curl -sL https://get.pmmp.io | bash -s- to install PocketMine-MP on a Linux server
2.Use ./start.sh to start pocketmine-mp game server
3.Language is chs
Agree to use agreement
Skip settings
4.After I enter the game server, I then invite my friends to the game server
5.My friends can't see me moving, I can't see my friends moving, but we are always moving

### OS and versions
* PocketMine-MP:3.11.5
* PHP:7.3
* Server OS:Linux
* Game version: PE

### Plugins
No plugin

**Comment by nnnlog** [comment] 2020-02-18 07:33
Duplicate of #3304 & #3308 & #3309.

**Closed** 2020-02-18 08:13 UTC
