### ISSUE TITLE
Control of player falling speed

### ISSUE THREAD

**Issue by ViceEye** [pmmp/PocketMine-MP#5536] opened 2023-01-26 10:47 UTC
## Description
Is there an API that can be implemented for control of a player's falling speed, considering that there is a potion that could be altered to make a player fall slower, but the potion is not very ideal for a long-time behavior

**Comment by xerenahmed** [comment] 2023-01-26 12:10
Duplicate of https://github.com/pmmp/PocketMine-MP/issues/5525

**Closed as completed** 2023-01-26 12:58 UTC
Labels: Resolution: Duplicate, Category: API
