### ISSUE TITLE
Liquids Stop Flowing After Server Restart

### ISSUE THREAD

**Issue by KCodeYT** [pmmp/PocketMine-MP#5845] opened 2023-06-19 05:24 UTC
### Issue description

- Expected result: Liquids should continue to flow normally after the server restarts.
- Actual result: Liquids stop flowing after the server has been restarted.

### Steps to reproduce the issue
1. Start the PocketMine-MP server.
2. Observe the flow of liquids (e.g., water or lava) in the game.
3. Restart the server.
4. Check the flow of liquids again.

### OS and versions

* PocketMine-MP: 5.1.2 (git hash: 7cd317bf398a017f7c690a475c5a67650c610323)
* PHP: 8.1.19
* Using JIT: not supported
* Server OS: Ubuntu 22.04 WSL
* Game version: 1.20.0 Windows 10

### Plugins
none

### Crashdump, backtrace or other files
No crashdump produced.

**Comment by dktapps** [comment] 2023-06-19 10:45
Duplicate of #2099

(well, not quite, but #2099 is the underlying issue)

**Closed as completed by dktapps** 2023-06-19 10:45 UTC
Labels: Resolution: Duplicate, Category: Gameplay, Category: Core
