### ISSUE TITLE
Crash PocketMine-MP version: 1.6.2dev #308 - Error: Return value of pocketmine\entity\Human::getRawUniqueId() must be of the type string, null returned

### ISSUE THREAD

**Issue by teracube** [pmmp/PocketMine-MP#1237] opened 2017-07-24 10:12 UTC
### Issue description
Server Crash /PocketMine-MP version: 1.6.2dev #308

PocketMine-MP Crash Dump Mon Jul 24 11:57:15 CEST 2017

Error: Return value of pocketmine\entity\Human::getRawUniqueId() must be of the type string, null returned
File: src/pocketmine/entity/Human
Line: 103
Type: notice

Code:
[94] 	 */
[95] 	public function getUniqueId(){
[96] 		return $this->uuid;
[97] 	}
[98] 
[99] 	/**
[100] 	 * @return string
[101] 	 */
[102] 	public function getRawUniqueId() : string{
[103] 		return $this->rawUUID;
[104] 	}
[105] 
[106] 	/**
[107] 	 * @param string $str
[108] 	 * @param string $skinId
[109] 	 */
[110] 	public function setSkin($str, $skinId){
[111] 		if(!Player::isValidSkin($str)){
[112] 			throw new \InvalidStateException("Specified skin is not valid, must be 8KiB or 16KiB");
[113] 		}

Backtrace:
#0 src/pocketmine/Server(2254): pocketmine\entity\Human->getRawUniqueId()
#1 src/pocketmine/Player(3489): pocketmine\Server->removeOnlinePlayer(pocketmine\Player object)
#2 src/pocketmine/Server(2291): pocketmine\Player->close(string , string Login timeout)
#3 src/pocketmine/Server(2459): pocketmine\Server->checkTickUpdates(integer 995710, double 1500890235.7568)
#4 src/pocketmine/Server(2221): pocketmine\Server->tick()
#5 src/pocketmine/Server(2100): pocketmine\Server->tickProcessor()
#6 src/pocketmine/Server(1682): pocketmine\Server->start()
#7 src/pocketmine/PocketMine(501): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/gsp_1485/g3.hmserv.eu-19144/PocketMine-MP.phar/, string /home/gsp_1485/g3.hmserv.eu-19144/, string /home/gsp_1485/g3.hmserv.eu-19144/plugins/)
#8 /home/gsp_1485/g3.hmserv.eu-19144/PocketMine-MP.phar(1): require(string phar:///home/gsp_1485/g3.hmserv.eu-19144/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 1.6.2dev #308 [Protocol 113; API 3.0.0-ALPHA7]
Git commit: f32e8805420c177ac491912108b0815627808421
uname -a: Linux ns3023271.ip-151-80-230.eu 4.4.19-mod-std-ipv6-64 #1 SMP Mon Aug 22 13:05:01 CEST 2016 x86_64
PHP Version: 7.0.17
Zend version: 3.0.0
OS : Linux, linux

Loaded plugins:
PurePerms 1.4.1-dev1 by 64FF00 & ProjectInfinity for API(s) 3.0.0-ALPHA7
BlockPets 1.1.0 by BlockHorizons for API(s) 3.0.0-ALPHA7
ItemCasePE 1.1.0-dev1 by aliuly for API(s) 3.0.0-ALPHA7
FactionsPro 1.4.4-dev1 by Tethered_, HostingItAll.com for API(s) 3.0.0-ALPHA7
SignPortal 1.1.3-dev1 by 99leonchang for API(s) 3.0.0-ALPHA7
AlwaysSpawn 2.2.3-dev1 by Philip Shilling for API(s) 3.0.0-ALPHA7
Cameraman 1.1.0-dev by ChalkPE for API(s) 3.0.0-ALPHA7
TreasureChest 1.2.1 by Awzaw for API(s) 3.0.0-ALPHA7
SimpleAuth 1.8.1-dev1 by PocketMine Team, shoghicp, awzaw for API(s) 3.0.0-ALPHA7
SimpleAuthHelper 2.0.5-dev1 by aliuly for API(s) 3.0.0-ALPHA7
PiggyCustomEnchants 1.0.2 by DaPigGuy for API(s) 3.0.0-ALPHA7
essentialsTP 1.1.1-dev2 by  for API(s) 3.0.0-ALPHA7
ChatToDiscord 1.1.0 by eDroid for API(s) 3.0.0, 3.0.0-ALPHA6, 3.0.0-ALPHA7
Parkour 1.5.3 by jdcraft for API(s) 3.0.0-ALPHA7

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtO9ty20aWv9KhUjtyiiABXsRLSqlVZHusXTvmWvL6IZhSNYEm2RGAhtENUXTK/77nnG6AAE05
noy2ah7iFxF9Ofc74N87RqaiMw/Gvj+d+YPhuNtJuDYvikIVnfnvHbPLYbuTKSMj0el2UqE1X+PS
O2HKImP3PCkFUyuWq+hOmFRmIgxFZqTZheGrMuXZfL4W5h3fvs/kx1JcxafPWFpqw5Z0zWwEQyRM
m0Jm6y7LyiRhBQEXMWBcwfNLmSDKfMOLeb/f36hU9Nc6vw1G03F/PextUi2K+54ovWAWjEb9BdHy
Bmjx3ix6eK2vi6i/J7FvKewTgXAgR0QWyVcOwqEE1kBc/rDbMQUHkcx/7Zz47ODSNVAjitPBYDx6
Nn9cMt5Ph5IBDCfBIbRFwncAbTiazg6gWTzeT4VI1b14myF17nTzmF1iavmbiAzhGDxK8Sw4wGEv
ez9FidLi1GqJdZ262Gu1lhlDI1KlBT18DPRo/Bj50UZEdzcyunufx9wIfSozI9ZA8Ww2ngR+l8Wq
XCaC7a20NxmfTQnd6FFOBsEj6MCU76yox49dDnz/K5cXhYrAD1RhoZw9AiU4mw4egaINL4y9PflC
3bXxno79x3i4vY1UBjooI3P6M9fiErxWv1Y8rvXcbd0rjUx0GL7hMgOVrRunnCL/Fd+qgfzx7X/i
aJ6UYFu6T1Kasj9D2SmKrxAfS1nUpvuEQWR/AkPIs84/Pnc74t8ocv5TAQ1otxLvzFc80aLbiVQs
kJPZCKCEhv3Qh/OzMT3k4JAyYqsyi4xUGQNC91T+jufO6FxoLEHse7OR2vupLGX8I25PaPsz/pzC
T/w7o6X+Dz/AAzigQ8r+00GwbNJe0CAo8AePUdQW3dxB+J0uDY+SV8CN91fPf6Qjo5rEwB9bGgP/
rEXkpCYy5wVPK+P+Hv7S/vSx/TuZXcV0ZNbkJfCP8qKFuYYbpwi3W90mMQdB4BiRq9PvbKyez6X+
X57IuL7zzJ0duLOhMZtCbVkmtiwMr7J7Om0g9r54iESOOE/DznUuIrmSImaIkEnNwJgZne3Whjj9
b/kzUwULzuBH2HlGogsq6X7ufP4rUf6VKP9KlH8lylai7HbWIhMFTzC/ZBxbkE4LDLAC6tMQiGAn
6J31BrG4h8VlKZO4Mx/6U0hXhTIqUgADAk63w3MJZ4c9v+d7F68Xry4mcH4tDSyuhgMxnfrj0cCP
gsmER6MZkA7GO13602B8NphM/eloEMCFgt8lcgl3/N6058NC6ch7LbPygWV6CG41mAQ9mXvBOPCm
vjcY+iAMNuqNesHMS1XsaRN7Mr8/885GDMLU9ZsFewNh/KJcs8GABcO5P577Abt8cX3DBn5wxh6m
Z7dnI8CGrci8MwEmAiT/k8jiiim7e6t0RQws0ENCD3X+1ijTRVmIhShS3RRwvdYWLpDtgXSRe16a
jSo0Buuz0cuXvs/+g4ETowNcZSuZQUhG5ZGof23LGpZFxiH6AMHgblA/xCIH8hEY7Gm1Ms+bCynH
UqNza/FA+Kyoa/zE+gRcFWl/e33z4e27189haSuWWhrkaGNMrsFGQcubctmLVNqnu84h9nBAOD8n
YF8LYZoS2a+1JRKQtBvCoIOvVCE/QTB5Ygm0YIdhTVMY2jD1R0JA5q6MSC8hui1eNLhrLH7B3hGF
Q14vk6dWrwUahkBqGgEtubCx9VuYesmp+tFggA2umquHdjw6wtaNgEK5EPFtl71S2kBkuzIXSYLG
8sS8NigLQ/fwrbxey3W2UIVpRcTG4qECh0c4nc0SobJow6FKflrOarizGWTWmqpvU+URJ21Q2m8w
CXK4SLZ8p69zvs0agmiuNiUx6A2OSmKxkYnM2TX8SeSTSyMn6NoBD0NO1Gmk7kufvb65eHfzfvGF
wi+BM+gIeJPN/dpRf23zeLnhyR249tPyFiHUMIwqSsKwSdQf6hnUTBB60PsCkzeF4BqC8OVGaNNg
tL3eZnbQO1DmxfYT3z51WEKYIXZ/REeEdHx7YLqWaZ6ICyCx5az1Ypuh6dH0uq922I3gKWzqjVpv
ZISjSP7/wPKePnThBq1fMdRj+bWmu9+A0hLKK5HkojgqGrfV9mG/N37SdNRUxTekpg3R9KdjGU/E
bzyLCwXgGjWvV1XlYGOin3JtRNH/QhAgt4Vcr3eX0E2r9AWFxFaFcmy3bV5+b9AW3HMOl/5ePnUm
P0LJt3sMNIHY0PNE3ywa3LWWD2MeeU2bt6flqIk9DA9o+UOWIP6aG/Vc6kgVcTOIt9b/oK4Uzwsl
40NNwZkGf2ftxz/PLuGCgN4kMAzTlgofS1cLXtypsunU1Uqbw3Fv2Obwtzgq+Mo8sTE6qGGYWyq+
1RKxScJBnABvrFDQoKAHzSQ4pJECO6qTRf3ELhU0PmuGw9SwCLOT6zJj/1UmbDCEXm7uT6AXrRu5
CZ5IlYnPw9L3+WRm/yT2z91339kfq+pHVP0omP0r3IUbSLmX5VKw+XPWAvU1GIjccuPlUFCdU3dO
FIlUFTsvkak05wN/MHqDq9sNSAUWtTlXqxWu8CxTZRZh7KJRFo82UtyLFPxCn6uM4GOV42HnLai+
PR8HhIE/uEv6fOwTrCRRW2+VyPWmhm8v80ym4GUtgKlaVgtrjuTG4pzArFQB9NRrDtCGFzFYb/2c
3+fudixXKxmVidmdDwgajRmMKjwtDBb/+hyXE2Ar8dCSz7eqSOL9mhYibhzBAfv58xcvL96/vsFV
a6zex1IUO4fSLRURSMPRg797OdcagMfnP9A/EElplKf5vahYt7qS+XlzqII7igaUXpPleym2XgzK
4qCg8yku4UCgzje9XZqg5TJ0BBaR0ZbAOY6P0XYZSJK1Rixgy+wGCh/BKtEwXgh6raAyMHwDcYJF
aBM06JVZlJSxiOEH+8JnENa1Sqv3EocwNV+JLlPYiGkEyZZQeN2xHXiug8XkigG7dtwMqFQBVZmB
9AyAfxHbGlw/FisO6tVsq7K/GcbzXPCCoWhTYDYCs9sB+QzH+Zbv7UZkrMzXBY8BQC/MUPAW2DzM
2MnNBhK0l8ASUJFAR1LytWD47oNE5pSkJTxDZw5FwycSKl69xHGs5aJ9EQioKgWR9bbyTuYilryn
inUfn/qvQZG3anV7df329mw48wa3eA/EWAOasxAi4zrsIKIPG2pimVFATxYz4NKNB0FNBc90wg3I
jbZJmkSpwLk8MEYqhVwqI8Egb8cJKTkFwNa79ijpxQ+s601pYoV+aV9aITF2oMpouh1bsi7QxxlG
EJoX2oKH3UvO/gf9A46Qn1Sl0JxhhMeL1xu4x9FKtQJqHBarKu4AsVKDEUI2AEMg7i4WV3ASEkuM
ctpveEDWEojag39BHlnBAY4ZBgsG5goWgaQud8zZERx3/lvv7sVw8gFaPFAmmBSPY1YIbS0PycTx
NpBD7QMGSHw9shQoDxC6+FjyBNWxlveietN36lBCongGwC0+iBsCg7UH2sRp8xx2EfMvZbrE2fOK
XehdFt1wfQcWX9yBA/Vw/z0ogeyzYhJPbQoFARxMAk7rLqPIxlwEBJPtghhSkJrGbE1igdSIa2mZ
gefgEYJ9TSYD/IBzFeoBorURIAJgh0w9q0lDqVpyrlbooXgEPbHLpPkbSM4UdCsWmCzICg/uslPg
APTMBigR4sFzXM4JEnqrzV7kq39P1BIEi1UBs8uMkhrGpFSs+XJngCB2bUnxCbnUqF7r6cDTVhJh
JGyGKcolR7ekSS4rCeYCYQpSQEagVhAjKoxW/cBMSUa7VsCHQtdAmQGeNRFps+2c+SGFCorKBkIN
j//NyccK6yvEY+r9l4iHBiIn/C5U1fQ4aJqBS2HuhCjjqEGcFUkBlC+WqoUopKJ0hL6oESG9H6uo
q/0tAFQQamK0MTrhgT8I62kUxhXU/Rl4KMgNo8NjYrXihLIpoQiPvm6PhZRwEQZ4396TbThCDG8x
hGCGo+O9Lw8j264OBhG6966axIK0WhnbuzUDIEmR6z2bUIdaPvWzowQ5roeW6zUvlqB/L1JJYks5
9LCjUiVzQlLcHebugO+mPCsp5TapgHKkBFt41q1iwoExOGuwcXW1qmJDureyHntr8x09gUVsVJnE
NSESIsg2Y3vS0W5ZTpQDg2e+b3lkJy/JE76IjWQr9nbN1KpQaRVi8a7b95pRqaFTYMKp7tAUjthP
4x5WytGmzO60lfcbDgG2TCG5ZPhKsqrwkBtmK2rrIXsUaCsOLrkII3Ae1jclhM2RI++5shuHWsPY
jwWShYBHK/uwcNyxJ2CV8o8XcZyuEbPOBCpEuFEn7a+CCrNMGFRBXbGBRSQ2AS65gTYF6w+OxS3k
PTAjF4zI72w96nZtDFqKOhWSCE+aUavaQX8vdmZD39Z4QcOGMeURWs9UpEA0GZ/ZYLJPsdRCYH6L
rQ6xdqPyA+/CoqOpx15BlwTiPYcSGOz1cvG+C3eBgiWEna2MzcYGa3LrGrxH4Ods4uqBfaWgSTCN
oz12EYMbbXiy6kNtb4uXWIB5OUSAkmHrjBpu+GGdlBuwGuXRiwf0Oax+eNK1/oyIP8gMikdgC8xG
kK9hin+/yBZVgbAv1bH2wUtbCPEh1ulZ7rnHZikGjZ1YlmurfuVCJcMkUZBBiwcRlbbGwZiDr017
9a5Gi6DSJd/kPZlJJCMg3qoT1hc/8CLDMN24id2LC8wIxQHoshjSBTKzP5ly8MwUVGpQiEWZ4bce
6MbATkouDZCrGI/ogMfMkyvPre09oapf6RsdtBdRfZTjas8G1hWXIHoyauq4mVoa0B/eIluC2gtO
EPFER+3+EHBXdqeG1mXL0hAfEUeN8SpFRwXXG6K5UejZj8TgEPKB+CrPKrjUhBDyE1rUas8I1iQV
LwSPdrx6rWFbgOgnFmAl6coGbBnICKp2gdSKfLg2InQONyfdOiFq1oeAakoIC/11ZB0ItBHrPaow
s3F2bls6Ba0EirlquETVTFAsjrkBsfB720rir3paglu1EjmoH+Kc4GZeyc0JzFVwVBmDT1FNoXOB
ioAaI1MRvrmim+BBb2pl4HdLrs/QpcA4BlFBY8u9xBfGaBky2pC9YsO+AyXZ9jwhs0zosrM8O5up
IFoyGwJpUotGrC0K27RrKxNse5xMdI2UAKFkGnQ/GbloT5xIaESFambT6udF1dwxa/J2kkFHXfwv
tWs2I4BnKAW4K569Mmc5WMm9TKjNbUUsemspKnAUSakaA7Fg5ETvg8rSVU+YxW1RhjaB8x9cd5VY
ZSqt5arOtW3gNaYstPEl16KB7DSAZHEES5cNYCM4tiFM1HtGiUuLJhXkLPhNGU0VKpUKSM4WH1qo
FRbNb/aDHUyGFHKwcUBF2fegFraD01CVTfouBVaB3AnTxZkMZZ8clkLd6lRrBHZ0DEW96EWqIPhS
j0l1FqZdilgVbygVJBKbcPBb/EllEzt5RzVU4ypZTibsbGUpLKilWGFopcklRjXUj4WNEYHmmY1i
DJQIQcIGU4njI4HjiHxXfcJri7S6wKcMuqLXRVW94PL7qkzomNIm2XkY1WRkayxKCwXOpwwRXzH6
m8LJgK2uNU8FeTPGQKy8qip0H3KP1BAVzcimE4ldztwwraoPbAkqPoKvmy+UjhKulA71LuOHGsrt
d4Igmdru2srxj2qHFwAnpokRBWfQkbvq7NsqYYiZAefQXmk/m9zzHCWCWyQ0CN+PkK6eEyIXrDBE
oQHZZA4uCAVOyhxbzOayqrilK02W2YkHXnnC1pBF9V4o+7lMJZfel4JxGW7LJY3YQLy27gBTdPcp
eNG6p8G25mz6p6DlKi8TB839xhLzAHCYUVzxcpst7STfI5NHY8e2C+wTE39RrwYuxGGqnDPbm1UW
CNLPynzOZrZhs75DAdBWZA4WQBnTNYdx/7zliKpeDeyhdCnBT6tWl+KrnbLNbUzFgSCWNMyuWpt2
Nmj97bAmQ4P3cETbXqkTT2sVikSstvZWtlFoWraKakzsoach+jKV7VJs1MmnNYhY14Ti5MFts/02
EUylCF+vC7F24716cIrtHn51fXecG0sPgtPH6EF5WU8hLR/eBrOwu/O6inUV2L6EpVWVN0a+lzj1
pzG0SFSO2R3KTShOcVyKid12VVAQrUQBfa2HMT/DYg4PuYKw1FRENoEw9/KxUSiW0DtqY5NGFZ4d
NNSQ3a7g6wOhbLfbIyKBuFnXF65CRKh4pWpvUCOYoBAj9RruTjU17tUo3EYvT1NoJmjEWcnvqxWo
S5KkNme5Nvo0i2CAbqwoT355e/Nijm947BqFK5wmuDLdxSsca6+h26I2UK5qOJFKgIt9bdfoXAic
i8xVhw5JAuoKK6EXDxwrOPuAdTvQ59Q0r/RFWxARcBo4Z79SHQ3VRJfGg/9AiDazVSVd840ScYAj
ywJfytBgqnrLR83JscqAimsqVzQ1utQggV4kEOpquQbphJUIoF8MXwpifKN0vsc2Zy9fX9zMBz9O
uuPZQ9AdPgy7gx+DH2MouWxoP8WvPyIMw+dT32YA+zQaP6MXeOLBQDGNrRy+Wr+EuqL5+S96WfM5
j9r7+mMijRjS18oT94nYJ/v5cn1mGUHtummu4KuhLOZFa839d6X9QlkkzeeVTIxoXVmZ1qfK67j1
lLY2NxD67Ncq8PCbrj/YxMd06f5nT+N8GhW73DRXrhev25LITIs+rAqBpxYRudLyobXgBor0SXXQ
wy8r3omVm4q1oG1S1WJAU0zQLRp3IH76PNv9YmPcGqAemIefA4z9kT+Bn99fgfUsx9F45p/Fo/FA
4K/JcMBnw6U/DlbD6WAi/MFkNFtOh+x7gL3YkHoG7useo+5EBkm4Jf8P0ApBuCTlD+mzix2nd8AD
9w3JJ5nbr06GvXFFr9xD+Pz5/wCKuXK+
===END CRASH DUMP===

### Steps to reproduce the issue

1. PocketMine-MP version: 1.6.2dev #308
2. ...

### OS and versions

* PocketMine-MP: PocketMine-MP version: 1.6.2dev #308

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
Unknow

thanks #

**Comment by dktapps** [comment] 2017-07-24 10:12
duplicate of #1220

**Closed by dktapps** 2017-07-24 10:12 UTC

**Comment by teracube** [comment] 2017-07-24 10:14
sorry for duplicate
