### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by irwans123** [pmmp/PocketMine-MP#5836] opened 2023-06-14 15:18 UTC
there is a bug in pocketmine server 5.1

https://github.com/pmmp/PocketMine-MP/assets/102463409/08139d69-dccc-4f66-a4d6-8e52863269bf

**Comment by Gaprix** [comment] 2023-06-14 15:40
Reproduced. Looping debug message appears after putting on the turtle helmet. When I try to remove the turtle helmet, an error appears, which is also provided in the attached log

https://pastebin.com/z9VEFrtf

**Comment by IvanCraft623** [comment] 2023-06-14 15:46
Duplicate of #5786

**Closed as completed by IvanCraft623** 2023-06-14 15:46 UTC
Labels: Resolution: Duplicate, Category: Gameplay
