### ISSUE TITLE
Falling in water from a high height does not cancel the damage.

### ISSUE THREAD

**Issue by Muqsit** [pmmp/PocketMine-MP#514] opened 2017-04-05 10:51 UTC
### Issue description

This is probably the cause of slight network lag. When you fall off a high height into the water, your damage isn't cancelled. While testing, please test it with water of height 1. This doesn't happen when you fall into seas/oceans/hemispherical ponds.

### Steps to reproduce the issue

1. Place water.
2. Create a 20m high tower.
3. Fall off the tower into the water.
4. You are dead-dead.

### OS and versions

* PocketMine-MP: 202bac2
* PHP: 7.0.17
* Server OS: Ubuntu 14.04 64-bit
* Game version: Win10

### Crashdump, backtrace or other files

-==-

**Comment by dktapps** [comment] 2017-04-05 10:52
Duplicate of #470

**Closed by dktapps** 2017-04-05 10:52 UTC

**Comment by Muqsit** [comment] 2017-04-05 10:57
My bad. I don't know how I missed that issue.
