### ISSUE TITLE
Head/body do not rotates

### ISSUE THREAD

**Issue by udwarf** [pmmp/PocketMine-MP#992] opened 2017-06-03 21:30 UTC
When one player is moving or rotating head - other player see him staring always in the same direction.
Was checked on the latest master without plugins.

how to reproduce: 
run php src/pocketmine/PocketMine.php, 
connect 2 player and try to look to each other

* PocketMine-MP: This server is running PocketMine-MP 1.6.2dev 「Unleashed」 implementing API version 3.0.0-ALPHA5 for Minecraft: PE v1.1.0.55 (protocol version 113)
* PHP: PHP 7.0.3
* Server OS: Win8
* Game version: Clients was win10 1.1.0 and android 1.1.0.55

**Comment by Qimie** [comment] 2017-06-03 21:31
Of course u need to run the server lol XD

**Comment by jasonwynn10** [comment] 2017-06-03 21:33
It work's just fine for me

**Comment by ZaydPE** [comment] 2017-06-03 21:33
Can confirm this. To reproduce, simply PvP and move around a lot.

**Comment by jasonwynn10** [comment] 2017-06-03 21:38
x32 or x64 bit server?

**Comment by ZaydPE** [comment] 2017-06-03 21:38
x64 I'm sure... 
It appears as if the player is hitting him from the back.

**Comment by udwarf** [comment] 2017-06-03 21:41
server was run on Win8 x64

Moreover, plugin that rotates statues stop to work: all statues staring in the one direction instead of looking at the player

**Comment by MCPEPIG** [comment] 2017-06-04 01:13
Happens to me too.

**Comment by SuperMaXAleX** [comment] 2017-06-04 05:54
Never happened to me .-.

**Comment by AppleMinerHD** [comment] 2017-06-04 08:07
Happens to me to...

**Comment by dktapps** [comment] 2017-06-04 08:15
I'm unable to reproduce this. Can you provide any more detail?

**Comment by thebigsmileXD** [comment] 2017-06-04 08:38
@dktapps you just mentioned it in the mojagn group, SetEntityMotionPacket is broken

**Comment by dktapps** [comment] 2017-06-04 08:39
SetEntityMotionPacket does not have anything to do with rotation. I said the rotation issues may be related because of the giant mess they made of motion+movement this update.

**Comment by Lazerplayz** [comment] 2017-06-04 08:50
This happens to me, tp to another world and have more than 1 player on the world and this issue will happen.

**Comment by thebigsmileXD** [comment] 2017-06-04 08:54
I think no more "me too" comments are needed ;) ty

**Comment by Matthww** [comment] 2017-06-04 10:10
Reproduced on 64 bit system with version: b01ad01

https://www.youtube.com/watch?v=Rp2y2CMkpMk
Here is a video it's bit laggy but around 00:11 you will see that the player is looking forward but the arrows shoot in a total different direction.

**Comment by dktapps** [comment] 2017-06-04 10:13
Marked this as Community Consensus, I'm still unable to reproduce. This is clearly a problem though :S

**Comment by Driesboy** [comment] 2017-06-04 12:43
Works on 32 bit

**Comment by IrishPacks** [comment] 2017-06-04 15:22
I've reproduced this on the latest commit, and someone I work with has reproduced this with the god awful spoon that starts with a T.

Maybe this is the revenge that the PHP gods are sending to Dylan, because he is removing 32 bit compatibility 😱

**Comment by dktapps** [comment] 2017-06-04 15:27
> he is removing 32 bit compatibility

I have _proposed_ removal of 32-bit compatibility.

This issue is a pain in the ass. I have no idea how to reproduce it or what might be causing it, so  I'm in a difficult position. I need reproducing information.

**Comment by dktapps** [comment] 2017-06-04 15:29
and naturally as soon as I said that, I reproduced it... it happened after a teleport.

**Closed** 2017-06-04 15:54 UTC
Labels: Category: Gameplay, Status: Debugged

**Comment by MetalMinurz** [comment] 2017-07-31 14:22
Im having this issue now, even though it says debugged.

**Comment by MetalMinurz** [comment] 2017-07-31 14:23
I think it may be a bug or something.

**Comment by MetalMinurz** [comment] 2017-07-31 14:23
That comes with a plugin i use...
