### ISSUE TITLE
Server crashed after teleport another world

### ISSUE THREAD

**Issue by Eren5960** [pmmp/PocketMine-MP#3955] opened 2020-12-05 17:53 UTC
```
20:50:57.685 CRITICAL > InvalidArgumentException: "Cannot add an Entity in an ungenerated chunk" (EXCEPTION) in "src/world/World" at line 2156
20:50:57.686 CRITICAL > #0 src/entity/Entity(1445): pocketmine\world\World->addEntity(object Eren5960\SkyBlock\SkyPlayer)
20:50:57.687 CRITICAL > #1 src/player/Player(667): pocketmine\entity\Entity->switchWorld(object pocketmine\world\World)
20:50:57.687 CRITICAL > #2 plugins/Core/src/StormGames/SGCore/SGPlayer(653): pocketmine\player\Player->switchWorld(object pocketmine\world\World)
20:50:57.687 CRITICAL > #3 plugins/Core/plugins/SkyBlock/src/Eren5960/SkyBlock/SkyPlayer(165): StormGames\SGCore\SGPlayer->switchWorld(object pocketmine\world\World)
20:50:57.688 CRITICAL > #4 src/entity/Entity(1316): Eren5960\SkyBlock\SkyPlayer->switchWorld(object pocketmine\world\World)
20:50:57.690 CRITICAL > #5 src/entity/Entity(1344): pocketmine\entity\Entity->setPosition(object pocketmine\world\Position)
20:50:57.690 CRITICAL > #6 src/entity/Entity(1415): pocketmine\entity\Entity->setPositionAndRotation(object pocketmine\world\Position, double 0, double 0)
20:50:57.691 CRITICAL > #7 src/player/Player(2247): pocketmine\entity\Entity->teleport(object pocketmine\world\Position, NULL , NULL )
20:50:57.691 CRITICAL > #8 plugins/Core/src/StormGames/SGCore/commands/MazeCommand(22): pocketmine\player\Player->teleport(object pocketmine\world\Position)
20:50:57.691 CRITICAL > #9 src/command/SimpleCommandMap(244): StormGames\SGCore\commands\MazeCommand->execute(object Eren5960\SkyBlock\SkyPlayer, string[8] labirent, array[0])
```

**Comment by dktapps** [comment] 2020-12-05 18:04
Duplicate of #3947

**Closed by dktapps** 2020-12-05 18:04 UTC
