### ISSUE TITLE
Weird behavior when cancelling PlayerToggleSneakEvent

### ISSUE THREAD

**Issue by DaPigGuy** [pmmp/PocketMine-MP#950] opened 2017-05-28 21:11 UTC
### Issue description

 When I cancel PlayerToggleSneakEvent, instead of cancelling the sneaking, it unsneaks and sneaks non stop til I unsneak manually. Results from var_dump shows the event is constantly triggered with isSneaking as true.

### Steps to reproduce the issue

1. Cancel PlayerToggleSneakEvent when the player sneaks
2. Go in game
3. Sneak

### OS and versions

* PocketMine-MP: Build #748 on Poggit
* PHP: 7.0.3
* Server OS: Windows 10
* Game version: PE

### Crashdump, backtrace or other files

Code:
```php
    /**
     * @param PlayerToggleSneakEvent $event
     *
     * @priority HIGHEST
     * @ignoreCancelled true
     */
    public function onSneak(PlayerToggleSneakEvent $event)
    {
        $player = $event->getPlayer();
        var_dump($event->isSneaking());
        if ($event->isSneaking()) {
            $this->checkArmorEnchants($player, $event);
            $event->setCancelled();
        }
    }
```

**Comment by MCPEPIG** [comment] 2017-05-28 21:35
Same effect if you have a delayed task setting sneaking to false instead of cancelling the task.

**Comment by dktapps** [comment] 2017-05-28 22:15
Likely a client/server feedback loop. Not sure why it would be doing that, it used to work fine...

**Comment by dktapps** [comment] 2017-05-28 22:44
Confirmed, it's a feedback issue. Client-sided bug.

**Comment by dktapps** [comment] 2017-05-29 09:11
Reported as https://bugs.mojang.com/browse/MCPE-22113

**Comment by dktapps** [comment] 2017-09-01 18:43
Since this is a client bug I'm going to close this as Won't Fix.

**Closed by dktapps** 2017-09-01 18:43 UTC
Labels: Category: Client (all), Category: Plugin API, Status: Reproduced
