### ISSUE TITLE
Blocks are not broken with EFFICIENCY Enchantment

### ISSUE THREAD

**Issue by Prisane** [pmmp/PocketMine-MP#445] opened 2017-03-21 22:27 UTC
### Issue description

I showed the problem with the video
https://www.youtube.com/watch?v=Jru4svI2zoo&feature=youtu.be

### OS and versions

*  @PocketMine-MP: [c040579](https://github.com/pmmp/PocketMine-MP/commit/c040579e090e3461829e42b62db50d0085b81e5b)
* PHP: 7
* Server OS: linux
* Game version: PE/Win10

**Comment by JackNoordhuis** [comment] 2017-03-21 22:43
Duplicate of #414

**Comment by Prisane** [comment] 2017-03-21 22:49
You suggest it a temporary solution?

**Closed** 2017-03-22 08:32 UTC
