### ISSUE TITLE
Raklib Crashed on many players

### ISSUE THREAD

**Issue by SiNo195** [pmmp/PocketMine-MP#2643] opened 2019-01-05 06:43 UTC
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 1052672 bytes) in phar:///home/skhidc/pm2/PocketMine-MP.phar/vendor/pocketmine/raklib/src/server/Session.php on line 464

..

**Comment by Frago9876543210** [comment] 2019-01-05 06:53
Replace these values ​​to allow PM to use more RAM.
![default](https://user-images.githubusercontent.com/13465245/50721379-a3916400-10cf-11e9-9427-8502a4c12e7c.png)

**Comment by dktapps** [comment] 2019-01-05 08:57
Duplicate of #2522

**Closed by dktapps** 2019-01-05 08:57 UTC
