### ISSUE TITLE
Manual Crafting is being reverted (PMMP 3.11.6, MC:BE 1.14.x)

### ISSUE THREAD

**Issue by AthasGames** [pmmp/PocketMine-MP#3380] opened 2020-03-31 14:41 UTC
Attempting to manually craft an item results in the materials being restored to the player's inventory, but using the recipe book works. 

PocketMine-MP: 3.11.6
Server OS: Android (yeah, yeah, I know.)
PE/Win10 (same results in both)

- If you remove all plugins, does the issue still occur? - Yes

No crashes, no crashdumps to submit.

**Comment by dktapps** [comment] 2020-05-14 00:00
Closing due to unable to reproduce. If the issue still occurs, you'll need to provide more detail.

**Closed by dktapps** 2020-05-14 00:00 UTC
