### ISSUE TITLE
Players gets fall damage when jumping off 2 blocks

### ISSUE THREAD

**Issue by JavierLeon9966** [pmmp/PocketMine-MP#5334] opened 2022-10-12 21:35 UTC
### Issue description

- Expected result: Player shouldn’t get fall damage from jumping off 2 blocks
- Actual result: Player gets 1HP of fall damage from jumping off 2 blocks

### Steps to reproduce the issue
1. Make a 2 block pillar
2. Jump off it

### OS and versions

* PocketMine-MP: 4.9.0
* PHP: 8.0.12
* Using JIT: no 
* Server OS: linux
* Game version: iOS

### Plugins

None

### Crashdump, backtrace or other files

https://user-images.githubusercontent.com/58715544/195451901-0c3e727b-956a-4727-9ad8-5bb3f9ea0874.mp4

**Comment by dktapps** [comment] 2022-10-12 21:49
Duplicate of #4686

**Closed as completed by dktapps** 2022-10-12 21:49 UTC
Labels: Resolution: Duplicate, Category: Gameplay
