### ISSUE TITLE
Threads try to redeclare vendor libraries

### ISSUE THREAD

**Issue by TwistedAsylumMC** [pmmp/PocketMine-MP#3795] opened 2020-08-25 12:54 UTC
### Issue description

- Expected result: When starting a new thread, the thread should have no issues & should call the onRun() method
- Actual result: The thread crashed because it is trying to redeclare a vendor library

### Steps to reproduce the issue
1. Create a new class extending ``\pocketmine\thread\Thread``
2. Add a basic ``onRun()`` method
3. Start the thread

### OS and versions

* PocketMine-MP: 4.0.0+dev, Commit [a9871a6](https://github.com/pmmp/PocketMine-MP/commit/a9871a6c1a712e1bb2db9a617168c5cb3b280d76)
* PHP: PHP 7.3.13
* Server OS: Windows 10
* Game version: Win10

### Plugins

- If you remove all plugins, does the issue still occur? No, as a plugin is required to create & start the thread

### Crashdump, backtrace or other files

Script plugin used to reproduce the bug
```php
<?php
declare(strict_types=1);

/**
 * @name ThreadTest
 * @main threadtest\ThreadTest
 * @version 1.0.0
 * @api 4.0.0
 */
namespace threadtest {

	use pocketmine\plugin\PluginBase;
	use pocketmine\thread\Thread;
	use function var_dump;

	class ThreadTest extends PluginBase {

		protected function onEnable(): void {
			$thread = new TestThread();
			var_dump($thread->start());
		}
	}

	class TestThread extends Thread {

		protected function onRun(): void {
			var_dump("Hello World!");
		}
	}
}
```
Output of above:
```
[12:49:27.822] [Server thread/INFO]: Enabling ThreadTest v1.0.0
bool(true)

Fatal error: Cannot redeclare Respect\Stringifier\stringify() (previously declared in phar://C:/Users/twist/Documents/Servers/PM 4.0/PocketMine-MP.phar/vendor/respect/stringifier/src/stringify.php:18) in phar://C:/Users/twist/Documents/Servers/PM 4.0/PocketMine-MP.phar/vendor/respect/stringifier/src/stringify.php on line 27
```

**Comment by SOF3** [comment] 2020-08-25 13:01
Your error message does not match the code you used to reproduce this error.
Does this error occur when the classes are declared in different files?

**Comment by TwistedAsylumMC** [comment] 2020-08-25 13:02
Yes, that's how I originally discovered the issue. I wrote the script plugin afterwards (and tested with it) so I could easily attach it to the issue

**Comment by NoTdEmONicGG** [comment] 2020-08-25 13:05
tried getting gooD?

**Comment by dktapps** [comment] 2020-08-25 13:23
and, this, guys and gals, is why you use PTHREADS_INHERIT_NONE.

This problem is not solvable in any way that doesn't break things, short of just using PTHREADS_INHERIT_NONE. The file declaring this function is directly included by the composer autoloader when it's registered. Since composer doesn't use require_once() (and pthreads fucks up such things anyway with PTHREADS_INHERIT_INCLUDES enabled), this issue occurs.

Since there is no real solution to this problem, I'm closing the issue.

**Closed by dktapps** 2020-08-25 13:23 UTC
