### ISSUE TITLE
Map load error

### ISSUE THREAD

**Issue by RompeCraneos** [pmmp/PocketMine-MP#987] opened 2017-06-03 17:30 UTC
### Issue description
Some maps aren't loading on level change, parts of the maps are corrupted by previously map, blocks are transparent

### Steps to reproduce the issue
1. ... Join with latest build
2. ... Teleport to other map

### OS and versions
* PocketMine-MP: master branch 1.6.2dev [Protocol 113; API 3.0.0-ALPHA5]
* PHP: 7.0.3
* Server OS: WINNT, win
* Game version: Win10

### Crashdump, backtrace or other files

* ...

**Comment by dktapps** [comment] 2017-06-03 17:30
This is a client-sided issue and also a duplicate of #843 .

**Closed by dktapps** 2017-06-03 17:30 UTC
