### ISSUE TITLE
Player movement updates when teleporting

### ISSUE THREAD

**Issue by xLordShadow** [pmmp/PocketMine-MP#4921] opened 2022-03-22 18:23 UTC
### Issue description

- Expected result: What were you expecting to happen?
- - When I teleport with an ender pearl, it sends the updated player position.
- Actual result: What actually happened?
- - The player teleports, but their position to other players dosnt update until they move / send a input update. 

### Steps to reproduce the issue
1. Jump and throw a pearl
2. When you land, dont move your mouse/touch your keyboard.

**NOTE:** This only happens if the user jumps before they pearl. If you dont jump it works as intended. 

### OS and versions
* PocketMine-MP: 4.2.0
* PHP: 8.0.13
* Using JIT: No
* Server OS: Linux
* Game version: Win10/Mobile

### Plugins
- Plugins (0):

- If you remove all plugins, does the issue still occur?
- - Yes
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - - No
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

### Crashdump, backtrace or other files
- None needed

**Comment by dktapps** [comment] 2022-03-22 20:29
Duplicate of #4394

**Closed as completed by dktapps** 2022-03-22 20:29 UTC
Labels: Resolution: Duplicate, Category: Gameplay, Category: Client
