### ISSUE TITLE
Dust and redstone (maybe others) particles are don't working

### ISSUE THREAD

**Issue by Eren5960** [pmmp/PocketMine-MP#3176] opened 2019-11-02 12:58 UTC
### Issue description
some particles are don't working like this code
```php

$sender->getWorld()->addParticle($sender->getPosition(), new DustParticle(new Color(255, 0, 0)));
```

### OS and versions
* PocketMine-MP: 4.0.0+dev (protocol version 361)
* PHP: 7.3.6
* Server OS: Windows 10

### Plugins
no plugins

### Crashdump, backtrace or other files
no crash

**Comment by dktapps** [comment] 2019-11-02 13:13
Duplicate of #3158, #3032 , #3002 , #2572

**Closed by dktapps** 2019-11-02 13:13 UTC
