### ISSUE TITLE
Player getGamemode() return null when Respawn

### ISSUE THREAD

**Issue by AkmalFairuz** [pmmp/PocketMine-MP#3016] opened 2019-07-13 04:27 UTC
### Issue description
Can't return player->getGamemode() when PlayerRespawnEvent. Tested with no plugins.

### Steps to reproduce the issue
1. Use this code on PlayerRespawnEvent
`$player = $event->getPlayer();
var_dump($player->getGamemode());`
2. Death and respawn, check console and return null.

### OS and versions

* PocketMine-MP: 3.9.0
* PHP: 7.2
* Server OS: Ubuntu 16.04
* Game version: PE

**Comment by dktapps** [comment] 2019-07-13 08:35
Please provide a backtrace.

**Comment by dktapps** [comment] 2019-07-13 14:36
Unable to reproduce. Closing until further detail is provided.

**Closed by dktapps** 2019-07-13 14:36 UTC
Labels: Category: Core, Status: Unconfirmed
