### ISSUE TITLE
Knockback is "flat"

### ISSUE THREAD

**Issue by artulloss** [pmmp/PocketMine-MP#2315] opened 2018-07-20 04:08 UTC
### Issue description

The player->knockback is entirely flat, there is no vertical push upwards when hitting and it makes PvP very bad.

- Expected result: What were you expecting to happen?
Knockback to be how it was on 1.4
- Actual result: What actually happened?
The player didn't get hit up at all and it felt very flat
### Steps to reproduce the issue

1. Make a PvP server
2. Listen to 15+ complaints a minute about the KB being awful
3. In all seriousness the best way to experience this is to set the damage event cancelled to false in order to hackily make the server like PC combo then hit another player rapidly, you'll notice they don't get pushed up at all.

### OS and versions
3.1.0 Release

NO support whatsoever will be provided for third-party modified variants of PocketMine-MP. Issues relating to third-party modifications will be closed as spam.

Note that 32-bit platforms are no longer supported by PocketMine-MP and issues concerning 32-bit platforms will be closed.
-->
* PocketMine-MP: 3.1.0 Release
* PHP: 7.2
* Server OS: Ubuntu 16
* Game version: All platforms - 1.5.0

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

Yes

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here

* ...

**Comment by dktapps** [comment] 2018-07-20 07:55
This is intended behaviour. The old behaviour was broken and allowed OP knockback when using auto clickers in PvP.

**Comment by artulloss** [comment] 2018-07-20 10:46
What commit was it to fix it back /:

**Comment by dktapps** [comment] 2018-07-20 10:53
it's this one: 0081e30a896a730f9598353353f6ee258803850e

but... I just noticed that the kb code I was looking at was from post-1.9 combat update, and now PM kb doesn't match MCPE vanilla. The old logic matched pre-1.9. My bad.

I'll revert that for the next 3.0 and 3.1 releases.

**Comment by dktapps** [comment] 2018-07-20 10:58
Fixed in 2b30ef16718542a20ce89f44013e42140277400e, the fix will be in releases 3.0.8 and 3.1.1. Thanks.

**Closed by dktapps** 2018-07-20 10:58 UTC
Labels: Category: Gameplay, Resolution: Works As Intended

**Comment by artulloss** [comment] 2018-07-20 13:52
Thank god
