### ISSUE TITLE
Player's position not updating for others when teleporting

### ISSUE THREAD

**Issue by FaigerSYS** [pmmp/PocketMine-MP#921] opened 2017-05-16 08:49 UTC
### Issue description

Player's position not updating for others when teleporting. It updates only after player has moved.

### Steps to reproduce the issue

1. Teleport (using Player::teleport()) Player1 (P1) to another position that is visible by Player2 (P2)
2. After P1 was successfully teleported, P2 must see P1 at the new position, but he will not see P1 there until P1 moves

### OS and versions

* PocketMine-MP: 0935855d
* PHP: 7.0.16
* Server OS: Ubuntu 14.04 x64
* Game version: 1.0.8 PE

**Comment by dktapps** [comment] 2017-05-16 08:54
- Unable to reproduce with steps provided
- not enough detail provided. 

Do not assume that just because you find a problem easy to reproduce, at everyone else attempting to will also be able to do so. This issue will be closed until clear reproducing steps are given. What exactly did you do, what were you expecting, what actually happened?

**Comment by Falkirks** [comment] 2017-05-16 13:59
But this actually does happen sorta...I found this when I was making Specter. When teleport is called, PocketMine sends a packet to the player who needs to teleport. Then once that player sends a move packet back (that satisfies the delta requirements) it is broadcast to all players. Still, I am not sure if this is a real issue.

**Comment by dktapps** [comment] 2017-05-16 14:08
Yes, it does, and eventually I found a reproducing test case and debugged it, however this took a lot of experimentation due to the lack of useful information in this issue. I closed this issue as not reproducible before I stumbled across a reproducing test case after looking at the code.

**Comment by FaigerSYS** [comment] 2017-05-16 14:19
I updated the issue. Is it okay now? Can it be reopened?

**Comment by dktapps** [comment] 2017-05-16 14:22
A reproducing test case (including numbers, don't leave out any details that might be useful):
- Have a player1 fly and player2 watch
- /tp player1 ~ ~100 ~ (directly upwards so no client interference)
- player1 is still in the same place as seen by player2
- player1 turns head, position updates

**Comment by daniktheboss** [comment] 2017-05-19 04:37
Maybe send updated position to client2 when client1 tp's?

**Comment by mal0ne-23** [comment] 2017-06-05 13:57
doesnt pocketmine ignore spammed packets of the player moving or something like that? Maybe the server doesnt see that the player has physcially moved yet due to that and ignores the teleport, am i making sense?

**Comment by Qimie** [comment] 2017-06-05 14:01
Kinda true actually bc i remember someone say that b4. Good Theory dude.

**Comment by dktapps** [comment] 2017-06-05 14:03
Nice theory, but it's incorrect. It simply isn't sending the teleport to other players, only the player who was teleported

**Closed** 2017-06-05 15:47 UTC
Labels: Category: Gameplay, Status: Debugged
