### ISSUE TITLE
Force kill on shutdown

### ISSUE THREAD

**Issue by alex2534alex** [pmmp/PocketMine-MP#170] opened 2016-12-17 07:28 UTC
### Issue description
Server killed forcefully after "Stopping other threads"

### Steps to reproduce the issue

1. Stop server

### OS and versions

* PocketMine-MP: 61e8828
* PHP: 7.0.13
* Server OS: Linux Mint 18

### Crashdump, backtrace or other files

> [Server thread/INFO]: Stopping other threads
> 
> Took too long to stop, server was killed forcefully!

**Comment by alex2534alex** [comment] 2016-12-17 07:30
Not always, but very often

**Comment by robske110** [comment] 2016-12-17 07:32
Hmm, I guess we need to add some more debug to this, because we don't need which thread wouldn't want to die...

**Comment by alex2534alex** [comment] 2016-12-17 07:35
@robske110

> [Server thread/INFO]: Stopping other threads
> [Server thread/DEBUG]: Stopping Console thread
> [Server thread/DEBUG]: Stopping Asynchronous Worker #1 thread
> [Server thread/DEBUG]: Stopping Asynchronous Worker #2 thread
> [Server thread/DEBUG]: Stopping Server Killer thread
> 
> Took too long to stop, server was killed forcefully!

**Comment by robske110** [comment] 2016-12-17 07:36
Hmm, that is interesting. It was trying to actually stop the Server Killer thread already...

**Comment by robske110** [comment] 2016-12-17 07:37
This is the old issue with the logger not exiting, I think this is also a duplicate issue

**Comment by SOF3** [comment] 2016-12-17 07:47
Possible duplicate of #25

**Comment by dktapps** [comment] 2016-12-17 10:06
No, this is an issue with the Server Killer itself. You can see from the log that all other threads have stopped successfully. I've seen this issue occasionally myself where the server killer fails to stop. This may be a pthreads bug.

**Comment by robske110** [comment] 2016-12-17 11:15
Wrong, the debug message [Server thread/DEBUG]: Stopping Server Killer thread is caused by the attempt to quit it in the foreach loop, this is actually stuck at joining logger again, you can add an echo() just before the join for the truth ;)

**Comment by dktapps** [comment] 2016-12-17 11:16
@robske110 no, because then the server killer _would have stopped.

**Comment by robske110** [comment] 2016-12-17 11:17
it probably doesn't react to the quit function. Please add the debug echo to verify for yourself.

**Comment by dktapps** [comment] 2016-12-18 13:37
In Ubuntu 16.10, this happens _every single time_ I shut the server down. Quite irritating to be truthful.

**Comment by L3ice** [comment] 2017-01-25 14:01
> [Server thread/INFO]: Stopping other threads
> [Server thread/DEBUG]: Stopping Console thread
> [Server thread/DEBUG]: Could not stop Console thread: STDIN is being piped from another location and the pipe is blocked, cannot stop safely
> [Server thread/DEBUG]: Stopping Asynchronous Worker #1 thread
> [Server thread/DEBUG]: Asynchronous Worker #1 thread stopped successfully.
> [Server thread/DEBUG]: Stopping Asynchronous Worker #2 thread
> [Server thread/DEBUG]: Asynchronous Worker #2 thread stopped successfully.
> [Server thread/DEBUG]: Stopping Server Killer thread
> [Server thread/DEBUG]: Server Killer thread stopped successfully.

Is this a different issue?

**Comment by robske110** [comment] 2017-01-25 14:02
That is no issue, it's simply a debug message.

**Comment by L3ice** [comment] 2017-01-25 14:08
@robske110 
> [Serverthread/DEBUG]: Could not stop Console thread: STDIN is being piped from another location and the pipe is blocked, cannot stop safely

> Some threads could not be stopped, performing a force-kill

> bin\php\php.exe: Exit 1.

I think that is indeed an issue

**Comment by robske110** [comment] 2017-01-25 14:09
Would be nice to know what 'some threads' are :)
But yes, that issue may be related to this one. We think this is an pthreads, maybe it'll get fixed with PHP7.1 pthreads...

**Comment by dktapps** [comment] 2017-01-25 14:12
@L3ice your issue is the underlying issue behind #25 . It's just better managed now. Don't worry about it, it doesn't harm anything.

**Comment by dktapps** [comment] 2017-01-25 14:20
I recommend you use PowerShell to run PocketMine-MP on Windows now. The issue will not occur under PowerShell. The reasons why the issue occurs are detailed at #171

**Comment by L3ice** [comment] 2017-01-25 14:56
@dktapps I already use Powershell(and its great, except for that spacing issue when you maximize the window, that is also occuring in cmd.exe) instead of MinTTY.
And I already read the whole text, maybe not good enough! 
So as a user I just have to wait for updated php binaries to get this fixed?

**Comment by dktapps** [comment] 2017-05-18 12:54
@alex2534alex how many CPU cores does the machine have available?

I've observed that on a Ubuntu virtual machine with one logical core, the server killer will not start until something attempts to join it, resulting in a force-kill on shutdown. With 2 or more cores, the issue does not occur.

**Comment by alex2534alex** [comment] 2017-05-18 13:10
I have Intel Celeron with 1 CPU core and frequently 2.2 GHz

**Comment by dktapps** [comment] 2017-05-18 13:20
Well... that explains it. You need a better machine ;)

**Comment by alex2534alex** [comment] 2017-05-18 13:24
I also think so, but I can't afford it 😔

**Comment by dktapps** [comment] 2017-05-18 13:46
@alex2534alex would you mind testing https://github.com/pmmp/PocketMine-MP/tree/1a4c79b99d0fed7de5a5e651326f1b69287c8b39 please? Works for me on a single-core virtual machine.

**Comment by alex2534alex** [comment] 2017-05-18 14:11
Tested. Fix works :)

**Comment by thebigsmileXD** [comment] 2017-05-18 14:51
Finally! Works like a charm <3

**Closed** 2017-05-18 14:58 UTC
Labels: Category: PHP (extension), Status: Debugged
