### ISSUE TITLE
Lose item on crafting table

### ISSUE THREAD

**Issue by leolee3914** [pmmp/PocketMine-MP#4315] opened 2021-07-16 11:47 UTC
### Issue description

Use 512 planks to craft 64 chests

- Expected result: 64 chests can be crafted
- Actual result: the player was kicked from the server (Too many packets in a single batch) and 14 chests was lost

### Steps to reproduce the issue
1. get 512 planks
2. right click the crafting table
3. put 8 sets of planks to crafting table
4. press shift to craft the chests and you will be kicked from the server
5. join the server and check your inventory

### OS and versions

* PocketMine-MP: 3.22.0
* PHP: PHP 7.4.20 (cli) (built: Jun 29 2021 14:57:19)
* Server OS: Windows 10
* Game version: Win10

### Plugins

- If you remove all plugins, does the issue still occur? Y
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

### Crashdump, backtrace or other files

Video: https://youtu.be/-SM08c-F3bk
Server console: https://pastebin.com/JKWLnY0F
![image](https://user-images.githubusercontent.com/15855635/125942687-7daf06f1-6a3e-4055-ab8d-adb32c9cf294.png)

**Comment by dktapps** [comment] 2021-07-16 12:05
Duplicate of #3954

**Closed by dktapps** 2021-07-16 12:05 UTC

**Comment by leolee3914** [comment] 2021-07-16 12:26
I think this is not a duplicate issue. Before I open this issue, I have read the previous issue. They don't mention that items will be lost.

**Comment by dktapps** [comment] 2021-07-16 12:55
The underlying issue remains the same.

**Comment by leolee3914** [comment] 2021-07-16 14:46
I reproduced the issue with other methods, and this method will not cause "Too many packets in a single batch".

1. put any stuff to crafting grid (2x2 or 3x3)
2. keep the inventory opening and close the minecraft
3. join the server and check your inventory

**Comment by leolee3914** [comment] 2021-07-16 16:26
```
	function pq ( PlayerQuitEvent $e ) {
		$e->getPlayer()->doCloseInventory();
	}
```
Using a plugin with above code can be solve this issue.  So this is not a duplicate issue.
