### ISSUE TITLE
Immortal mobs

### ISSUE THREAD

**Issue by MrHoller** [pmmp/PocketMine-MP#4506] opened 2021-10-12 22:12 UTC
### Issue description

- Expected result: What were you expecting to happen? Mob will die
- Actual result: What actually happened? The mob remains alive, and becomes invisible until it disappears from the field
Video: https://icedrive.net/0/a5e75VeZiU

### Steps to reproduce the issue
1.  Kill the mob

### OS and versions

* PocketMine-MP: 4.0.0
* PHP: 8.0
* Using JIT: no (delete as appropriate) 
* Server OS: Ubuntu 18
* Game version: All versions

### Plugins

- If you remove all plugins, does the issue still occur? Yes

**Comment by dktapps** [comment] 2021-10-13 19:39
Closing as unable to reproduce (in 4.0.0-BETA6+dev (git hash: 8523f0fb0bcd83e7ed20ec20525b3a916be7fe45-dirty)).

**Closed as completed by dktapps** 2021-10-13 19:39 UTC
Labels: Category: Core, Resolution: Cannot Reproduce
