### ISSUE TITLE
All players on PM Windows server have same ips

### ISSUE THREAD

**Issue by buggerfinder** [pmmp/PocketMine-MP#405] opened 2017-03-09 09:40 UTC
if you start server on windows and invite some players with different ips that they all will have same ip (they ip will be as server ip)

Also i tried :
1) Reinstall windows 7 64bit
2) Change the PHP binary
3) Change the kernel for example to Tesseract (bug is still in other kernels too)
4) Deactivate the standart windows firewall

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/93896977d0ba5cf23748b8c4a7e108daa196ce8b
* PHP: 7
* Server OS: Win7 64bit
* Game version: MCPE 1.0.3.0

![image](https://cloud.githubusercontent.com/assets/19263759/23562553/8db5db66-004b-11e7-8d80-7c37e8491767.png)

**Comment by dktapps** [comment] 2017-03-09 09:42
`Last` is not a valid version. Please provide a git hash as the issue template specifies.

**Comment by buggerfinder** [comment] 2017-03-09 09:44
@dktapps done.

**Comment by dktapps** [comment] 2017-03-09 09:46
Nobody in the development team uses Windows 7, so this is a little difficult to debug. I cannot reproduce this on Windows 10.

**Comment by buggerfinder** [comment] 2017-03-09 09:49
@dktapps as for me i will run official server on ubuntu or debian. But a write plugins and test it on the win7 os. Also you can try to reproduce it on virtual box on you can install win7 64bit on the empty local disc, if you have.

**Comment by dktapps** [comment] 2017-03-09 09:52
Correction: I have seen this happen, but only when using an external IP to connect to a server on the same network. That would be expected behaviour, since you _do_ have the same IP, since you're connecting the the server via the same IP that the server is forwarded to. Notice that the port numbers are different?

**Comment by dktapps** [comment] 2017-03-09 09:58
This is clearly not an issue with PocketMine-MP. If an incorrect IP was being reported, then that would be an issue with RakLib and would probably make it impossible to connect. Since that isn't the case, I'm going to close this as invalid.

**Closed by dktapps** 2017-03-09 09:58 UTC
Labels: Category: Core, Status: Unconfirmed

**Comment by buggerfinder** [comment] 2017-03-09 10:33
@dktapps but ehat i must do to use ban-ip ?

**Comment by dktapps** [comment] 2017-03-09 10:42
Don't have them connect on the same network as you. For a production server that would never happen regardless.
