### ISSUE TITLE
Crashing, too many open files

### ISSUE THREAD

**Issue by isoz** [pmmp/PocketMine-MP#2454] opened 2018-09-20 21:20 UTC
Recently my servers been crashing a lot.

Errors appear on console and server crashes.

* PocketMine-MP: 3.2.3
* Ubuntu 14.04

```
Fatal error: Uncaught ErrorException: include(/home/source/pmmp/vendor/pocketmine/spl/LogLevel.php): failed to open stream: Too many open files in /home/source/pmmp/vendor/composer/ClassLoader.php:444
Stack trace:
#0 /home/source/pmmp/vendor/composer/ClassLoader.php(444): pocketmine\utils\Utils::errorExceptionHandler(2, 'include(/home/s...', '/home/source/pm...', 444, Array)
#1 /home/source/pmmp/vendor/composer/ClassLoader.php(444): include()
#2 /home/source/pmmp/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/home/source/pm...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('LogLevel')
#4 /home/source/pmmp/src/pocketmine/utils/MainLogger.php(200): spl_autoload_call('LogLevel')
#5 /home/source/pmmp/src/pocketmine/scheduler/AsyncWorker.php(74): pocketmine\utils\MainLogger->logException(Object(ErrorException))
#6 /home/source/pmmp/src/pocketmine/scheduler/AsyncTask.php(75): pocketmine\scheduler\AsyncWorker->handleException(Object(ErrorException))
#7 [internal function]: pocketmine\sc in /home/source/pmmp/vendor/composer/ClassLoader.php on line 444
```

**Comment by rdstonech** [comment] 2018-09-21 06:37
(From [stackoverflow](https://stackoverflow.com/questions/14748499/fatal-error-too-many-open-files))

This can be a limitation on the server where the code is running. Every operating system only allows for a certain number of open files/handles/sockets. This limit is usually further reduced when the server is virtualized. On a Linux server you can check the current limit with ulimit -n, if you have root access you can increase it with the same command. I assume there is a method for Windows server as well. Otherwise there is not much you can do about it (except ask your hoster or administrator to increase it).

**Comment by dktapps** [comment] 2018-09-21 07:06
increasing fd limits to solve an issue like this is as pointless as increasing memory limits to fix a memory leak... we need to know what file descriptors are leaking first.

**Comment by isoz** [comment] 2018-09-21 07:17
No limitations on my dedicated server, infact I'm running less pmmp instances at the same time than I was a few months ago.

**Comment by geNAZt** [comment] 2018-09-21 07:17
It may not really be a leak. How many services run on that server? How many FDs do they use? Can you post your `ulimit -S`, `ulimit -N` and `ulimit -n` aswell `lsof | wc -l` without PMMP running?

**Comment by isoz** [comment] 2018-09-21 07:19
`root@ns3024155:/# ulimit -S
unlimited
root@ns3024155:/# ulimit -N
bash: ulimit: -N: invalid option
ulimit: usage: ulimit [-SHabcdefilmnpqrstuvxT] [limit]
root@ns3024155:/# ulimit -n
1024
`

Cannot really stop the services now for lsof.

**Comment by geNAZt** [comment] 2018-09-21 07:29
That doesn't look that bad, does it take some time to crash due to no fds left over?

**Comment by isoz** [comment] 2018-09-21 07:30
Yes. It takes some time. Sometimes it doesn't crash at all. I can't put any logic to it, it's not when there's more players than usual, it's just random.

**Comment by dktapps** [comment] 2018-09-21 08:06
Please load this plugin on your server and wait for it to crash with the error. When it does, you'll get a nice big red error message with lists of open files. https://github.com/dktapps/OpenFilesLeakDebugger

**Comment by dktapps** [comment] 2018-09-21 08:11
for the record, `-N` and `-S` mean hard and soft limit respectively... you should be looking using `ulimit -Hn`, `ulimit -Sn` or just `ulimit -n`.

**Comment by isoz** [comment] 2018-09-25 11:09
@dktapps 
`[13:08:55] [Server thread/INFO]: Enabling OpenFilesLeakDebugger v0.0.1
[13:08:55] [Server thread/CRITICAL]: ErrorException: "fopen(/home/nova/plugins/OpenFilesLeakDebugger/dudFiles/randomFile18.txt): failed to open stream: Too many open files" (EXCEPTION) in "OpenFilesLeakDebugger/src/dktapps/OpenFilesLeakDebugger/Main" at line 21
[13:08:55] [Server thread/DEBUG]: #0 (): pocketmine\utils\Utils::errorExceptionHandler(integer 2, string fopen(/home/nova/plugins/OpenFilesLeakDebugger/dudFiles/randomFile18.txt): failed to open stream: Too many open files, string /home/nova/plugins/OpenFilesLeakDebugger/src/dktapps/OpenFilesLeakDebugger/Main.php, integer 21, array Array())
[13:08:55] [Server thread/DEBUG]: #1 OpenFilesLeakDebugger/src/dktapps/OpenFilesLeakDebugger/Main(21): fopen(string /home/nova/plugins/OpenFilesLeakDebugger/dudFiles/randomFile18.txt, string wb)
[13:08:55] [Server thread/DEBUG]: #2 src/pocketmine/plugin/PluginBase(102): dktapps\OpenFilesLeakDebugger\Main->onEnable()
[13:08:55] [Server thread/DEBUG]: #3 src/pocketmine/plugin/PluginManager(509): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
[13:08:55] [Server thread/DEBUG]: #4 src/pocketmine/Server(1918): pocketmine\plugin\PluginManager->enablePlugin(dktapps\OpenFilesLeakDebugger\Main object)
[13:08:55] [Server thread/DEBUG]: #5 src/pocketmine/Server(1904): pocketmine\Server->enablePlugin(dktapps\OpenFilesLeakDebugger\Main object)
[13:08:55] [Server thread/DEBUG]: #6 src/pocketmine/Server(1698): pocketmine\Server->enablePlugins(integer 1)
[13:08:55] [Server thread/DEBUG]: #7 src/pocketmine/PocketMine(243): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/nova/, string /home/nova/plugins/)`

**Comment by dktapps** [comment] 2018-09-25 11:11
wat

**Comment by dktapps** [comment] 2018-09-25 11:15
grab an updated  version and try again ... looks like a plugin loading before my plugin would perhaps cause this.

**Comment by isoz** [comment] 2018-09-25 11:17
That worked. Now just need to wait for it to crash I guess.

**Comment by isoz** [comment] 2018-09-27 15:03
Here's what I got from the logs https://pastebin.com/WXYcsDAR

**Comment by dktapps** [comment] 2018-09-27 15:07
Looks like a PHP temporary file leak. Perhaps a plugin is using `getResource()` and not cleaning up after itself.

This does not look like something caused by the core, so I'm going to close this (although I note that OpenFilesLeakDebugger needs a bugfix of its own for server reloading).

**Closed by dktapps** 2018-09-27 15:07 UTC
Labels: Category: Core, Status: Unconfirmed
