### ISSUE TITLE
Issue On Fall damage death cancel

### ISSUE THREAD

**Issue by Kjenium** [pmmp/PocketMine-MP#3522] opened 2020-05-22 14:37 UTC
### Issue description

- Expected result: What were you expecting to happen?
I would expect to be teleported to the spawn of the default world
- Actual result: What actually happened?
I got teleported to the right world but not to the correct coordinates

### Steps to reproduce the issue
1.  Cancel fall damage death's last damage
2. Teleport the player in another world different from the one the action has occured in.

### OS and versions

* PocketMine-MP:
* PHP: 7.x.x
* Server OS:
I've tested on ubuntu and in a web platform so idk

### Plugins

- If you remove all plugins, does the issue still occur?
yes

**Comment by dktapps** [comment] 2020-05-22 14:50
If this is an issue with the API, I need simple reproducing code to investigate.

**Comment by Kjenium** [comment] 2020-05-24 11:01
<?php
/**
 * @name NoDie
 * @main test\TpTest
 * @version 1.0.0
 * @api 3.0.0
 * @author Kjenium
 */
namespace test;
use pocketmine\plugin\PluginBase;
use pocketmine\event\Listener;
use pocketmine\event\entity\EntityDamageEvent;
use pocketmine\Player;
class TpTest extends PluginBase implements Listener
{
    public function onEnable()
    {
        $this->getLogger()->info("NoDieTest");
        $this->getServer()->getPluginManager()->registerEvents($this,$this);
    }
    public function onDisable()
    {
        $this->getLogger()->info("NoDieTest Failed");
        $this->getServer()->getPluginManager()->registerEvents($this, $this);
    }
    public function onDamage(EntityDamageEvent $event)
    {
        if($event->getEntity() instanceof Player)
        {
            if($event->getFinalDamage() >= $event->getEntity()->getHealth())
            {
                $event->setCancelled();
                $event->getEntity()->teleport($this->getServer()->getDefaultLevel()->getSpawnLocation());
            }
        }
    }
}

**Comment by Kjenium** [comment] 2020-05-24 11:01
https://pastebin.com/nScwq399

**Comment by dktapps** [comment] 2020-05-24 12:46
Thanks for the code. It seems that this is a pretty-much-dupe of #2616, so I'm going to close this.

**Closed by dktapps** 2020-05-24 12:46 UTC
