### ISSUE TITLE
Can't use /enchant with id >= 3

### ISSUE THREAD

**Issue by TanToan99** [pmmp/PocketMine-MP#354] opened 2017-02-14 01:51 UTC
### Issue description
Cant set effect or enchant for player with enchant id >=3 nd effect id = 6 and 7
Pmmp need update enchant and effect system
* PocketMine-MP: 01a07a0
* PHP: 7.0.4
* Server OS: linux
* Game version: Win10 and mcpe 1.0.3

### Crashdump, backtrace or other files
Nothig
* ...

**Comment by dktapps** [comment] 2017-02-14 10:35
Closing due to not reproducible. Check your plugins.

**Comment by dktapps** [comment] 2017-02-14 10:41
My bad, /enchant command issue. I misread the issue. No such issue occurs with effects though.

**Comment by TanToan99** [comment] 2017-02-14 14:44
Command /effect same issues

**Comment by TanToan99** [comment] 2017-02-14 14:56
I can not set effect with effrct id >= 6

**Comment by IrishPacks** [comment] 2017-02-17 05:33
It's because all enchants aren't registered on PMMP.

**Comment by dktapps** [comment] 2017-02-17 09:14
* _not all enchantments are_ registered (just to be less confusing ;))

**Comment by IrishPacks** [comment] 2017-02-18 00:50
Yeah I forgot to add "not" in front of it, don't know what I was thinking.

**Comment by TheDeibo** [comment] 2017-02-18 01:45
Make sure you are using the the item IDs for their purpose.
`const TYPE_ARMOR_EXPLOSION_PROTECTION = 3;`  -- Protection from explosions when wearing the enchanted armor.
`const TYPE_WATER_BREATHING = 6;` -- Breath under water
`const TYPE_WATER_SPEED = 7;`  -- Travel under water with speed

For ~all~ most PocketMine friendly enchantments, see here https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/item/enchantment/Enchantment.php#L29

**Comment by IrishPacks** [comment] 2017-02-18 20:21
But only 3 are implemented, check the implementation below. https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/item/enchantment/Enchantment.php#L87

**Comment by dktapps** [comment] 2017-02-18 20:22
correct... hence the "not implemented" label.

**Comment by IrishPacks** [comment] 2017-02-18 20:23
Talking to @TheDeibo 😆

**Comment by thebigsmileXD** [comment] 2017-05-03 07:49
So that we dont forget this:

https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/item/enchantment/Enchantment.php#L103 here
GitHub
pmmp/PocketMine-MP
PocketMine-MP - A server software for Minecraft Pocket Edition in PHP
 

[10:43] 
I think that should return null

Xenial
[10:43 AM] 
yea



Xenial
[10:43 AM] 
it should not succeed with the enchant

Dylan K. Taylor
[10:43 AM] 
agreed

**Comment by dktapps** [comment] 2017-07-04 09:56
Closing this in favour of #414 and #1012

**Closed by dktapps** 2017-07-04 09:56 UTC
Labels: Category: Gameplay, Status: Not Implemented, Status: Work in Progress
