### ISSUE TITLE
EntityMoveEvent

### ISSUE THREAD

**Issue by J1b1x** [pmmp/PocketMine-MP#6120] opened 2023-10-27 00:57 UTC
I'd like an EntityMoveEvent, since there's no good way of checking if/how an entity moved other than using a repeating task.

Tbh, i'm pretty sure it's NOT a good idea to add it, since it's probably really inefficient and causes performance issues, but idk any other or better way than this.

**Comment by jasonw4331** [comment] 2023-10-27 02:27
Duplicate of #5799

**Closed as not planned by jasonw4331** 2023-10-27 02:27 UTC
Labels: Category: API, Resolution: Declined

**Comment by JavierLeon9966** [comment] 2023-10-27 04:48
How is this a duplicate? EntityMoveEvent can be used to log entity positions every time they move and then reproduce them in a replay plugin instead of checking every tick. This is very different from waiting for a block collision.

**Comment by dktapps** [comment] 2023-10-27 07:12
This actually used to exist years ago, but Shoghi removed it due to large performance impact. Probably not a good idea to bring it back.
