### ISSUE TITLE
Error when water or lava falling to gap (y < 0)

### ISSUE THREAD

**Issue by EmreTr1** [pmmp/PocketMine-MP#2513] opened 2018-11-03 17:15 UTC
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue

1. place a water in a void world
2. wait it and server will crash

### OS and versions

* PocketMine-MP: Latest
* PHP: Latest
* Server OS: Windows 10
* Game version: Win10

### Plugins
- no plugin

### Crashdump, backtrace or other files

`InvalidArgumentException: "Pos x=360,y=-1,z=-328 is outside of the world bounds" (EXCEPTION) in "src/pocketmine/level/Level" at line 1575`

**Comment by dktapps** [comment] 2018-11-03 17:16
Duplicate of #2510 

oh, I may add there's no such version as "latest", didn't you read the template?

**Closed by dktapps** 2018-11-03 17:16 UTC
