### ISSUE TITLE
Can't set blocks to air

### ISSUE THREAD

**Issue by PotatoeTrainYT** [pmmp/PocketMine-MP#2375] opened 2018-08-15 09:20 UTC
### Issue description

When you try setting a block to air via a plugin, it doesn't work. Even when you do TNT->ignite(), it still doesnt set tnt to air

- Expected result: TNT->ignite() would set the TNT block to air, then spawn PrimedTNT entity
- Actual result: TNT block stayed, and spawned PrimedTNT entity

### Steps to reproduce the issue

1. Use TNT->ignite() or try settings a block to air via a plugin

### OS and versions

* PocketMine-MP: 3.0.7+dev
* PHP: 7.2
* Server OS: Ubuntu 14
* Game version: Win10

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
I mean, idk? because as far as i know, it only happens when you do it via a plugin lol

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here

* ...

**Comment by dktapps** [comment] 2018-08-15 09:29
That version is obsolete. Please use up to date versions to test.

**Comment by dktapps** [comment] 2018-08-15 09:45
Closing due to not reproducible. Please do not use the issue tracker for plugin support requests.

**Closed by dktapps** 2018-08-15 09:45 UTC
