### ISSUE TITLE
Unexpected Freezes

### ISSUE THREAD

**Issue by 6kek6** [pmmp/PocketMine-MP#6361] opened 2024-06-15 08:09 UTC
### Issue description
 https://github.com/pmmp/PocketMine-MP/issues/2618 
 Same problems again.

### OS and versions
* PocketMine-MP: 5.16.1
* PHP: 8.2.17
* Using JIT: no
* Server OS: Ubuntu 20.04
* Game version: all

### Plugins
 Without plugins

### Crashdump, backtrace or other files
 Similarly #2618

**Comment by dries-c** [comment] 2024-06-19 23:14
Would it be possible to send us timings of this happening?

**Comment by IvanCraft623** [comment] 2024-06-20 00:34
To provide timings you need to follow these steps:
1. Run `/timings on` command
2. Try to replicate the freeze or wait for it to happen, the report should be at least 25 minutes with players on the server.
3. Run `/timings paste` command
4. Send us the generated URL

**Comment by 6kek6** [comment] 2024-06-20 04:06
The timing is completely random. It could happen in an hour, it could happen in a few days.

Regarding timings, do you generally understand the essence of the problem? The server completely freezes at a random moment and NOTHING CAN BE RECEIVED (Only if you take some data directly from PHP).

This is such an interesting problem, very...

**Comment by Gewinum** [comment] 2024-06-20 09:11
@6kek6 have you ever had any beef with players

**Comment by Gewinum** [comment] 2024-07-02 17:24
@IvanCraft623 i might know reasons of freeze, can you please contact me? can't talk about this in public. my dc @gewinum

**Comment by 6kek6** [comment] 2024-07-02 18:52
Currently trying to get more logs and information.

**Comment by Gewinum** [comment] 2024-07-02 19:00
> Currently trying to get more logs and information.

please contact me in discord @gewinum

**Comment by s1111111111c** [comment] 2024-07-05 13:39
Garbage Collection

**Comment by IvanCraft623** [comment] 2024-07-27 21:07
Closing due to lack of basic reproduction steps

**Closed as completed** 2024-08-15 11:16 UTC
Labels: Resolution: Invalid, Category: Core
