### ISSUE TITLE
Crash when unloading player level during PlayerQuitEvent

### ISSUE THREAD

**Issue by legoboy0215** [pmmp/PocketMine-MP#284] opened 2017-01-22 08:41 UTC
### Issue description

The getBlah on null in Level.php issue is back again!

### Steps to reproduce the issue

1. Unload a level.

### OS and versions
* PocketMine-MP: This server is running PocketMine-MP 1.6.2dev 「Unleashed」 implementing API version 3.0.0-ALPHA2 for Minecraft: PE v1.0.0.16 (protocol version 100)
* PHP: 7.0.4
* Server OS: Ubuntu 16.10
* Game version: PE/Win10 (delete as appropriate)

### Crashdump, backtrace or other files

http://pastebin.com/rsH9Sb4b

**Comment by dktapps** [comment] 2017-01-22 08:56
This is unsurprising, happening since 6fbb9b6083e80f835ce042e658797d3326c189d6. This was a patch to prevent Level objects from leaking, but they are used unsafely everywhere. The first issue that came to light was a double chest memory leak.

Did you see anything in your server log about `Position was holding a reference to an unloaded Level` before the crash occurred?

**Comment by legoboy0215** [comment] 2017-01-22 08:58
No.

**Comment by legoboy0215** [comment] 2017-01-22 09:00
```
2017-01-22 [03:52:17] [Server thread/CRITICAL]: Unhandled exception executing command 'kick l' in kick: Call to a member function getSpawn() on null
2017-01-22 [03:52:17] [Server thread/CRITICAL]: Error: "Call to a member function getSpawn() on null" (EXCEPTION) in "/src/pocketmine/level/Level" at line 2543
2017-01-22 [03:52:17] [Server thread/CRITICAL]: Error: "Call to a member function getWorldHeight() on null" (EXCEPTION) in "/src/pocketmine/level/Level" at line 1245
2017-01-22 [03:52:17] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
2017-01-22 [03:52:17] [Server thread/EMERGENCY]: Please upload the "/root/pm-1.0/crashdumps/Sun_Jan_22-03.52.17-EST_2017.log" file to the Crash Archive and submit the link 
```
Another one. I did /kick Lego and this happened?!

**Comment by dktapps** [comment] 2017-01-22 09:01
Wtf... you are in a world which has a null LevelProvider?

**Comment by dktapps** [comment] 2017-01-22 09:03
That should be impossible. I don't understand.

**Comment by legoboy0215** [comment] 2017-01-22 09:04
I have no idea. I basically ran out of battery and my client was still on a world. But when I kicked it, it triggered PlayerQuitEvent in my plugin, which in turn closes the level (unloadLevel) because... Well, it is a SkyWars plugin.

**Comment by dktapps** [comment] 2017-01-22 09:05
Ahhh. That's probably a bad idea.

**Comment by legoboy0215** [comment] 2017-01-22 09:06
http://pastebin.com/FbfawVaL

Here is part of the log.

**Comment by dktapps** [comment] 2017-01-22 09:07
Could you try to reproduce it with debugging enabled?

**Comment by legoboy0215** [comment] 2017-01-22 09:10
I'll try.

**Comment by dktapps** [comment] 2017-01-22 10:01
```
<?php

/**
 * @name UnloadOnQuit
 * @main dktapps\unload\Main
 * @api 3.0.0-ALPHA2
 * @version 1.0.0
 * @description Unloads levels on player quit
 * @author dktapps
 */

namespace dktapps\unload{
	class Main extends \pocketmine\plugin\PluginBase implements \pocketmine\event\Listener{
		public function onEnable(){
			$this->getServer()->getPluginManager()->registerEvents($this, $this);
		}

		public function onQuit(\pocketmine\event\player\PlayerQuitEvent $e){
			$this->getServer()->unloadLevel($e->getPlayer()->getLevel());
		}
	}
}
```

With backtrace:
```
[09:58:12] [Server thread/CRITICAL]: Unhandled exception executing command 'kick p' in kick: Call to a member function getSpawn() on null
[09:58:12] [Server thread/CRITICAL]: Error: "Call to a member function getSpawn() on null" (EXCEPTION) in "C:/Users/User/Downloads/server/src/pocketmine/level/Level" at line 2543
[09:58:12] [Server thread/DEBUG]: #0 C:/Users/User/Downloads/server/src/pocketmine/level/Level(598): pocketmine\level\Level->unloadChunkRequest(integer 16, integer 16, boolean 1)
[09:58:12] [Server thread/DEBUG]: #1 C:/Users/User/Downloads/server/src/pocketmine/Player(3120): pocketmine\level\Level->unregisterChunkLoader(pocketmine\Player Player(1), integer 16, integer 16)
[09:58:12] [Server thread/DEBUG]: #2 C:/Users/User/Downloads/server/src/pocketmine/Player(3004): pocketmine\Player->close(pocketmine\event\TranslationContainer ..e%multiplayer.player.left, string Kicked by admin.)
[09:58:12] [Server thread/DEBUG]: #3 C:/Users/User/Downloads/server/src/pocketmine/command/defaults/KickCommand(56): pocketmine\Player->kick(string )
[09:58:12] [Server thread/DEBUG]: #4 C:/Users/User/Downloads/server/src/pocketmine/command/SimpleCommandMap(194): pocketmine\command\defaults\KickCommand->execute(pocketmine\command\ConsoleCommandSender object, string kick, array Array())
[09:58:12] [Server thread/DEBUG]: #5 C:/Users/User/Downloads/server/src/pocketmine/Server(1813): pocketmine\command\SimpleCommandMap->dispatch(pocketmine\command\ConsoleCommandSender object, string kick p)
[09:58:12] [Server thread/DEBUG]: #6 C:/Users/User/Downloads/server/src/pocketmine/Server(1798): pocketmine\Server->dispatchCommand(pocketmine\command\ConsoleCommandSender object, string kick p)
[09:58:12] [Server thread/DEBUG]: #7 C:/Users/User/Downloads/server/src/pocketmine/Server(2331): pocketmine\Server->checkConsole(boolean)
[09:58:12] [Server thread/DEBUG]: #8 C:/Users/User/Downloads/server/src/pocketmine/Server(2087): pocketmine\Server->tick(boolean)
[09:58:12] [Server thread/DEBUG]: #9 C:/Users/User/Downloads/server/src/pocketmine/Server(1969): pocketmine\Server->tickProcessor(boolean)
[09:58:12] [Server thread/DEBUG]: #10 C:/Users/User/Downloads/server/src/pocketmine/Server(1590): pocketmine\Server->start(boolean)
[09:58:12] [Server thread/DEBUG]: #11 C:/Users/User/Downloads/server/src/pocketmine/PocketMine(492): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string C:\Users\User\downloads\server\, string C:\Users\User\downloads\server\, string C:\Users\User\downloads\server\plugins\)
```

With that crash in mind, I would say it is extremely inadvisable to try to do what you are doing from the quit handler, because there are various actions that need to take place before the level is unloaded after the event is called.

In the future I plan to add support for ondemand level loading an unloading, so you (hopefully) won't need to do this.

**Comment by legoboy0215** [comment] 2017-01-22 10:28
Oh. What should I do right now? It seems like what I am doing is kind of like bad practice.

**Comment by dktapps** [comment] 2017-01-22 10:29
Right now? Wait on a bugfix, since I'm pretty sure there are other ways this crash can occur.

**Comment by jasonwynn10** [comment] 2017-01-22 14:24
@legoboy0215 couldn't you just close the level in a delayed task so that the server could do what it needs before closing?

**Comment by legoboy0215** [comment] 2017-01-22 23:45
I used to do that. But what is the point? The bug is still there.

**Comment by dktapps** [comment] 2017-01-23 08:14
@legoboy0215 it's a hack for a critical issue in case you need it.

**Comment by Creeperface01** [comment] 2017-01-24 09:35
It happens if player spawnpoint is in upload level doesnt it?

**Comment by dktapps** [comment] 2017-01-24 09:36
@Creeperface01 that particular case was already fixed, see #24 . This is a different issue due to timing of PlayerQuitEvent and attempted chunk unloads.

**Comment by dktapps** [comment] 2017-04-26 16:53
Should be fixed as of 69ac80518c1ef7a7794f3f1c5b24a8d5f42a3151

**Closed by dktapps** 2017-04-26 16:53 UTC
Labels: Category: Core, Status: Debugged, Status: Reopened

**Comment by legoboy0215** [comment] 2017-04-29 03:48
I'll try and test it.

**Comment by zKoz210** [comment] 2017-11-14 14:28
It seems to me that in this case it is logical to use the task with a delay of 1 tick and use getLevelName().
