### ISSUE TITLE
Crashing when in a inventory then teleport to another world.

### ISSUE THREAD

**Issue by xMercyTheDeveloper** [pmmp/PocketMine-MP#3911] opened 2020-11-15 08:37 UTC
Today I wanted to make a trade system with inventories.

I made, but when you are in a inventory and then you get teleported to another world you crash.

(My english is bad)
![Screenshot_1](https://user-images.githubusercontent.com/42582303/99180384-7af83d80-272e-11eb-9fc2-5f5f6d4f81a8.png)

**Comment by TwistedAsylumMC** [comment] 2020-11-15 08:49
This is an issue with the client, and is not going to be fixed until the 1.16.100 update. It's not a fault in pocketmine, so for now you can just use [InvCrashFix by Muqsit](github.com/Muqsit/InvCrashFix)

**Comment by xMercyTheDeveloper** [comment] 2020-11-15 09:01
i used that too but same thing

**Comment by xMercyTheDeveloper** [comment] 2020-11-16 07:33
nvm it works

**Comment by dktapps** [comment] 2020-11-16 12:08
duplicate of #3651

**Closed by dktapps** 2020-11-16 12:08 UTC
