### ISSUE TITLE
Client crashes when using Player::removeWindow() in PocketMine 3.14.0

### ISSUE THREAD

**Issue by 95CivicSi** [pmmp/PocketMine-MP#3651] opened 2020-06-28 14:37 UTC
### Issue description
When using `Player::removeWindow()`, the player will see the inventory window disappear and the the client will crash.

### Steps to reproduce the issue
1. Have 2 players connect to a server running on PocketMine 3.14.0 with no plugins
2. Have a player open a chest.
3. Have the other player break the chest that the first player is viewing inventory of.
4. Client of the player viewing chest inventory will crash.

### OS and versions

* PocketMine-MP: 3.14.0
* PHP: 7.3.19
* Server OS: Win10/Linux
* Game version: PE/Win10 (delete as appropriate)

### Plugins

- If you remove all plugins, does the issue still occur? Yes

**Comment by dktapps** [comment] 2020-06-28 14:51
I changed nothing regarding inventories in 1.16. Please check if this happens on BDS, because I'm pretty sure this is a client bug.

**Comment by alvin0319** [comment] 2020-06-28 15:12
It works fine in BDS. I tested if the client crashes when I opened the chest from high up and fell to the floor, the client crashed in PM, but BDS didn't.

**Comment by dktapps** [comment] 2020-06-28 15:15
That's not the same thing. This is about player1 viewing a chest while player2 destroys it.

**Comment by alvin0319** [comment] 2020-06-28 15:21
I'm sorry. I explained it wrong. There was no problem with BDS, but there was a problem with PM. And I tested double chest, but the same client issue did not appear.

**Comment by 95CivicSi** [comment] 2020-06-28 15:36
I don't have this problem on my BDS server.  The steps in the OP are mostly to trigger `Player::removeWindow()`
I would imagine that if you are able to trigger it from other methods, that it would cause the same type of crash.

**Comment by 95CivicSi** [comment] 2020-06-28 15:52
This problem can also be repeated using a Furnace instead of a chest.  It might be important to note that this doesn't happen if you use a crafting table.

**Comment by hyunseo777** [comment] 2020-06-28 15:56
When I use ContainerClosePacket, this problem occurs in my PM server either.

**Comment by dktapps** [comment] 2020-06-28 16:03
If a plain ContainerClose can reproduce this problem, then either there's something wrong with ContainerClose, or this is a client bug that I can't help you with.

**Comment by ahnsunggwan45** [comment] 2020-06-28 23:34
https://github.com/ZulfahmiFjr/SoulWell/blob/master/src/InvMenu/muqsit/invmenu

**Comment by Encritary** [comment] 2020-06-29 07:41
I close my fake inventory by removing a fake entity that was assigned to it. I don't send ContainerClose until I receive it from the client. Otherwise, the game crashes.

**Comment by zhangbeic** [comment] 2020-10-22 12:04
I want to use the item click event to call a box window, can you provide the next algorithm, thank you.

**Comment by DimBis** [comment] 2020-10-22 13:16
> I want to use the item click event to call a box window, can you provide the next algorithm, thank you.

yes.

**Comment by dktapps** [comment] 2021-11-08 22:31
The crash was long since fixed by Mojang.

The issue with UIs not being openable after the fix is fixed by 4bf338f783c729ed6143d0c33739407debb629b4.

**Closed by dktapps** 2021-11-08 22:31 UTC
Labels: Category: Gameplay, Category: Client, Status: Unconfirmed
