### ISSUE TITLE
[BUG]: pocketmine translate error, appear {number%} in the vanilla messages

### ISSUE THREAD

**Issue by FabriSoftware** [pmmp/PocketMine-MP#4579] opened 2021-11-17 21:40 UTC
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue
1. execute any commands

### OS and versions

* PocketMine-MP: 3.25.4
* PHP: 8.0
* Using JIT: no 
* Server OS: Ubuntu 20.04.3 LTS
* Game version:1.17.41

### Plugins

- If you remove all plugins, does the issue still occur?: yes
  - Have you asked for help on our forums before creating an issue?: no
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section:
  when i execute the say command the command returns
  [{0%}] {1%} and this happens to me with all pocketmine commands

### Crashdump, backtrace or other files
None

### More explication
I have this problem since I update the php binary of the server and also PocketMine-MP.phar
I also want to note that this does not happen on the console

**Comment by dktapps** [comment] 2021-11-17 22:10
Which language are you using?

**Comment by FabriSoftware** [comment] 2021-11-17 23:05
I use the default language "English"

in server.properties
```yml
language=eng
```

**Comment by dktapps** [comment] 2021-11-17 23:24
I can't reproduce this using a fresh install.

**Comment by FabriSoftware** [comment] 2021-11-18 19:00
I will try to install a new php binary and say if it solved

**Comment by dktapps** [comment] 2021-11-19 14:46
Closing due to unable to reproduce.

**Closed by dktapps** 2021-11-19 14:46 UTC
