### ISSUE TITLE
Console not responding

### ISSUE THREAD

**Issue by EnteMomo** [pmmp/PocketMine-MP#2246] opened 2018-06-16 17:20 UTC
When i type anything in the console of the Server it doesnt answer. So it Looks like its freezed but when i join onto the Server i can do everything and it doesnt lag or smth like this and it also dont crashed. I also receive every logs/Infos in the console.

- Its very annoying bc i have to go ingame to type any command, so Maybe you have an idea to fix it bc in the earlier it worked perfectly.

### OS and versions
* PocketMine-MP: Build #1188 
* PHP: 7.2
* Server OS: Debian 9
* Game version: Both

![screenshot_72](https://user-images.githubusercontent.com/20842552/41500869-43d0d9d0-719a-11e8-9381-7c4ed0def844.png)

**Comment by dktapps** [comment] 2018-06-16 17:36
I need reproducing steps to investigate this.

**Comment by TheAz928** [comment] 2018-06-16 17:49
It's your shh client bug, happened to me before, reset my client and all done. To confirm this, try reset your putty or whatever ssh client you have and try the same and see if it reproduces or not, If it doesn't reproduces then it's NOT pmmp bug

**Comment by TheAz928** [comment] 2018-06-16 17:50
Also, some vps/vds sshd or shh has wrong configurations which causes this

**Comment by dktapps** [comment] 2018-06-16 17:51
@TheAz928 I wouldn't jump to that conclusion so fast, this could be a bug in Snooze.

If you do try resetting your SSH client, please do so **without** restarting the server. If it persists after a reconnect then it's likely a Snooze bug.

**Comment by EnteMomo** [comment] 2018-06-16 19:16
Nah, in the earlier versions of pmmp it worked also. And also now it works with the older versions. But i want to use the newer versions.

**Comment by dktapps** [comment] 2018-06-17 11:56
> I need reproducing steps to investigate this.

**Comment by dktapps** [comment] 2018-06-19 20:09
is this issue anything like #2251 ?

**Comment by FienixEC** [comment] 2018-06-27 22:21
having same issue, when loading latest version with or without plugins, console commands not responsive and plugins wont load due to incompatible API, reproduce by loading latest version, restart, @dktapps if u want u can email me fienixjp@gmail.com and i can grant u access to my cpanel to see for urself and help solve this issue, thanks!

**Comment by lukeeey** [comment] 2018-06-28 07:10
This happens to me when using nukkit but tbh i think that could just be as issue specific to that

**Comment by LagHD** [comment] 2018-07-04 22:18
All I can confirm is, these recent commits causing the typing in ssh client to lag and yeah sometimes it becomes unresponsive and I have to disconnect from ssh and reconnect

**Comment by FienixEC** [comment] 2018-07-10 21:04
Any new info on why this occurs? with 1.5 update im being forced to update my PMMP, and still having issue same, absolutely no response from console, but server runs fine

**Comment by lukeeey** [comment] 2018-07-11 20:31
Clear the server log and launch the server again, see what it says

**Comment by lukeeey** [comment] 2018-07-11 20:32
Oh wait is it just not allowing you to enter commands?

**Comment by lukeeey** [comment] 2018-07-11 20:32
Oh wait is it just not allowing you to enter commands?

**Comment by FienixEC** [comment] 2018-07-11 21:03
UPDATE: a friend of mine fixed the issue for me, the problem was an outdated PHP i was using prior to an early June PHP update.

Fix: PHP binary needs to be updated due to that june update

**Comment by dktapps** [comment] 2018-07-11 21:12
I did ask if that was the fault, but apparently nobody was paying attention...

https://github.com/pmmp/PocketMine-MP/issues/2246#issuecomment-398528810

**Comment by dktapps** [comment] 2018-07-11 21:13
Duplicate of #2251

**Closed by dktapps** 2018-07-11 21:12 UTC
Labels: Category: Core, Status: Awaiting Response, Status: Unconfirmed
