### ISSUE TITLE
Interact with a slab on any slab of the same type at any face creates double slab

### ISSUE THREAD

**Issue by thebigsmileXD** [pmmp/PocketMine-MP#1314] opened 2017-08-24 16:33 UTC
### Issue description

Reminding issue - As already discussed/mentioned in private
Expected result: Tapping the "side" that is not filled creates a double slab, otherwise it places it
Actual result: at any face it creates a double slab

### Steps to reproduce the issue

1. Place a slab (example: stone slab)
2. Try placing another slab onto it at any face

### OS and versions

* PocketMine-MP: As of commit 238b3ca4c1d10bb2f8010b070425482c6780ed9d, same on api3/blocks & mcpe1.2
* PHP: 7.0.1

### Plugins
-  [x] Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
-  [x] Have you asked for help on our forums before creating an issue?
-  [ ] Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
-  [ ] Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here 

* ...

**Comment by zKoz210** [comment] 2017-08-24 17:55
I have same thing

**Comment by thebigsmileXD** [comment] 2017-08-24 19:44
Instead of adding a comment, you could simply use the desktop view of github to add a  ❤️  or 👍 to show your agreement

**Comment by AppleDevelops** [comment] 2017-08-24 22:51
Oh wow @thebigsmileXD the button works!

**Comment by mal0ne-23** [comment] 2017-08-24 22:55
i don't mean to pollute the comments, but the :-1: button works for me aswell.

**Comment by dktapps** [comment] 2017-08-25 19:52
This bug was caused by https://github.com/pmmp/PocketMine-MP/commit/f2ff0198cca01db0e93a9b45d428e624822f18e9. Not sure I want to swap one bug for another, and not sure how best to fix this issue at the moment.

**Comment by dktapps** [comment] 2017-09-21 13:44
Fixed in 1b5fed983b545e4151f65af23949a2eaf4c9df98 (reverted bad commit).

**Closed by dktapps** 2017-09-21 13:44 UTC
Labels: Category: Gameplay, Status: Debugged
