### ISSUE TITLE
cant take/place armor on while getting hit

### ISSUE THREAD

**Issue by UnknownOre** [pmmp/PocketMine-MP#4183] opened 2021-04-17 18:25 UTC
### Issue description

- Expected result: being able to remove/add armor normally
- Actual result: sometimes it doesn't let you and stop you from removing/placing armor

### Steps to reproduce the issue
1. get someone to hit you really really fast
2. try removing/armor while getting hit
3. voila

### OS and versions

* PocketMine-MP: 3.18.0
* PHP: 7.4
* Server OS: Ubuntu 18.0
* Game version: Win10 (haven't tested in pe)

### Crashdump, backtrace or other files
i believe its caused because of this:
https://github.com/pmmp/PocketMine-MP/blob/6f80b8979dbc8e475f90fc4f8c197b81666620b3/src/pocketmine/entity/Living.php#L516

**Comment by dktapps** [comment] 2021-04-19 15:23
I'm not sure there is a solution to this. This is essentially a transaction race caused by network latency. It will happen in other cases too (for example, trying to move a stack of items when the server just added one item to the stack (pickup) will cause the same rollback effect). It can maybe be reduced by checking which of the armour pieces changed (if any) and then avoiding changing the ones that didn't, but I think this problem is likely to persist regardless.

**Comment by dktapps** [comment] 2021-04-19 15:24
Since armour is almost always going to reduce in durability when you get attacked, I don't think there's any practical way to mitigate this.

**Comment by UnknownOre** [comment] 2021-04-28 16:28
well yeah i noticed that there no way to fix it completely this will keep happening no matter what

**Comment by dktapps** [comment] 2021-05-18 23:29
I'm going to close this since there is no solution; however, I will note that PM4 has improvements to network inventory handling which might reduce the problem, although it won't be eliminated.

**Closed by dktapps** 2021-05-18 23:29 UTC
