### ISSUE TITLE
Activator rail shows when world has missing blocks

### ISSUE THREAD

**Issue by ghost** [pmmp/PocketMine-MP#4805] opened 2022-02-07 03:56 UTC
## Issue Description
When converting worlds on java to pocketmine/mcpe, theres activator rail in each missing blocks. 
### Steps to reproduce the issue
1. Add your java world (pmanvil/mcanvil) 
2. Convert your world
3. Load your world
4. TP to world
5. You will see activator rail each missing blocks

### OS and versions

* PocketMine-MP: 3.26.3
* PHP: 8.0
* Using JIT: yes 
* Server OS: Windows 10 NT
* Game version: Windows 10 & Android

### Plugins

None

- If you remove all plugins, does the issue still occur? yes
- If the issue is **not** reproducible without plugins: no
  - Have you asked for help on our forums before creating an issue? No
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section: i havent code

### Crashdump, backtrace or other files

I dont have crashdump, or backtrace

**Comment by ghost** [comment] 2022-02-07 03:57
Its still has activator rail when converting world and theres missing blocks, this kind a wirddo thing

**Comment by ghost** [comment] 2022-02-07 04:00
I tried to 4.0.0 version, its still not working. Its same. Some reason is slabs position up and down is buggy, its adding rail activator, bruh.

**Comment by dktapps** [comment] 2022-02-07 04:03
Duplicate of #2799

**Closed as completed by dktapps** 2022-02-07 04:03 UTC
Labels: Resolution: Duplicate, Category: Core
