### ISSUE TITLE
Give Error

### ISSUE THREAD

**Issue by ParkChanSol** [pmmp/PocketMine-MP#1107] opened 2017-06-16 22:34 UTC
### Issue description

server is dead with crashdump

### Steps to reproduce the issue

1. Type Command '/give beagle -1 1'

### OS and versions

* PocketMine-MP:846be84
* PHP:7.0.3
* Server OS: Windows 10 x64
* Game version: PE/Win10 (delete as appropriate) PE

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded? yes

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue? no
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section : 
Error: Value 65535 is too large!
File: /src/pocketmine/nbt/tag/ShortTag
Line: 70
Type: notice

Code:
[61] 	/**
[62] 	 * @param int $value
[63] 	 *
[64] 	 * @throws \TypeError
[65] 	 */
[66] 	public function setValue($value){
[67] 		if(!\is_int($value)){
[68] 			throw new \TypeError("ShortTag value must be of type int, " . \gettype($value) . " given");
[69] 		}elseif($value < -(2 ** 15) or $value > ((2 ** 15) - 1)){
[70] 			throw new \InvalidArgumentException("Value $value is too large!");
[71] 		}
[72] 		parent::setValue($value);
[73] 	}
[74] }
[75] 
[76] 
[77] 
[78] 
[79] 
[80]
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP) : DevTools v1.11.3, AllGive v1, RemoteControl v1, TSBox v1.0.1, PluginForceLoader v빌드4

### Crashdump, backtrace or other files

*[Sat_Jun_17-06.01.02-AWST_2017.log.zip](https://github.com/pmmp/PocketMine-MP/files/1082098/Sat_Jun_17-06.01.02-AWST_2017.log.zip)

**Comment by dktapps** [comment] 2017-06-16 23:43
Perfect duplicate of #1101

**Closed by dktapps** 2017-06-16 23:43 UTC
