### ISSUE TITLE
Freezed players... but the other player hears there footsteps

### ISSUE THREAD

**Issue by SpectorV** [pmmp/PocketMine-MP#3309] opened 2020-02-16 20:08 UTC
### Freezing players while the other players hear footsteps from them

- Expected result: need to fix this bug/issue with PMMP software files... possibly be fixed through the files???
- Actual result: players are freezing but they hear walking footsteps on the character

P.S. This is for a server named Dream Life City (Not my server)

**Comment by TwistedAsylumMC** [comment] 2020-02-16 20:54
Duplicate of #3304 & #3308.

**Closed** 2020-02-17 01:08 UTC
