### ISSUE TITLE
Server crashed When i click on item

### ISSUE THREAD

**Issue by mr-zinkil** [pmmp/PocketMine-MP#3927] opened 2020-11-23 17:00 UTC
[16:55:52] [Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine\network\mcpe\NetworkBinaryStream::putString() must be of the type string, null given, called in phar:///home/container/PocketMine-MP.phar/src/pocketmine/network/mcpe/protocol/RemoveObjectivePacket.php on line 41" (EXCEPTION) in "src/pocketmine/network/mcpe/NetworkBinaryStream" at line 66
[16:55:52] [Server thread/CRITICAL]: #0 src/pocketmine/network/mcpe/protocol/RemoveObjectivePacket(41): pocketmine\network\mcpe\NetworkBinaryStream->putString(NULL )
[16:55:52] [Server thread/CRITICAL]: #1 src/pocketmine/network/mcpe/protocol/DataPacket(127): pocketmine\network\mcpe\protocol\RemoveObjectivePacket->encodePayload()
[16:55:52] [Server thread/CRITICAL]: #2 src/pocketmine/network/mcpe/RakLibInterface(244): pocketmine\network\mcpe\protocol\DataPacket->encode()
[16:55:52] [Server thread/CRITICAL]: #3 src/pocketmine/Player(3321): pocketmine\network\mcpe\RakLibInterface->putPacket(object pocketmine\Player, object pocketmine\network\mcpe\protocol\RemoveObjectivePacket, boolean , boolean )
[16:55:52] [Server thread/CRITICAL]: #4 plugins/Scoreboards_v1.0.2.phar/src/Scoreboards/Scoreboards(47): pocketmine\Player->sendDataPacket(object pocketmine\network\mcpe\protocol\RemoveObjectivePacket)
[16:55:52] [Server thread/CRITICAL]: #5 plugins/MlgBlock By MR Zinkil,FOX v7.phar/src/mrzinkil/MlgBlock/SWarena(566): Scoreboards\Scoreboards->remove(object pocketmine\Player)
[16:55:52] [Server thread/CRITICAL]: #6 plugins/MlgBlock By MR Zinkil,FOX v7.phar/src/mrzinkil/MlgBlock/SWcommands(88): mrzinkil\MlgBlock\SWarena->closePlayer(object pocketmine\Player, boolean 1)
[16:55:52] [Server thread/CRITICAL]: #7 src/pocketmine/command/SimpleCommandMap(248): mrzinkil\MlgBlock\SWcommands->execute(object pocketmine\Player, string[2] mb, array[0])
[16:55:52] [Server thread/CRITICAL]: #8 plugins/MlgBlock By MR Zinkil,FOX v7.phar/src/mrzinkil/MlgBlock/SWlistener(117): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\Player, string[7] mb quit)
[16:55:52] [Server thread/CRITICAL]: #9 src/pocketmine/plugin/MethodEventExecutor(42): mrzinkil\MlgBlock\SWlistener->onInteract(object pocketmine\event\player\PlayerInteractEvent)
[16:55:52] [Server thread/CRITICAL]: #10 src/pocketmine/plugin/RegisteredListener(80): pocketmine\plugin\MethodEventExecutor->execute(object mrzinkil\MlgBlock\SWlistener, object pocketmine\event\player\PlayerInteractEvent)
[16:55:52] [Server thread/CRITICAL]: #11 src/pocketmine/event/Event(88): pocketmine\plugin\RegisteredListener->callEvent(object pocketmine\event\player\PlayerInteractEvent)
[16:55:52] [Server thread/CRITICAL]: #12 src/pocketmine/level/Level(1872): pocketmine\event\Event->call()
[16:55:52] [Server thread/CRITICAL]: #13 src/pocketmine/Player(2523): pocketmine\level\Level->useItemOn(object pocketmine\math\Vector3, object pocketmine\item\Bed, integer 2, object pocketmine\math\Vector3, object pocketmine\Player, boolean 1)
[16:55:52] [Server thread/CRITICAL]: #14 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(149): pocketmine\Player->handleInventoryTransaction(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket)
[16:55:52] [Server thread/CRITICAL]: #15 src/pocketmine/network/mcpe/protocol/InventoryTransactionPacket(173): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleInventoryTransaction(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket)
[16:55:52] [Server thread/CRITICAL]: #16 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(109): pocketmine\network\mcpe\protocol\InventoryTransactionPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
[16:55:52] [Server thread/CRITICAL]: #17 src/pocketmine/network/mcpe/protocol/BatchPacket(127): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket)
[16:55:52] [Server thread/CRITICAL]: #18 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(109): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
[16:55:52] [Server thread/CRITICAL]: #19 src/pocketmine/Player(3273): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
[16:55:52] [Server thread/CRITICAL]: #20 src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
[16:55:52] [Server thread/CRITICAL]: #21 vendor/pocketmine/raklib/src/server/ServerHandler(95): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[18] 41.238.27.22 32848, object raklib\protocol\EncapsulatedPacket, integer 0)
[16:55:52] [Server thread/CRITICAL]: #22 src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
[16:55:52] [Server thread/CRITICAL]: #23 src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
[16:55:52] [Server thread/CRITICAL]: #24 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
[16:55:52] [Server thread/CRITICAL]: #25 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
[16:55:52] [Server thread/CRITICAL]: #26 src/pocketmine/Server(2157): pocketmine\snooze\SleeperHandler->sleepUntil(double 1606150552.3818)
[16:55:52] [Server thread/CRITICAL]: #27 src/pocketmine/Server(1994): pocketmine\Server->tickProcessor()
[16:55:52] [Server thread/CRITICAL]: #28 src/pocketmine/Server(1588): pocketmine\Server->start()
[16:55:52] [Server thread/CRITICAL]: #29 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[16] /home/container/, string[24] /home/container/plugins/)
[16:55:52] [Server thread/CRITICAL]: #30 src/pocketmine/PocketMine(304): pocketmine\server()
[16:55:52] [Server thread/CRITICAL]: #31 (11): require(string[71] phar:///home/container/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

**Comment by ZizzyZizzy** [comment] 2020-11-23 17:26
@mr-zinkil I'm not sure if you're lazy, selfish, or just a jerk.

1. Quit wasting developers' precious time. **FILL OUT THE FORM**. You know, the one you ceremoniously deleted when you pasted the crash dump?

2. READ your own crash dump. If it has plugins listed, 99% of the time the issue is going to be with one of those plugins.

3. Go back and READ THE FORM you deleted. There is a section about if you have tested WITHOUT plugins, which you clearly have not here. I can see at least 2 different plugins in the crash dump.

4. Close this now so the developers don't have to waste their time closing it for you and telling you everything I'm telling you now.

**Closed** 2020-11-23 17:33 UTC
Labels: Support request
