### ISSUE TITLE
ChestInventory error

### ISSUE THREAD

**Issue by Frago9876543210** [pmmp/PocketMine-MP#1899] opened 2018-01-10 16:08 UTC
### Steps to reproduce the issue
I do not know how to reproduce this issue.

## OS, commit, PHP version
* PocketMine-MP: a0683dbb0f1f1d4f27ef6d7edcd1bef72bba939d
* PHP: 7.2.1
* Server OS: Linux

### Plugins
I have 17 plugins, but I do not want to make them public.

### Crashdump, backtrace or other files
```
2018-01-10 [18:52:01] [Server thread/CRITICAL]: Error: "Call to a member function addChunkPacket() on null" (EXCEPTION) in "src/pocketmine/inventory/ChestInventory" at line 90
2018-01-10 [18:52:01] [Server thread/DEBUG]: #0 src/pocketmine/inventory/DoubleChestInventory(120): pocketmine\inventory\ChestInventory->broadcastBlockEventPacket(pocketmine\tile\Chest object, boolean )
2018-01-10 [18:52:01] [Server thread/DEBUG]: #1 src/pocketmine/inventory/BaseInventory(399): pocketmine\inventory\DoubleChestInventory->onClose(vc_api\player\CustomPlayer object)
2018-01-10 [18:52:01] [Server thread/DEBUG]: #2 src/pocketmine/Player(3797): pocketmine\inventory\BaseInventory->close(vc_api\player\CustomPlayer object)
2018-01-10 [18:52:01] [Server thread/DEBUG]: #3 src/pocketmine/Player(3811): pocketmine\Player->removeWindow(pocketmine\inventory\DoubleChestInventory object, boolean )
2018-01-10 [18:52:01] [Server thread/DEBUG]: #4 src/pocketmine/Player(3639): pocketmine\Player->removeAllWindows()
2018-01-10 [18:52:01] [Server thread/DEBUG]: #5 plugins/API/src/vc_api/Main(62): pocketmine\Player->teleport(pocketmine\level\Position object)
2018-01-10 [18:52:01] [Server thread/DEBUG]: #6 src/pocketmine/command/PluginCommand(58): vc_api\Main->onCommand(vc_api\player\CustomPlayer object, pocketmine\command\PluginCommand object, string home, array Array())
2018-01-10 [18:52:01] [Server thread/DEBUG]: #7 src/pocketmine/command/SimpleCommandMap(258): pocketmine\command\PluginCommand->execute(vc_api\player\CustomPlayer object, string home, array Array())
2018-01-10 [18:52:01] [Server thread/DEBUG]: #8 src/pocketmine/Server(1987): pocketmine\command\SimpleCommandMap->dispatch(vc_api\player\CustomPlayer object, string home)
2018-01-10 [18:52:01] [Server thread/DEBUG]: #9 src/pocketmine/Player(2117): pocketmine\Server->dispatchCommand(vc_api\player\CustomPlayer object, string home)
2018-01-10 [18:52:01] [Server thread/DEBUG]: #10 plugins/API/src/vc_api/player/CustomPlayer(67): pocketmine\Player->chat(string /home)
2018-01-10 [18:52:01] [Server thread/DEBUG]: #11 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(220): vc_api\player\CustomPlayer->chat(string /home)
2018-01-10 [18:52:01] [Server thread/DEBUG]: #12 src/pocketmine/network/mcpe/protocol/CommandRequestPacket(54): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleCommandRequest(pocketmine\network\mcpe\protocol\CommandRequestPacket object)
2018-01-10 [18:52:01] [Server thread/DEBUG]: #13 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(92): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
2018-01-10 [18:52:01] [Server thread/DEBUG]: #14 src/pocketmine/network/mcpe/protocol/BatchPacket(118): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\CommandRequestPacket object)
2018-01-10 [18:52:01] [Server thread/DEBUG]: #15 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(92): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
2018-01-10 [18:52:01] [Server thread/DEBUG]: #16 src/pocketmine/Player(2964): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
2018-01-10 [18:52:01] [Server thread/DEBUG]: #17 src/pocketmine/network/mcpe/RakLibInterface(143): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
2018-01-10 [18:52:01] [Server thread/DEBUG]: #18 vendor/pmmp/raklib/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string ****************:16153, raklib\protocol\EncapsulatedPacket object, integer 0)
2018-01-10 [18:52:01] [Server thread/DEBUG]: #19 src/pocketmine/network/mcpe/RakLibInterface(84): raklib\server\ServerHandler->handlePacket()
2018-01-10 [18:52:01] [Server thread/DEBUG]: #20 src/pocketmine/network/Network(89): pocketmine\network\mcpe\RakLibInterface->process()
2018-01-10 [18:52:01] [Server thread/DEBUG]: #21 src/pocketmine/Server(2527): pocketmine\network\Network->processInterfaces()
2018-01-10 [18:52:01] [Server thread/DEBUG]: #22 src/pocketmine/Server(2279): pocketmine\Server->tick()
2018-01-10 [18:52:01] [Server thread/DEBUG]: #23 src/pocketmine/Server(2154): pocketmine\Server->tickProcessor()
2018-01-10 [18:52:01] [Server thread/DEBUG]: #24 src/pocketmine/Server(1742): pocketmine\Server->start()
2018-01-10 [18:52:01] [Server thread/DEBUG]: #25 src/pocketmine/PocketMine(554): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/****/, string /home/****/plugins/)
```

**Comment by dktapps** [comment] 2018-01-10 16:12
Another duplicate of #1449 .

**Closed by dktapps** 2018-01-10 16:12 UTC
