### ISSUE TITLE
There is no way to handle player interact when player is spectator

### ISSUE THREAD

**Issue by rdstonech** [pmmp/PocketMine-MP#2937] opened 2019-05-25 12:49 UTC
### Issue description
- Expected result: PlayerInteractEvent is called when player right clicked on air (in spectator)
- Actual result: We can't handle any inventory transaction when is on spectator

### Steps to reproduce the issue
1. create event or item (that uses onClickAir)
2. look that anything doesn't work

### OS and versions
* PocketMine-MP: 3.8.2 Release
* PHP: 7.3
* Server OS: Ubuntu 18.04
* Game version: PE/Win10

### Plugins
I needed just one plugin that handle PlayerInteractEvent for testing it

**Comment by dktapps** [comment] 2019-05-25 12:53
Duplicate of #2627

**Closed by dktapps** 2019-05-25 12:53 UTC

**Comment by rdstonech** [comment] 2019-05-25 12:59
@dktapps It will be fixed? On minigames server we can't handle quit item from arena when player is died. It's huge restriction. Now I need to handle directly InventoryTransactionPacket :(
