### ISSUE TITLE
The world is infinitely unloading.

### ISSUE THREAD

**Issue by Frago9876543210** [pmmp/PocketMine-MP#1974] opened 2018-01-27 13:56 UTC
### Issue description
The server freezes without cause and other errors in the unloading of the world. Another strange thing is that the process no longer exists. 
![im](https://snag.gy/gl9x6G.jpg)

### OS and versions
* PocketMine-MP: 41592a04b7d0124d155ea6d99be8f11fe14d1de1
* PHP: 7.2.1
* Server OS: Linux Debian 8.6 jessie

### Plugins
DevTools v1.12.7, ModalFormsAPI v1, clans v1, quests v1, DonateCases v1, RegionGuard v1.0.0, area v1, Kits v1.0.0, Shop v1, Economy v1, MineReset v3, PurePerms v1.4.0-INDEV, Evaluator v0.0.1, Horses v1.0.0, ToyBox v1, API v1.0.0, PureChat v1.4.0

**Comment by Muqsit** [comment] 2018-01-27 14:09
does it happen without any players too?

**Comment by dktapps** [comment] 2018-01-27 14:11
it would be appreciated if you could reproduce this with debug output enabled.

**Comment by Frago9876543210** [comment] 2018-01-27 14:12
@dktapps you mean X debug?

**Comment by dktapps** [comment] 2018-01-27 14:13
no, I mean debug log level in pocketmine.yml

**Comment by Frago9876543210** [comment] 2018-01-27 14:17
I can also add that this shit started to happen after January 18-19. Prior to this, with 84 players, the server did not freezes in unloading of the world.

**Comment by dktapps** [comment] 2018-01-27 14:22
@Frago9876543210 please watch your language.

It would be more helpful to know after which versions the bug started to occur. Also:

- plugins? specifically if you're using TeaSpoon then no support can be provided
- is the bug consistent or random?

**Comment by Frago9876543210** [comment] 2018-01-27 14:28
@dktapps 
- Plugins list added.
-  The error occurs entirely by accident. It is impossible to predict when it will happen.

**Comment by dktapps** [comment] 2018-01-27 14:29
you're running Evaluator on a production server? 💀

**Comment by Frago9876543210** [comment] 2018-01-27 14:32
Yea. This is a very useful thing. For example, to fix some errors without rebooting.

**Comment by zKoz210** [comment] 2018-01-27 14:49
I also encountered such a problem, however, it was only once.

**Comment by xinghao2003** [comment] 2018-01-27 14:59
I also have this problem random happen when the server stop

**Comment by dktapps** [comment] 2018-01-27 15:21
If someone can reproduce this with debug logging enabled, or offer ways to reproduce this, it would be much appreciated. I have never encountered this issue.

**Comment by dktapps** [comment] 2018-01-27 15:23
> Another strange thing is that the process no longer exists.

correction - it's just not bound to port 19132 anymore, which would indicate that RakLib's socket has closed (due to shutdown).

**Comment by Driesboy** [comment] 2018-01-27 16:06
I Have this with the asyn branch

Op 27-jan.-2018 14:56 schreef "Frago9876543210" <notifications@github.com>:

**Comment by Yexeed** [comment] 2018-01-27 16:39
For me, this happens when I have a plugin which removing items from creative inventory. I catched this problem about 2 month ago (nov. 2017).

**Comment by xISRAPILx** [comment] 2018-01-28 08:32
Do you use removeCreativeItem or unregisterCommand functions?

**Comment by dktapps** [comment] 2018-01-28 09:55
Unless you have something constructive to add to the discussion, please take the conversation elsewhere. This is not a support forum. Anything which does not directly pertain to the reported issue does not belong here.

**Comment by xISRAPILx** [comment] 2018-01-28 11:15
@dktapps After using these functions, I have the same problem. 

Sorry, bad English

**Comment by Bruno99** [comment] 2018-01-28 15:52
@xISRAPILx Terrorist!

**Comment by Frago9876543210** [comment] 2018-01-29 14:53
@dktapps 
![im](https://snag.gy/ytK24s.jpg)

**Comment by dktapps** [comment] 2018-01-29 14:55
so RakLib is getting stuck for some reason. Thanks @Frago9876543210 .

**Comment by dktapps** [comment] 2018-01-29 16:35
@Frago9876543210 would you mind making some modifications to RakLib and add some debug output into this function? https://github.com/pmmp/RakLib/blob/master/server/ServerHandler.php#L70-L78

It appears that RakLib is getting stuck while shutting down, but it is unclear why.

**Comment by Frago9876543210** [comment] 2018-01-29 16:59
@dktapps ok. What add?

**Comment by Frago9876543210** [comment] 2018-01-29 17:04
like this?
![im](https://snag.gy/WHgTEq.jpg)

**Comment by dktapps** [comment] 2018-01-29 17:05
that should be fine, yes.

**Comment by xinghao2003** [comment] 2018-01-29 22:49
tq

**Comment by xinghao2003** [comment] 2018-02-04 09:54
Can this log be used ?
```
[17:50:50] [Server thread/DEBUG]: Unloading all levels
[17:50:50] [Server thread/INFO]: Unloading level "lobby"
[17:50:50] [Server thread/INFO]: Unloading level "nether"
[17:50:50] [Server thread/INFO]: Unloading level "ender"
[17:50:50] [Server thread/INFO]: Unloading level "resources03"
[17:50:50] [Server thread/INFO]: Unloading level "resources02"
[17:50:50] [Server thread/INFO]: Unloading level "resources01"
[17:50:50] [Server thread/INFO]: Unloading level "residence01"
[17:50:50] [Server thread/DEBUG]: Removing event handlers
[17:50:50] [Server thread/DEBUG]: Stopping all tasks
[17:50:50] [Server thread/DEBUG]: Closing console
[17:50:50] [Server thread/DEBUG]: Stopping network interfaces
#1
#2
#3
#4
#5
Done
```

**Comment by dktapps** [comment] 2018-02-04 09:56
that's strange indeed... so it's not RakLib at all...

@xinghao2003 am I correct to assume that your server is then stuck after "done"?

**Comment by xinghao2003** [comment] 2018-02-04 10:06
Yes

**Comment by dktapps** [comment] 2018-02-04 10:07
that's very odd... hmm... I'm not sure what else could cause this.

**Comment by dktapps** [comment] 2018-02-04 10:15
I've pushed a commit to add additional debug for server shutdown. Please try it and report back where issues occur.

**Comment by xinghao2003** [comment] 2018-02-04 11:19
Latest Log
```
[19:18:07] [Server thread/DEBUG]: Unloading all levels
[19:18:07] [Server thread/INFO]: Unloading level "lobby"
[19:18:07] [Server thread/INFO]: Unloading level "nether"
[19:18:07] [Server thread/INFO]: Unloading level "ender"
[19:18:07] [Server thread/INFO]: Unloading level "resources03"
[19:18:07] [Server thread/INFO]: Unloading level "resources02"
[19:18:08] [Server thread/INFO]: Unloading level "resources01"
[19:18:08] [Server thread/INFO]: Unloading level "residence01"
[19:18:08] [Server thread/DEBUG]: Removing event handlers
[19:18:08] [Server thread/DEBUG]: Stopping all tasks
[19:18:08] [Server thread/DEBUG]: Closing console
[19:18:08] [Server thread/DEBUG]: Stopping network interfaces
[19:18:08] [Server thread/DEBUG]: Stopping network interface pocketmine\network\mcpe\RakLibInterface
#1
#2
#3
#4
[19:18:08] [RakLibServer thread/DEBUG]: Closed session for 115.132.200.23 55710
#5
Done
[19:18:08] [Server thread/DEBUG]: Stopping network interface specter\network\SpecterInterface
[19:18:08] [Server thread/DEBUG]: Collecting cycles
```

**Comment by dktapps** [comment] 2018-02-04 11:21
hmmmmmm... you're never seeing "stopping other threads"...

could you add some debug output after this line? 
https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/Server.php#L2106

and in these lines:
https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/PocketMine.php#L556-L569

**Comment by xinghao2003** [comment] 2018-02-04 13:16
Okay, It just stuck at Collecting cycles

**Comment by dktapps** [comment] 2018-02-04 14:53
this might be a GC issue in PHP then. This is very difficult to debug without being able to reproduce it myself.

If anyone would care to try and reproduce this without plugins, it would be appreciated.

**Comment by Muqsit** [comment] 2018-02-05 12:16
I've been facing this error too for the past couple of days, except it's been more severe just this week. I see you are running PHP 7.2.1 and I was too. I know this sounds really stupid as I don't have any exact justification for this but upgrading to PHP 7.2.2 solved this for me. I've not got any issues with PHP 7.2.2 so far. Can you upgrade your PHP and see if the problem persists?

**Comment by xinghao2003** [comment] 2018-02-05 14:10
I will try it, thanks

**Comment by xinghao2003** [comment] 2018-02-05 14:55
This issue still happen in PHP 7.2.2

**Comment by xinghao2003** [comment] 2018-02-05 15:00
Seems like PHP 7.2.2 make this issue happen every time I stop the server...

**Comment by dktapps** [comment] 2018-02-05 15:13
Please try it without plugins. I cannot reproduce this bug at all, so while it might well be a PHP bug, whatever is triggering the bug needs to be isolated if possible.

**Comment by Frago9876543210** [comment] 2018-02-05 17:03
@xinghao2003 not only on 7.2.2. I got this error with php 7.2.0 & 7.2.1

**Comment by Muqsit** [comment] 2018-04-11 12:09
@Frago9876543210 Do you have a plugin that registers or uses a custom world generator?

**Comment by Frago9876543210** [comment] 2018-04-11 13:03
@Muqsit no. I can also note that this error was on the old hosting with low ghz per core.

**Comment by daniktheboss** [comment] 2018-04-11 15:39
If I try to unload with a player on the server and in that world, it works fine. Without player it doesn't unload.

**Comment by dktapps** [comment] 2018-04-24 19:04
Upstream PR'd test case (no fix): https://github.com/krakjoe/pthreads/pull/861

**Comment by dktapps** [comment] 2018-06-13 09:01
This has not been fixed in pthreads but may have been resolved by recent changes on the master branch (no child threads in PocketMine-MP inherit loaded classes anymore), could someone confirm?

Note that this doesn't account for threads started by plugins.

**Comment by dktapps** [comment] 2018-07-06 13:57
Closing this since it doesn't occur any longer (unless using custom threads, which is a bug for pthreads to fix).

**Closed by dktapps** 2018-07-06 13:57 UTC
Labels: Category: PHP (extension), Status: Reproduced

**Comment by Frago9876543210** [comment] 2019-08-12 16:24
![изображение](https://user-images.githubusercontent.com/13465245/62880771-d58a3900-bd36-11e9-837b-4a7a04794c05.png)
I have it again on 4.0
