### ISSUE TITLE
Lanterns cannot be placed on all transparent blocks

### ISSUE THREAD

**Issue by Nerahikada** [pmmp/PocketMine-MP#4529] opened 2021-10-31 01:56 UTC
### Issue description
Lanterns can be placed on some permeable blocks.
For example, it can place on certain surfaces of stairs or slabs.

### Steps to reproduce the issue
1. Place lanterns on glass

### OS and versions
* PocketMine-MP: 63dfcc6
* reproduced at test.pmmp.io:19132

**Comment by Nerahikada** [comment] 2021-10-31 01:58
This problem is not only seen in the lantern but also in some other blocks such as the bed.

**Comment by alvin0319** [comment] 2021-10-31 02:03
The problem is caused by this code (in case of bed): https://github.com/pmmp/PocketMine-MP/blob/faad2365e2529d4bb6e86fcb26d6f46dc7ee93c9/src/block/Bed.php#L185

**Comment by dktapps** [comment] 2021-10-31 14:13
That makes no sense. That would allow lanterns to be placed on blocks like tallgrass.

**Comment by dktapps** [comment] 2022-05-20 14:21
Relates to #4856, fixed by #4886

**Closed by dktapps** 2022-05-20 14:21 UTC
Labels: Category: Gameplay, Status: Unconfirmed
