### ISSUE TITLE
Suffocation in doors

### ISSUE THREAD

**Issue by Polo1K** [pmmp/PocketMine-MP#368] opened 2017-02-17 17:21 UTC
I'm suffocating in any door except for iron/oak doors. pls fix.

**Comment by madecode15** [comment] 2017-02-17 17:25
> pls fix.

Unhappy with the development speed? You can create a pull request and fix it yourself.

This is a duplicate of #181 and you did not follow the issue format.

**Comment by Polo1K** [comment] 2017-02-17 17:46
I never stated that I was unhappy with the development speed, and do you need detailed instructions on placing a door?

**Comment by jasonwynn10** [comment] 2017-02-17 19:09
@Polo1K He is simply stating that this is a known issue. He is also stating that you may be able to fix it yourself if you know how to code php.

**Comment by dktapps** [comment] 2017-02-18 10:43
Closing as a duplicate of #181 , discussion should be continued there.

**Closed by dktapps** 2017-02-18 10:43 UTC
