### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by vLilly** [pmmp/PocketMine-MP#4257] opened 2021-06-09 03:18 UTC
[03:14:45] [Server thread/CRITICAL]: ErrorException: "Undefined offset: 2" (EXCEPTION) in "pmsrc/src/pocketmine/network/mcpe/NetworkBinaryStream" at line 714

**Comment by MrXMaster** [comment] 2021-06-09 03:24
Multiworld, update it or remove it

**Comment by DaisukeDaisuke** [comment] 2021-06-09 03:25
duplicate https://github.com/pmmp/PocketMine-MP/issues/4251#issuecomment-857090407

**Comment by leoderoin** [comment] 2021-06-09 07:47
how updtate MultiWorld ?

**Comment by VixikHD** [comment] 2021-06-09 08:39
This is problem caused by MultiWorld plugin, please, close the issue, as it is not caused by PocketMine

**Closed** 2021-06-09 09:01 UTC
Labels: Support request
