### ISSUE TITLE
Packet Processing Error Bug.

### ISSUE THREAD

**Issue by kkim93142** [pmmp/PocketMine-MP#6272] opened 2024-03-03 10:07 UTC
### Issue description
Caused by InventoryTransaction Packet.

- Expected result: normal
- Actual result: Packet Processing Error (id: 0ec4-9d6b-e17e)

### Steps to reproduce the issue
1. just hold an any item on main hand.
2. hold right click on any block.
3. do something that causes send packet to the server.
4. and hold the right cilck on the any block again.
5. kicks the player.

### OS and versions

* PocketMine-MP:5.11.1
* PHP:8.2.13
* Using JIT: no 
* Server OS: Linux
* Game version: Win10 (Minecraft ver: 1.20.60, Protocol ver: 649)

### Plugins

- If you remove all plugins, does the issue still occur? yes
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue? no
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by dktapps** [comment] 2024-03-03 14:42
Duplicate of #5728

**Closed as completed by dktapps** 2024-03-03 14:42 UTC
Labels: Resolution: Duplicate, Category: Client, Category: Network
