### ISSUE TITLE
Slowness Effect bug

### ISSUE THREAD

**Issue by Rush1533** [pmmp/PocketMine-MP#3074] opened 2019-08-03 13:51 UTC
### Issue description

- Expected result: Apply Slowness Effect by command and turn off the effect
- Actual result: Walking speed is not reset

### Steps to reproduce the issue
1. .../ effect <user name> slowness 9999 255 execute true / effect <user name> execute clear

### OS and versions

* PocketMine-MP:3.9.0
* PHP:7.2
* Server OS:Linux
* Game version: PE/Win10 

### Plugins
There is no plugin

**Comment by dktapps** [comment] 2019-08-03 13:59
Duplicate of #1551

**Closed by dktapps** 2019-08-03 13:59 UTC
