### ISSUE TITLE
Furnace Bug doesn't drop EXP

### ISSUE THREAD

**Issue by xodamcm** [pmmp/PocketMine-MP#4983] opened 2022-04-22 16:47 UTC
the furnace doesn't drop the EXP 

Plugin used: 0
Pocketmine 4.3.0

**Comment by ColinHDev** [comment] 2022-04-22 16:53
duplicate of https://github.com/pmmp/PocketMine-MP/issues/4418

**Closed as completed** 2022-04-22 16:56 UTC
Labels: Resolution: Duplicate, Category: Gameplay
