### ISSUE TITLE
Transfer error

### ISSUE THREAD

**Issue by DroidPlaysM** [pmmp/PocketMine-MP#1307] opened 2017-08-22 21:51 UTC
Issue description

When doing /transferserver < server  > [port] gives this error then crashes player and can't rejoin without restarting the server.

[17:29:03] [Server thread/CRITICAL]: Error: "Call to a member function addChunkPacket() on null" (EXCEPTION) in "src/pocketmine/Player" at line 2145
[17:29:03] [Server thread/CRITICAL]: [Network] Stopped interface pocketmine\network\mcpe\RakLibInterface due to Undefined index

Steps to reproduce the issue

Join the game and do /transferserver Ip port 

Plugins

    Tested without plugins

**Comment by dktapps** [comment] 2017-08-22 21:52
Duplicate of #1239

**Closed by dktapps** 2017-08-22 21:52 UTC
