### ISSUE TITLE
I put a resource pack bigger than 12 megabytes and it doesn't work

### ISSUE THREAD

**Issue by fabrififi** [pmmp/PocketMine-MP#3214] opened 2019-12-08 10:23 UTC
### Issue description

- Expected result: normally download the resource pack of 12 mb or more as happens for those smaller than 2mb for example that work
- Actual result: I put a resource pack bigger than 12 megabytes and it doesn't download and if I'm waiting a long time it disconnects me and blocks me for 300 seconds and activating debug mode from pocketmine.yml creates a very long text with ranklib errors

### Steps to reproduce the issue
1. use a resource pack larger than 12 mb

### OS and versions

* PocketMine-MP:1.13.1
* PHP: 7.3.11
* Server OS: Linux
* Game version: Android/Win10/IOS

### Plugins
I had not put any plugins yet

- If you remove all plugins, does the issue still occur? Yes
- If the issue is **not** reproducible without plugins: the problem is both with and without plugins
  - Have you asked for help on our forums before creating an issue? No
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
I could copy the debug but it is too big and goes outside the console limit

### Crashdump, backtrace or other files
 does not create a crash dump
my resourcepack
[test.zip](https://github.com/pmmp/PocketMine-MP/files/3936095/test.zip)

**Comment by dktapps** [comment] 2019-12-08 10:23
duplicate of #3127

**Closed by dktapps** 2019-12-08 10:23 UTC
