### ISSUE TITLE
Cake bug

### ISSUE THREAD

**Issue by Ascrel** [pmmp/PocketMine-MP#3643] opened 2020-06-27 18:42 UTC
### Issue description

- Expected result: The cake should stay the same after I have eaten a bit from it.
- Actual result: The cake is back to normal after I placed another cake on a carpet next to the cake I have eaten a bit from.

### Steps to reproduce the issue
1. Place a cake and eat a bit from it
2. Place a carpet next to the cake and then place another cake on the carpet
Here is a link to a video showing the reproduction of the bug: https://youtu.be/8BYwSGOpWps

### OS and versions

* PocketMine-MP: 3.14.0
* PHP: 7.3
* Server OS: Windows 10, Local Server.
* Game version: Windows 10

### Plugins
None.

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by dktapps** [comment] 2020-06-27 18:54
DUPLICATE OF #3591

**Closed by dktapps** 2020-06-27 18:54 UTC
