### ISSUE TITLE
Blocks randomly changing.

### ISSUE THREAD

**Issue by Spaldam** [pmmp/PocketMine-MP#337] opened 2017-02-09 03:58 UTC
**Issue description**

When mining with a diamond pickaxe, sometimes the blocks turn to dirt after being broken instead of turning to air. Sometimes I can even just touch the block and it will change into another block, usually dirt.

**Steps to reproduce the issue**

seems random.  not sure when it occurs or why. At first it seemed to only happen in a certain area close to the bedrock, but then it happened again further upwards.

**OS and versions**

PocketMine-MP: 1.6.2dev "Unleashed" (API 3.0.0-ALPHA3)
PHP: 7.0
Server OS: Ubuntu 16.04.01 - Linux Spaldam 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Game version: PE 1.0.2 MCPE on Android Nugget 7.0

**Crashdump, backtrace or other files**
https://youtu.be/7uSMiN36fog

**Comment by HimbeersaftLP** [comment] 2017-02-09 04:45
This often happens in newly generated worlds, is your world newly generated?

**Comment by Spaldam** [comment] 2017-02-09 05:21
Yes it is. Just started it a few hours ago.

**Comment by robske110** [comment] 2017-02-09 06:10
Are you sure your are running the latest PM version? Could you somehow provide a git hash of your version? Because for this exact bug there was a BugFix.

**Comment by daniktheboss** [comment] 2017-02-09 06:38
Confirmed. Also happens to me

**Comment by Sandertv** [comment] 2017-02-09 06:48
Relates to #265 I assume.

**Comment by dktapps** [comment] 2017-02-09 08:32
More like a duplicate of #265.

**Closed by dktapps** 2017-02-09 08:32 UTC

**Comment by Spaldam** [comment] 2017-02-10 03:37
I'm not sure how to do a git hash, but I did copy and past the version from the servers own output. Plus I just downloaded it yesterday, and got it running yesterday, so it can't be that old.

https://forums.pmmp.io/threads/get-pmmp-io-for-linux-macos.243/page-2
