### ISSUE TITLE
Inventory not works in spectator mode

### ISSUE THREAD

**Issue by Frago9876543210** [pmmp/PocketMine-MP#3061] opened 2019-07-29 12:09 UTC
## Description
It is impossible to somehow listen inventory when a player has switched to spectator mode because this condition not allow do this:
https://github.com/pmmp/PocketMine-MP/blob/379a40c13af95163bb42de9c6bf011db2d70a09d/src/pocketmine/network/mcpe/handler/InGamePacketHandler.php#L164-L168
Also see #2627 issue

## Justification
Spectator mode useful in mini games, etc. Why not to allow this?

## Alternative methods
- Put this check into separate protected method
- Call some event here

**Comment by dktapps** [comment] 2019-07-29 12:22
This is in effect a duplicate of #2627 .

**Closed by dktapps** 2019-07-29 12:22 UTC
