### ISSUE TITLE
Fast eating while canceling the PlayerItemDropEvent.

### ISSUE THREAD

**Issue by Laith98Dev** [pmmp/PocketMine-MP#5737] opened 2023-05-06 09:20 UTC
### Issue description

- Expected result: Eating normally as usual
- Actual result: Eating faster than usual

### Steps to reproduce the issue
1. Cancel the PlayerItemDropEvent.
2. Obtain any type of food to test, and the count of the item must be more than 1.
3. Begin eating and then drop the item at the same time while keeping the right-click button pressed.

### OS and versions
* PocketMine-MP: 4.20.2 (git hash: 22f8623e176e6cff5d87069fc300c191b78c2ceb)
* PHP: 8.0.25
* Using JIT: no
* Server OS: linux
* Game version: Win10

### Plugins
No plugins except one plugin to cancel the event

- If you remove all plugins, does the issue still occur? No

### Crashdump, backtrace or other files
Nothing

Video:
https://cdn.discordapp.com/attachments/908006719370707025/1104322755568078959/Minecraft_2023-05-06_11-22-45.mp4

**Comment by dktapps** [comment] 2023-05-06 13:26
Duplicate of #4936

**Closed as completed by dktapps** 2023-05-06 13:26 UTC
Labels: Resolution: Duplicate, Category: Gameplay
