### ISSUE TITLE
Bugs with player skins

### ISSUE THREAD

**Issue by Govdim** [pmmp/PocketMine-MP#3632] opened 2020-06-26 20:20 UTC
### Issue description

Instead of player skins, Steve's are displayed
And all players see it, and not just me
The same problem with NPCs

### OS and versions

* PocketMine-MP: 3.14.0
* PHP: 7.3
* Server OS: Ubuntu 18.04
* Game version: PE/Win10

**Comment by dktapps** [comment] 2020-06-26 20:53
duplicate of #3627

**Closed by dktapps** 2020-06-26 20:53 UTC
