### ISSUE TITLE
Crash issues [Chunk Error]

### ISSUE THREAD

**Issue by Misteboss** [pmmp/PocketMine-MP#156] opened 2016-12-08 15:30 UTC
### Issue description

Very often after a reset of a map, the server crash with this error, i checked and the maps is loaded, i don't know why :|. Some friends have the same problem.
### Steps to reproduce the issue

1. ... Reset a map (unload and load it)
2. ... join the world, the server will crash 1/6 with this error

### OS and versions

* PocketMine-MP: 5d16ecc
* PHP: 7.0.2
* Server OS: Debian
* Game version: PE/Win10 

### Crashdump, backtrace or other files

* ... Console : 016-12-08 Unloading level "BuildUHC1vs1(2)"
 Preparing level "BuildUHC1vs1(2)"
 Unloading level "BuildUHC1vs1(2)"
reparing level "BuildUHC1vs1(2)"
 Error: "Call to a member function getChunk() on null" (EXCEPTION) in "/src/pocketmine/level/Level" at line 2462
An unrecoverable error has occurred and the server has crashed. Creating a crash dump
An unrecoverable error has occurred and the server has crashed. Creating a crash dump

**Comment by Misteboss** [comment] 2016-12-08 15:32
It concerns that line 
-> 		$chunk = $this->provider->getChunk($x, $z, $generate);

**Comment by Misteboss** [comment] 2016-12-08 18:29
Oh and it's caused by .mcr worlds i think cause when the server crash it's caused by a map in .mcr world format and never by .mca worlds, is it possible to convert the worlds or to fix that ?

**Comment by dktapps** [comment] 2016-12-08 19:02
Please provide a proper crashdump.

**Comment by Misteboss** [comment] 2016-12-08 19:18
Ok i  going to send you one now ;)

**Comment by Misteboss** [comment] 2016-12-08 19:20
This is the crashdumps :
Crash Dump Thu Dec 8 09:05:05 EST 2016

Error: Call to a member function startTiming() on null
File: /src/pocketmine/level/format/mcregion/McRegion
Line: 209
Type: notice

Code:
[200] 
[201] 	public function loadChunk($chunkX, $chunkZ, $create = false){
[202] 		$index = Level::chunkHash($chunkX, $chunkZ);
[203] 		if(isset($this->chunks[$index])){
[204] 			return true;
[205] 		}
[206] 		$regionX = $regionZ = null;
[207] 		self::getRegionIndex($chunkX, $chunkZ, $regionX, $regionZ);
[208] 		$this->loadRegion($regionX, $regionZ);
[209] 		$this->level->timings->syncChunkLoadDataTimer->startTiming();
[210] 		$chunk = $this->getRegion($regionX, $regionZ)->readChunk($chunkX - $regionX * 32, $chunkZ - $regionZ * 32);
[211] 		if($chunk === null and $create){
[212] 			$chunk = $this->getEmptyChunk($chunkX, $chunkZ);
[213] 		}
[214] 		$this->level->timings->syncChunkLoadDataTimer->stopTiming();
[215] 
[216] 		if($chunk !== null){
[217] 			$this->chunks[$index] = $chunk;
[218] 			return true;
[219] 		}else{

Backtrace:
#0 /src/pocketmine/level/format/anvil/Anvil(137): pocketmine\level\format\mcregion\McRegion->getChunk(integer 9, integer 11, boolean 1)
#1 /src/pocketmine/level/Level(2763): pocketmine\level\format\anvil\Anvil->getChunk(integer 9, integer 11, boolean 1)
#2 /src/pocketmine/level/Level(694): pocketmine\level\Level->loadChunk(integer 9, integer 11)
#3 /src/pocketmine/Player(954): pocketmine\level\Level->registerChunkLoader(pocketmine\Player Player(188), integer 9, integer 11, boolean 1)
#4 /src/pocketmine/Player(2027): pocketmine\Player->sendNextChunk(boolean)
#5 /src/pocketmine/Server(2905): pocketmine\Player->checkNetwork(boolean)
#6 /src/pocketmine/Server(2594): pocketmine\Server->tick(boolean)
#7 /src/pocketmine/Server(2472): pocketmine\Server->tickProcessor(boolean)
#8 /src/pocketmine/Server(2053): pocketmine\Server->start(boolean)
#9 /src/pocketmine/PocketMine(467): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string /home/srv1/, string /home/srv1/, string /home/srv1/plugins/, string unknown)

**Comment by Misteboss** [comment] 2016-12-08 19:22
This is the crashdumps 👍  @dktapps 
Crash Dump Thu Dec 8 09:14:32 EST 2016

Error: Call to a member function getChunk() on null
File: /src/pocketmine/level/Level
Line: 2764
Type: notice

Code:
[2755] 	public function loadChunk(int $x, int $z, bool $generate = true) : bool{
[2756] 		if(isset($this->chunks[$index = Level::chunkHash($x, $z)])){
[2757] 			return true;
[2758] 		}
[2759] 
[2760] 		$this->timings->syncChunkLoadTimer->startTiming();
[2761] 
[2762] 		$this->cancelUnloadChunkRequest($x, $z);
[2763] 
[2764] 		$chunk = $this->provider->getChunk($x, $z, $generate);
[2765] 		if($chunk === null){
[2766] 			if($generate){
[2767] 				throw new \InvalidStateException("Could not create new Chunk");
[2768] 			}
[2769] 			return false;
[2770] 		}
[2771] 
[2772] 		if($this->provider->getProviderName() == "mcregion"){
[2773] 			if($chunk->getBiomeColor(0, 0) == [0, 0, 0]){
[2774] 				for($x = 0; $x < 16; ++$x){

Backtrace:
#0 /src/pocketmine/Player(954): pocketmine\level\Level->registerChunkLoader(pocketmine\Player Player(32), integer 8, integer 19, boolean 1)
#1 /src/pocketmine/Player(2027): pocketmine\Player->sendNextChunk(boolean)
#2 /src/pocketmine/Server(2905): pocketmine\Player->checkNetwork(boolean)
#3 /src/pocketmine/Server(2594): pocketmine\Server->tick(boolean)
#4 /src/pocketmine/Server(2472): pocketmine\Server->tickProcessor(boolean)
#5 /src/pocketmine/Server(2053): pocketmine\Server->start(boolean)
#6 /src/pocketmine/PocketMine(467): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string /home/srv1/, string /home/srv1/, string /home/srv1/plugins/, string unknown)

**Comment by Misteboss** [comment] 2016-12-11 11:47
It makes my server so instable please fix it :|, this is the second error
Unloading level "BuildUHC1vs1(2)"
Preparing level "BuildUHC1vs1(2)"
Unloading level "BuildUHC1vs1(2)"
 Preparing level "BuildUHC1vs1(2)"
Error: "Call to a member function startTiming() on null" (EXCEPTION) in "/src/pocketmine/level/format/mcregion/McRegion" at line 209
An unrecoverable error has occurred and the server has crashed. Creating a crash dump
Please upload the "/home/srv1/crashdumps
This error happens when i delete the $this->provider = null;
Please help @dktapps :(

**Comment by dktapps** [comment] 2016-12-11 14:22
Can you share the code you are using to perform these level unloads and reloads?

**Comment by Misteboss** [comment] 2016-12-11 17:51
if (!is_file($this->pg->getDataFolder() . 'arenes/' . $this->name . '/' . $this->world . '.tar') && !is_file($this->pg->getDataFolder() . 'arenes/' . $this->name . '/' . $this->world . '.tar.gz'))
            return false;
        if ($this->pg->getServer()->isLevelLoaded($this->world)) {
            if ($this->pg->getServer()->getLevelByName($this->world)->getAutoSave() || $this->pg->configs['world.reset.from.tar']) {
                $this->pg->getServer()->unloadLevel($this->pg->getServer()->getLevelByName($this->world));
                if (is_file($this->pg->getDataFolder() . 'arenes/' . $this->name . '/' . $this->world . '.tar'))
                    $tar = new \PharData($this->pg->getDataFolder() . 'arenes/' . $this->name . '/' . $this->world . '.tar');
                elseif (is_file($this->pg->getDataFolder() . 'arenes/' . $this->name . '/' . $this->world . '.tar.gz'))
                    $tar = new \PharData($this->pg->getDataFolder() . 'arenes/' . $this->name . '/' . $this->world . '.tar.gz');
                else
                    return false;
                $tar->extractTo($this->pg->getServer()->getDataPath() . 'worlds/' . $this->world, null, true);
                unset($tar);
                $this->pg->getServer()->loadLevel($this->world);
            }
            $this->pg->getServer()->unloadLevel($this->pg->getServer()->getLevelByName($this->world));
            $this->pg->getServer()->loadLevel($this->world);
            $this->pg->getServer()->getLevelByName($this->world)->setAutoSave(false);
        } else {
            if (is_file($this->pg->getDataFolder() . 'arenes/' . $this->name . '/' . $this->world . '.tar'))
                $tar = new \PharData($this->pg->getDataFolder() . 'arenes/' . $this->name . '/' . $this->world . '.tar');
            elseif (is_file($this->pg->getDataFolder() . 'arenes/' . $this->name . '/' . $this->world . '.tar.gz'))
                $tar = new \PharData($this->pg->getDataFolder() . 'arenes/' . $this->name . '/' . $this->world . '.tar.gz');
            else
                return false;
            $tar->extractTo($this->pg->getServer()->getDataPath() . 'worlds/' . $this->world, null, true);
            unset($tar);
            $this->pg->getServer()->loadLevel($this->world);

**Comment by Misteboss** [comment] 2016-12-11 17:51
@dktapps

**Comment by dktapps** [comment] 2016-12-11 17:54
Please use ``` around code blocks in future.

**Comment by Misteboss** [comment] 2016-12-11 17:57
done @dktapps

**Comment by Misteboss** [comment] 2016-12-12 06:06
Is it possible to check if the chunk exist so the server will not crash or something like that ?

**Comment by Misteboss** [comment] 2016-12-16 19:12
Do you have some news about that ? @dktapps

**Comment by dktapps** [comment] 2016-12-19 21:42
I haven't been able to identify what the cause of this bug may be. The issue appears to be that the level is retained after it's unloaded, which causes the unloaded level to be returned from Server->getLevelByName() instead of the newly loaded one. I can't identify what in the core could result in this happening, so I'm afraid that right now I can't help you. This will be investigated in more detail at a later date.

**Comment by legoboy0215** [comment] 2016-12-28 09:34
Sorry for bumping this, but didn't you fix it last time? There was a similar issue, and you implemented WeakPosition to address it.

**Comment by Misteboss** [comment] 2016-12-28 20:54
It happens with mcpe 1.0 branch too, others servers have this issues we need it to ne fixed :(

**Comment by Misteboss** [comment] 2016-12-29 17:15
I finally found the origin of the crash (not sure), when you teleport a player in a zone where the chunk aren't load for exemple (EnderPearl) the server crash.

**Comment by dktapps** [comment] 2017-01-04 13:42
@Misteboss Would you try to reproduce branch `issues/156` and report back what issues occur? Please make sure to set `zend.assertions = 1` in your php.ini for testing.

**Comment by dktapps** [comment] 2017-01-09 13:19
Closing due to lack of response.

**Closed by dktapps** 2017-01-09 13:19 UTC
Labels: Category: Core, Resolution: Awaiting Response

**Comment by sylvrs** [comment] 2023-08-27 21:55
Ok

**Comment by JustTalDevelops** [comment] 2023-08-27 21:55
Reopening this due to response.
