### ISSUE TITLE
Item setCustomName() bug.

### ISSUE THREAD

**Issue by Muqsit** [pmmp/PocketMine-MP#244] opened 2017-01-09 17:19 UTC
### Issue description

Item::setCustomName() wipes out the current compound tag on the item.

After going through the Item::setCustomName() function, I found out that...
if (item has compound tag) {
    tag = new CompoundTag("", []);
} else {
    tag = this->getNamedTag();
}
Shouldn't it be the opposite?

### Steps to reproduce the issue

1. Enchant the item.
2. Now custom name it. Notice how the ehcnat disappears. (Save the item NBT to a file and view it, if the item still shows as enchanted).

### OS and versions

* PocketMine-MP: 6e87a48
* PHP: 7.0.11
* Server OS: Ubuntu 14.04
* Game version: Both (core issue)

### Crashdump, backtrace or other files

* ...

**Comment by dktapps** [comment] 2017-01-09 22:43
Related to iTXTech/Genisys#2038 (https://github.com/iTXTech/Genisys/issues/2038#issuecomment-260428170)

**Comment by dktapps** [comment] 2017-01-09 22:48
If you are referring to [this](https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/item/Item.php#L562) line, I think you missed the fact that there is a `!` present. That code is overcomplicated though.

**Comment by dktapps** [comment] 2017-01-10 00:34
I cannot reproduce this, although reproduced the issue detailed on the Genisys issue with ease.

**Comment by dktapps** [comment] 2017-01-10 01:29
Closing due to not reproducible.

**Closed by dktapps** 2017-01-10 01:29 UTC
Labels: Category: Core, Category: Gameplay, Status: Unconfirmed

**Comment by Muqsit** [comment] 2017-01-10 08:11
Couldn't reply because I was in school. Sorry bout that.
