### ISSUE TITLE
Everyone receives food particles and sounds

### ISSUE THREAD

**Issue by Wumpotamus** [pmmp/PocketMine-MP#3354] opened 2020-03-13 00:56 UTC
### Issue description
When using bleeding edge, when one player eats, every player sees the particles and sounds on their side. It's been discussed on discord, but never reported on GitHub.

- Expected result: Only the person eating receives particles and sounds.
- Actual result: Everyone receives particles and sounds.

### Steps to reproduce the issue
1. Join a server with a friend.
2. Eat.
3. Profit.

### OS and versions

* PocketMine-MP: 4.0.0
* PHP: 7.3
* Server OS: Linux
* Game version: PE

**Comment by dktapps** [comment] 2020-03-13 01:16
pretty sure this is WAI...

**Comment by Wumpotamus** [comment] 2020-03-13 01:33
If you mean works as intended, it's not? Every player shouldn't see the particles from their pov, they should see the other player eating, but not themselves if they aren't eating

**Comment by dktapps** [comment] 2020-03-13 02:23
the original comment didn't make this clear.

**Comment by dktapps** [comment] 2020-03-13 12:15
I don't currently have the time or interest to look into this, so if someone else wants to jump in, please go ahead. You'll want to look into `ActorEventPacket`'s handling.

**Comment by dktapps** [comment] 2020-03-13 12:17
also please check if this bug occurs on the latest releases too.

**Comment by Saehing** [comment] 2020-03-13 12:21
> also please check if this bug occurs on the latest releases too.

This bug has been around for a long time, and still exists today

**Comment by Wumpotamus** [comment] 2020-03-13 12:22
Only occurs on 4.0, commit in use is about 3 days old now, but, never had the problems on the 3.x releases

**Comment by dktapps** [comment] 2020-03-13 12:27
there's no obvious reason why this bug should be occurring and I don't have the time to dig deeper into it.

@Wumpotamus There are behavioural differences on PM4 vs PM3, so it would be good to know for sure if the bug you're talking about happens on PM3 as well. It'll help to narrow down the cause of the bug.

**Comment by Saehing** [comment] 2020-03-13 12:27
> also please check if this bug occurs on the latest releases too.

In addition, I reported this problem earlier, but was ignored
https://github.com/pmmp/PocketMine-MP/issues/3246

**Comment by dktapps** [comment] 2020-03-13 15:21
fixed in c9e859851079c3bc10b94be4dfa885340408f634, thanks!

**Closed by dktapps** 2020-03-13 15:21 UTC
Labels: Category: Gameplay, Category: Protocol, Status: Unconfirmed
