### ISSUE TITLE
Packet Processing Error

### ISSUE THREAD

**Issue by ShadowMikado** [pmmp/PocketMine-MP#6226] opened 2024-01-14 22:51 UTC
### Issue description

- Expected result: Let nothing happen.
- Actual result: The client crashes.

### Steps to reproduce the issue
1. Keep your right-click pressed
2. Aim at a block
3. Move your mouse quickly

### OS and versions

* PocketMine-MP: 5.10.0
* PHP: 8.1.34
* Using JIT:  no  
* Server OS: linux (Ubuntu)
* Game version: Win10

### Plugins

- If you remove all plugins, does the issue still occur?
`Yes`

### Crashdump, backtrace or other files

```2024-01-14 [22:44:13.954] [Server thread/INFO]: ShadowMikado left the game
2024-01-14 [22:44:13.958] [Server thread/INFO]: [NetworkSession: ShadowMikado] Session closed: Bad packet: Exceeded rate limit for "Game Packets" (Error ID: e209-a036-8138)
2024-01-14 [22:44:13.964] [RakLib thread/NOTICE]: Blocked 192.168.0.59 for 5 seconds
```

https://github.com/pmmp/PocketMine-MP/assets/89030950/4862c5b6-34c4-44e0-b05d-0723da895a62

**Comment by IvanCraft623** [comment] 2024-01-15 00:53
Duplicate of #5728

**Closed as completed by IvanCraft623** 2024-01-15 00:53 UTC
