### ISSUE TITLE
LevelDB spawns player at y 32767

### ISSUE THREAD

**Issue by Wumpotamus** [pmmp/PocketMine-MP#2853] opened 2019-04-02 02:56 UTC
### Issue description

- Expected result: Player spawns on the saved world spawn at correct x, y, and z.
- Actual result: Player spawns at the correct x and z, but at y 32767, regardless of saved spawn.

### Steps to reproduce the issue
This may require less steps, but easiest to get it like this.
1. Turn player data saving off in pocketmine.yml
2. Join a leveldb world, set the world spawn.
3. Restart the server after setting spawn, making sure you save the world.
4. Turn the server back on and join.
5. Profit!

### OS and versions

* PocketMine-MP: 3.7.1
* PHP: 7.2.15
* Server OS: Windows
* Game version: PE/Win10

### Plugins

Can be reproduced without plugins.

**Comment by dktapps** [comment] 2019-04-02 10:54
does the world folder name match the world display name?

**Comment by Wumpotamus** [comment] 2019-04-02 11:50
Yes.

**Comment by dktapps** [comment] 2019-04-02 11:50
Closing as duplicate of #2724 .

**Closed by dktapps** 2019-04-02 11:50 UTC
