### ISSUE TITLE
Level::addParticle() error

### ISSUE THREAD

**Issue by gizanopatrica** [pmmp/PocketMine-MP#1225] opened 2017-07-21 08:27 UTC
### Issue description
Adding particles (only some) to a level does not work - only console spam

### Steps to reproduce the issue
1. Add a particle to a level
2. Check your console

### OS and versions
* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/1a7f567a70c58b0848def59118aad16557750ff3
* PHP: 7.02
* Server OS: Linux
* Game version: PE

### Plugins
Because I am using a plugin to add the particles, it is not reproducible without plugins - however I tried code from other developers adding the same particles and it didn't work

### Crashdump, backtrace or other files
Log (read from the bottom to the top):
[10:36:38] [Server thread/DEBUG] #11 /custom-phar.phar(1): require_once(string phar:///custom-phar.phar/src/pocketmine/PocketMine.php)
[10:36:38] [Server thread/DEBUG] #10 src/pocketmine/PocketMine(511): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar:///custom-phar.phar/, string /, string /plugins/)
[10:36:38] [Server thread/DEBUG] #9 src/pocketmine/Server(1702): pocketmine\Server->start()
[10:36:38] [Server thread/DEBUG] #8 src/pocketmine/Server(2120): pocketmine\Server->tickProcessor()
[10:36:38] [Server thread/DEBUG] #7 src/pocketmine/Server(2241): pocketmine\Server->tick()
[10:36:38] [Server thread/DEBUG] #6 src/pocketmine/Server(2479): pocketmine\Server->checkTickUpdates(integer 3746, double 1500561398.6731)
[10:36:38] [Server thread/DEBUG] #5 src/pocketmine/Server(2324): pocketmine\level\Level->doTick(integer 3746)
[10:36:38] [Server thread/DEBUG] #4 src/pocketmine/level/Level(747): pocketmine\Server->batchPackets(array Array(), array Array(), boolean , boolean )
[10:36:38] [Server thread/DEBUG] #3 src/pocketmine/Server(1865): pocketmine\network\mcpe\protocol\BatchPacket->addPacket(pocketmine\network\mcpe\protocol\LevelEventPacket object)
[10:36:38] [Server thread/DEBUG] #2 src/pocketmine/network/mcpe/protocol/BatchPacket(72): pocketmine\network\mcpe\protocol\DataPacket->encode()
[10:36:38] [Server thread/DEBUG] #1 src/pocketmine/network/mcpe/protocol/DataPacket(72): pocketmine\network\mcpe\protocol\LevelEventPacket->encodePayload()
[10:36:38] [Server thread/DEBUG] #0 src/pocketmine/network/mcpe/protocol/LevelEventPacket(118): pocketmine\utils\BinaryStream->putVarInt(double 2.9534396724559)
[10:36:38] [Server thread/CRITICAL] TypeError: "Argument 1 passed to pocketmine\utils\BinaryStream::putVarInt() must be of the type integer, float given, called in phar:///custom-phar.phar/src/pocketmine/network/mcpe/protocol/LevelEventPacket.php on line 118" (EXCEPTION) in "src/pocketmine/utils/BinaryStream" at line 334
[10:36:38] [Server thread/CRITICAL] Could not tick level "Backup": Argument 1 passed to pocketmine\utils\BinaryStream::putVarInt() must be of the type integer, float given, called in phar:///custom-phar.phar/src/pocketmine/network/mcpe/protocol/LevelEventPacket.php on line 118

**Comment by dktapps** [comment] 2017-07-21 08:35
> however I tried code from other developers adding the same particles and it didn't work

This means nothing other than the other code was just as defective as yours.

> only some

Which? Don't leave any details out, I don't want to guess.

Since this is not reproducible except with third-party code which I have not seen and therefore cannot review, this issue will be closed as a plugin support request unless further information is provided. You should use the forums for plugin help, not our issue tracker.

**Closed by dktapps** 2017-07-21 08:35 UTC
