### ISSUE TITLE
Unable to load large resource packs

### ISSUE THREAD

**Issue by CanadianBaconBoi** [pmmp/PocketMine-MP#3262] opened 2019-12-29 20:29 UTC
### Issue description

![image](https://user-images.githubusercontent.com/6825354/71562510-07761080-2a36-11ea-9ced-281f2f5c8235.png)

- Expected result: A large resource pack loads
- Actual result: You get stuck on the downloading page at 1.0 MB

### Steps to reproduce the issue
1. Add a large resource pack to the resource_packs folder and force it on clients
2. Attempt to join the server

### OS and versions

* PocketMine-MP: Build #1785, Jenkins
* PHP: 7.2
* Server OS: Ubuntu
* Game version: PE/Win10

### Plugins

Plugins (14): MagicPortal v1.3.4, BuilderTools v3.11.1, Colormatic v1.0.3-1, SkinFIX v3.11.1, TransferAPI v1.0, Hierarchy v1.1.2, NoLeafDecay v1.0.0, LobbyPlus v3.11.1, DevTools v3.11.1, FormAPI v3.11.1, ScoreHud v4.0.0, TPSD v3.11.1, JukeBox v1.0.1, HRKChat v1.1.0
- If you remove all plugins, does the issue still occur? Yes

**Comment by dktapps** [comment] 2019-12-29 21:03
duplicate of #3232 , #3127 , #3214 , #3213

**Closed by dktapps** 2019-12-29 21:03 UTC
