### ISSUE TITLE
Canceling PlayerItemConsumeEvent still feeds you

### ISSUE THREAD

**Issue by HashimTheArab** [pmmp/PocketMine-MP#4688] opened 2022-01-02 04:34 UTC
### Issue description
When canceling PlayerItemConsumeEvent, food still feeds you

- Expected result: Nothing
- Actual result: Player gained food

### Steps to reproduce the issue
1. Cancel PlayerItemConsumeEvent
2. Let your hunger go down
3. Eat something

### OS and versions

* PocketMine-MP: 4.0.3
* PHP: 8.0.1
* Using JIT: no
* Server OS: Windows
* Game version: Win10

### Plugins
Plugins (2): DevTools v1.15.0+dev, PAI v0.0.1

- If you remove all plugins, does the issue still occur?
  No because I have to cancel the event
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
```php
class Main extends PluginBase implements Listener {

	public function onEnable(): void{
		$this->getServer()->getPluginManager()->registerEvents($this, $this);
	}

	public function onConsume(PlayerItemConsumeEvent $event) : void {
		$event->cancel();
	}

}
```
### Crashdump, backtrace or other files>
https://user-images.githubusercontent.com/13991048/147866330-5ed7ca28-677e-4dd6-acd5-34f0f52ae605.mp4

**Comment by dktapps** [comment] 2022-01-02 12:48
Duplicate of #2728.

**Closed as completed by dktapps** 2022-01-02 12:48 UTC
Labels: Resolution: Duplicate, Category: Gameplay, Category: Client
