### ISSUE TITLE
Cactus is not growing

### ISSUE THREAD

**Issue by AlicanCopur** [pmmp/PocketMine-MP#2890] opened 2019-04-29 08:23 UTC
### Issue description

- Expected result: I wanted the cactus to grow
- Actual result: cactus did not grow

### Steps to reproduce the issue
1. I planted the cactus on the sand
2. I waited half an hour but didn't grow up

## OS and versions

* PocketMine-MP: 3.8.1
* PHP: 7.2.0
* Server OS: Centos 7 x64
* Game version: MCPE v1.11.0

### Plugins

Plugins(3): PurePerms v1, PureChat v1, HashCore v2.0.2

**Comment by JackMD** [comment] 2019-04-29 10:01
Have you tried without any plugins?

**Comment by AlicanCopur** [comment] 2019-04-29 10:08
Yes

**Comment by dktapps** [comment] 2019-09-18 09:34
Closing as unable to reproduce. If this was really an issue, I'd have players all over me complaining about their cactus farms not working. This is more likely a misconfiguration of your server.

**Closed by dktapps** 2019-09-18 09:34 UTC
Labels: Category: Gameplay, Status: Unconfirmed
