### ISSUE TITLE
Detected spam

### ISSUE THREAD

**Issue by KnifeDev** [pmmp/PocketMine-MP#2156] opened 2018-04-25 17:24 UTC
SO reduced this issue because it is **spam** and Fe<sup>2+</sup> oxidized this issue to base64 because it is a 24-hour no-life disrespectful watcher of issues.
Original content: 
```
VGl0bGU6IERldGVjdGVkIHNwYW0KQm9keTogU2VydmVyIHdvcmtpbmcgYW5kIGluIHJhbmRvbSB0
aW1lIHNlcnZlciBmcmVlemVzLCBzZXJ2ZXIgZG9lcyBub3QgcmVzcG9uZCBvbiBjb21tYW5kIGFu
ZCBpIGNhbiBub3QgY29ubmVjdCB0byBzZXJ2ZXIsIF5DIG5vdCB3b3JraW5nLCBpIHJlc3RhcnQg
c2VydmVyIHdpdGgga2lsbCAtOSBbbnVtYmVyLXByb2NjZXNzXSwgaXRzIGhlbHAgbWUgdG8gcmVz
dG9yZSBzZXJ2ZXIuDQoNCioqU3RlcHMgdG8gcmVwcm9kdWNlIHRoaXMgaXNzdWUqKg0KMS5TZXJ2
ZXIgc3RhcnRpbmcNCjIuU2VydmVyIHdvcmtpbmcsIHNlcnZlciBjYW4gd29ya2luZyBhIGxvbmcg
dGltZSBhbmQgaW4gcmFuZG9tIHRpbWUgdGhlIGlzc3VlIHdhcy4NCg0KKipPUyBhbmQgVmVyc2lv
bnMqKg0KDQotIFNlcnZlciBPUzogZGViaWFuIDgNCi0gUEhQIDcuMg0KLSBQTU1QIGxhc3QgcmVs
aWF6ZSwgdGhpcyBpc3N1ZSBjYW4gYXBwZWFyIG9uIG90aGVyIGNvcmVzIHN1Y2ggYXMgR2VuaXN5
c1BybyBvciBvdGhlciBmb3JrcywgaSBoYXZlIDMgc2VydmVycywgdGhpDQoNCioqUGx1Z2lucyoq
DQpUaGlzIGlzIG5vdCBkZXBlbmQgYnkgcGx1Z2lucywgdGhpcyBpc3N1ZSBjYW4gYXBwZWFyIG9u
IGNsZWFuIHNlcnZlcnMgKHdpdGggYW5kIHdpdGhvdXQgcGx1Z2lucykuDQoNCioqQ3Jhc2hkdW1w
cyoqDQpJIGRvbnQgaGF2ZSBhIGNyYXNoZHVtcCwgc2VydmVyIGZyZWV6ZXMsIGNyYXNoZHVtcCBm
b2xkZXIgaXMgZW1wdHksIHRoZSBzZXJ2ZXIgbG9hZCBub3QgaGlnaHQuDQo=

```

**Comment by dktapps** [comment] 2018-04-25 17:26
looks like a duplicate of #1974 to me? please read it and/or clarify, I don't understand what you're saying.

**Comment by KnifeDev** [comment] 2018-04-25 17:29
no, this bug is on unload server, my bug can appear on any moment

**Closed** 2018-04-25 17:35 UTC
Labels: Resolution: Invalid
