### ISSUE TITLE
Packet Error with new Custom Skins

### ISSUE THREAD

**Issue by PocketMiner92** [pmmp/PocketMine-MP#4741] opened 2022-01-19 09:19 UTC
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

Buy a Custom Skins from Minecraft Marketplace dont let you join the Server.

10:11:41.250] [Server thread/ERROR]: [NetworkSession: 109.42.242.97 1909] Bad packet (error ID 9a640f5f9042): Compressed packet batch decode error: Failed to decompress data

[10:11:41.287] [Server thread/INFO]: [NetworkSession: 109.42.242.97 1909] Session closed due to Packet processing error (Error ID: 9a640f5f9042)

[10:11:41.295] [RakLib thread/NOTICE]: Blocked 109.42.242.97 for 5 seconds

### Steps to reproduce the issue
1. Buy a Skin with Custom Geometry
2. Try to Join a Server

### OS and versions

* PocketMine-MP: 4.0.6
* PHP: 8.0.13
* Using JIT: no (delete as appropriate) 
* Server OS: Linux
* Game version: Android

### Plugins
 Multiworld, BetterVanillaGenerator

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins: Yes
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

### Crashdump, backtrace or other files

 

![Screenshot_2022-01-19-10-19-30-75_5c8300b655012b1930f2e0a7b81bf6a9.jpg](https://user-images.githubusercontent.com/96331694/150101025-44b14067-faf3-4e6e-8c76-d5c45780ae1a.jpg)

**Comment by dktapps** [comment] 2022-01-19 11:32
Duplicate of #3733.

**Closed as completed by dktapps** 2022-01-19 11:32 UTC
Labels: Resolution: Duplicate, Category: Client
