### ISSUE TITLE
Lag Fence & Beton

### ISSUE THREAD

**Issue by ErkamKahriman** [pmmp/PocketMine-MP#2886] opened 2019-04-28 10:19 UTC
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?
This bug causes laggs if there is a lot of this

### Steps to reproduce the issue
1. Place Fence
2. and beton above it

Video:
https://www.youtube.com/watch?v=QcUQPtnGjVw

### OS and versions

* PocketMine-MP: 3.8.1
* PHP: 7.2.16
* Server OS: Debian 9
* Game version: PE/Win10 (delete as appropriate)

**Comment by dktapps** [comment] 2019-04-28 10:30
Duplicate of #2449

**Closed by dktapps** 2019-04-28 10:30 UTC
