### ISSUE TITLE
An uncommon Human::spawnTo() crash

### ISSUE THREAD

**Issue by Muqsit** [pmmp/PocketMine-MP#1218] opened 2017-07-19 16:13 UTC
### Issue description

The reason why I added "uncommon" in the title was because this crash was cause multiple times but with more than 15 players online.
The crash is caused because the player is added to Level::$players and Chunk::$entities before Human::initEntity() is called (see [this](https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/entity/Entity.php#L402)). So there's a chance that Player::$inventory is still null.
I do use a custom player class (by calling PlayerCreationEvent::setPlayerClass()), but I've never overwritten Player::spawnTo(). I have overwritten Player::initEntity() but it looks something like this..
```php
protected function initEntity(){
    parent::initEntity();
    //...code
}
```
### Steps to reproduce the issue

1. Keep the server online and keep accepting players.

### OS and versions

* PocketMine-MP: 7c00982
* PHP: 7.0.19
* Server OS: Ubuntu 14.04 LTS
* Game version: Win10 (Happened when a windows 10 user joined, but this field is still irrelevant).

### Plugins
Custom plugins, (see crashdump).

### Crashdump, backtrace or other files

* https://gist.github.com/Muqsit/9bfa899da2e40eb9f237e3b31a222783

**Comment by dktapps** [comment] 2017-07-19 16:17
That's impossible. The code there is executed synchronously, there is no possibility whatsoever that this could occur _between_ those method calls. Something else is at the root of this.

**Comment by dktapps** [comment] 2017-07-19 16:23
There is one other, more likely circumstance when the inventory may be null, which is when the player is closed.

**Comment by Muqsit** [comment] 2017-07-19 18:46
@dktapps Player::sendChunk() loops through Chunk::$entities. There's a possibility of Entity::spawnTo() being called via Player::sendChunk().

**Comment by dktapps** [comment] 2017-07-19 18:53
@Muqsit you're not reading what I'm saying. That cannot happen at the same time as the entity is being constructed.

**Comment by Muqsit** [comment] 2017-07-20 05:33
@dktapps I get what you're saying, therefore my assumption was that there might be a chain of functions (one of which could include spawnTo()) before inventory is declared.

**Comment by matcracker** [comment] 2017-08-10 17:16
I think you should check the item in hand...
`$pk->item = $this->getInventory()->getItemInHand() === null ?? Item:get(Item::AIR)`

**Comment by dktapps** [comment] 2017-10-26 21:29
As far as I can tell, this issue seems to be impossible without external code, so I'm going to close this. If you happen to locate the cause of the issue and it is a PocketMine-MP core issue, feel free to comment and I'll reopen the issue.

**Closed by dktapps** 2017-10-26 21:29 UTC
Labels: Category: Core, Status: Unconfirmed
