### ISSUE TITLE
Craft Error 

### ISSUE THREAD

**Issue by xS91D** [pmmp/PocketMine-MP#5421] opened 2022-11-21 10:36 UTC
### Steps to reproduce the issue
1. Put item to craft table
2. double click item which you want to craft

* PocketMine-MP: 4.10.1
* PHP:
* Using JIT:  no
* Server OS: win
* Game version: Android/iOS

### Plugins
Plugins (1): DevTools v1.15.0

[error.log](https://github.com/pmmp/PocketMine-MP/files/10055700/error.log)

**Comment by dktapps** [comment] 2022-11-21 10:38
Duplicate of #3954

**Closed as completed** 2022-11-21 10:38 UTC
Labels: Resolution: Duplicate, Category: Gameplay, Category: Network
