### ISSUE TITLE
Player crash

### ISSUE THREAD

**Issue by jaylac2000** [pmmp/PocketMine-MP#4304] opened 2021-07-09 20:39 UTC
Link to crashdump: there is not one

### Additional comments (optional)

[20:36:55] [Server thread/CRITICAL]: UnexpectedValueException: "Too many packets in a single batch" (EXCEPTION) in "pmsrc/src/pocketmine/network/mcpe/protocol/BatchPacket" at line 101
[20:36:55] [Server thread/CRITICAL]: #0 pmsrc/src/pocketmine/network/mcpe/protocol/BatchPacket(123): pocketmine\network\mcpe\protocol\BatchPacket->getPackets()
[20:36:55] [Server thread/CRITICAL]: #1 pmsrc/src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(109): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
[20:36:55] [Server thread/CRITICAL]: #2 pmsrc/src/pocketmine/Player(3325): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
[20:36:55] [Server thread/CRITICAL]: #3 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
[20:36:55] [Server thread/CRITICAL]: #4 pmsrc/vendor/pocketmine/raklib/src/server/ServerHandler(95): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[19] 24.74.104.157 63273, object raklib\protocol\EncapsulatedPacket, integer 0)
[20:36:55] [Server thread/CRITICAL]: #5 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
[20:36:55] [Server thread/CRITICAL]: #6 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
[20:36:55] [Server thread/CRITICAL]: #7 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(113): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
[20:36:55] [Server thread/CRITICAL]: #8 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(75): pocketmine\snooze\SleeperHandler->processNotifications()
[20:36:55] [Server thread/CRITICAL]: #9 pmsrc/src/pocketmine/Server(2155): pocketmine\snooze\SleeperHandler->sleepUntil(double 1625863015.5801)
[20:36:55] [Server thread/CRITICAL]: #10 pmsrc/src/pocketmine/Server(1992): pocketmine\Server->tickProcessor()
[20:36:55] [Server thread/CRITICAL]: #11 pmsrc/src/pocketmine/Server(1586): pocketmine\Server->start()
[20:36:55] [Server thread/CRITICAL]: #12 pmsrc/src/pocketmine/PocketMine(291): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[16] /home/container/, string[24] /home/container/plugins/)
[20:36:55] [Server thread/CRITICAL]: #13 pmsrc/src/pocketmine/PocketMine(321): pocketmine\server()
[20:36:55] [Server thread/CRITICAL]: #14 pmsrc(11): require(string[71] phar:///home/container/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

**this player tried to quick craft chests.** 

PMMP: latest
Device: Win10

**Comment by dktapps** [comment] 2021-07-09 21:23
Incomplete issue, but even so, duplicate of #3954.

**Closed by dktapps** 2021-07-09 21:23 UTC
