### ISSUE TITLE
[Server thread/CRITICAL]: ErrorException: "Undefined offset: 0" (EXCEPTION) in "src/pocketmine/Player" at line 2876

### ISSUE THREAD

**Issue by teracube** [pmmp/PocketMine-MP#1235] opened 2017-07-23 16:50 UTC
### Issue description
PocketMine-MP_1.6.2dev-308_f32e8805_API-3.0.0-ALPHA7.phar
An error exception appear when Player joined server or moved wrongly
The player is blocked for 5 second and multiple errors appears

2017-07-23 [18:30:05] [Server thread/WARNING]: Steeve moved wrongly!
2017-07-23 [18:30:20] [Server thread/CRITICAL]: ErrorException: "Undefined offset: 0" (EXCEPTION) in "src/pocketmine/Player" at line 2876
2017-07-23 [18:30:20] [RakLibServer thread/NOTICE]: Blocked 51.249.199.146 for 5 seconds
2017-07-23 [18:30:26] [Server thread/CRITICAL]: ErrorException: "Undefined offset: 0" (EXCEPTION) in "src/pocketmine/Player" at line 2876
2017-07-23 [18:30:26] [Server thread/CRITICAL]: ErrorException: "Undefined offset: 0" (EXCEPTION) in "src/pocketmine/Player" at line 2876
2017-07-23 [18:30:26] [Server thread/CRITICAL]: ErrorException: "Undefined offset: 0" (EXCEPTION) in "src/pocketmine/Player" at line 2876
2017-07-23 [18:30:26] [Server thread/CRITICAL]: ErrorException: "Undefined offset: 0" (EXCEPTION) in "src/pocketmine/Player" at line 2876
2017-07-23 [18:30:26] [RakLibServer thread/NOTICE]: Blocked 41.249.199.146 for 5 seconds

### Steps to reproduce the issue
1. PocketMine-MP_1.6.2dev-308_f32e8805_API-3.0.0-ALPHA7.phar
2. List of installed plugins
PurePerms 1.4.1-dev1; BlockPets 1.1.0; ItemCasePE 1.1.0-dev1; FactionsPro 1.4.4-dev1; SignPortal 1.1.3-dev1; AlwaysSpawn 2.2.3-dev1; Cameraman 1.1.0-dev; TreasureChest 1.2.1; SimpleAuth 1.8.1-dev1; SimpleAuthHelper 2.0.5-dev1; PiggyCustomEnchants 1.0.2; essentialsTP 1.1.1-dev2; ChatToDiscord 1.1.0; Parkour 1.5.3

-->
* PocketMine-MP: PocketMine-MP 1.6.2dev-308
*
### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
Don't know

Thanks

**Comment by dktapps** [comment] 2017-07-23 16:52
Duplicate of #45

**Closed** 2017-07-23 16:52 UTC
