### ISSUE TITLE
the model of the essence of a person disappears during teleportation

### ISSUE THREAD

**Issue by technoboty** [pmmp/PocketMine-MP#5671] opened 2023-04-01 19:34 UTC
### Issue description

- Expected result: entity with custom model
- Actual result: entity with entity model - human

### Steps to reproduce the issue
1. set a custom entity model of the person class
2. teleport entity to 2nd place

### OS and versions

* PocketMine-MP: 4.18.0
* PHP: 8
* Using JIT: No
* Server OS: Linux
* Game version: Android

### Plugins

Casino777 v1.0.0-Alpha, DevTools v1.16.0, FormAPI v1.0.0

- If you remove all plugins, does the issue still occur? - yes (because there is no custom model)
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue? - yes
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
  ```php
  $npc = new Human($loc,$skin);
  $npc->spawnToAll();
  $nps->teleport(0,70,0);

### Crashdump, backtrace or other files
![image](https://user-images.githubusercontent.com/85828163/229310630-49afd8d8-5834-4a38-8754-5c11e9bd8dbf.png)

**Comment by Laith98Dev** [comment] 2023-04-01 20:09
same as [#5510](https://github.com/pmmp/PocketMine-MP/issues/5510)

**Comment by dktapps** [comment] 2023-04-02 08:31
Duplicate of #5510

**Closed as completed by dktapps** 2023-04-02 08:31 UTC
Labels: Resolution: Duplicate, Category: Gameplay, Category: Client
