### ISSUE TITLE
Swings that "don't count" arent being shown

### ISSUE THREAD

**Issue by MINTEDCLICKS** [pmmp/PocketMine-MP#5690] opened 2023-04-10 22:54 UTC
### Issue description

- Expected result: i was expecting that if a player was swinging the animation would play even if they are not hitting anything
- Actual result: only swings that actually result in something will show

### Steps to reproduce the issue
1. join on 2 accounts
2. swing into the air on one account and you will see that they are not shown from the other perspective

### OS and versions

* PocketMine-MP: 4.18.4
* PHP: 8.0.15
* Using JIT: no
* Server OS: linux
* Game version: Win10

### Plugins

the issue occurs regardless of plugins

### Crashdump, backtrace or other files
no crashes

**Comment by dktapps** [comment] 2023-04-11 11:49
This is expected. Animations from the client aren't rebroadcasted anymore, so if there's no action associated with the swing, it won't be seen by other players.

**Comment by dktapps** [comment] 2023-04-11 11:49
Duplicate of #4598

**Closed as completed by dktapps** 2023-04-11 11:49 UTC
Labels: Resolution: Won't fix, Category: Client
