### ISSUE TITLE
Server random crashing with this messages

### ISSUE THREAD

**Issue by KnifeDev** [pmmp/PocketMine-MP#2546] opened 2018-12-02 17:39 UTC
It happens by random. I cannot give steps to reproduce.
Server crashs and dont working.
Server use PMMP last build.
![k9-csaa4rwu](https://user-images.githubusercontent.com/30533957/49342912-10998000-f672-11e8-8702-630c5f90f7be.jpg)

**Comment by dktapps** [comment] 2018-12-02 17:40
Duplicate of #2522

**Closed by dktapps** 2018-12-02 17:40 UTC
