### ISSUE TITLE
Wearing you armor on touch in pocketmine not found

### ISSUE THREAD

**Issue by SuperAdam47** [pmmp/PocketMine-MP#2740] opened 2019-02-06 16:03 UTC
### Steps to reproduce the issue
1.Add support fast armor wearing pocketmine
2.Please 👍 

### OS and versions

* PocketMine-MP: 3.5.6
* PHP: 7
* Server OS: Linux
* Game version: Win10

**Comment by dktapps** [comment] 2019-02-06 16:09
Duplicate of #2641

**Closed by dktapps** 2019-02-06 16:09 UTC
