### ISSUE TITLE
Magma Block doesn't deal damage

### ISSUE THREAD

**Issue by Kjenium** [pmmp/PocketMine-MP#3143] opened 2019-10-09 17:57 UTC
### Issue description

- Expected result: What were you expecting to happen? Magma block should deal damage
- Actual result: What actually happened? It doesn't

### Steps to reproduce the issue
1. ...Just go on a magma block
2. ...

### OS and versions

* PocketMine-MP: 3.9.6
* PHP: I think 7 idk i'm using server.pro rn
* Server OS: same
* Game version: PE/Win10 (delete as appropriate)

### Plugins

- If you remove all plugins, does the issue still occur?
Yes
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by dktapps** [comment] 2019-10-09 18:34
duplicate of #2041

**Closed by dktapps** 2019-10-09 18:34 UTC
