### ISSUE TITLE
PlayerItemUseEvent works once until you switch the slot (air clicking)

### ISSUE THREAD

**Issue by Frago9876543210** [pmmp/PocketMine-MP#3648] opened 2020-06-28 08:58 UTC
### Issue description

When you make air click on some item, it works once and after event does fire because that code blocks it:
https://github.com/pmmp/PocketMine-MP/blob/2104b2d32b45f4b628c05a186d12e2d17f9968bd/src/network/mcpe/handler/InGamePacketHandler.php#L333-L338
Workaround is only switch slot and back to this item.

### Steps to reproduce the issue
1. Join to server and get compass
2. Make one __air click__ (this is important!) and make sure the event is working
3. Repeat step 2 to see problem

### OS and versions
* PocketMine-MP: 2104b2d32b45f4b628c05a186d12e2d17f9968bd
* PHP: PHP 7.3.13
* Server OS: Ubuntu 18.04 LTS

### Plugins
Minimal code
```php
<?php

/**
 * @name Example
 * @main Example
 * @api 4.0.0
 * @version 1.0.0
 */

declare(strict_types=1);

use pocketmine\event\Listener;
use pocketmine\event\player\PlayerItemUseEvent;
use pocketmine\item\Compass;
use pocketmine\plugin\PluginBase;

class Example extends PluginBase implements Listener{

	protected function onEnable() : void{
		$this->getServer()->getPluginManager()->registerEvents($this, $this);
	}

	public function onUseItem(PlayerItemUseEvent $e) : void{
		$item = $e->getItem();
		if($item instanceof Compass){
			$e->getPlayer()->sendMessage(__FUNCTION__);
		}
	}
}
```

**Comment by Frago9876543210** [comment] 2020-06-28 09:08
The real problem happens here:
https://github.com/pmmp/PocketMine-MP/blob/2104b2d32b45f4b628c05a186d12e2d17f9968bd/src/player/Player.php#L1479-L1480
It sets `startAction` to current server tick and then `isUsingItem` will always return false

https://github.com/pmmp/PocketMine-MP/blob/2104b2d32b45f4b628c05a186d12e2d17f9968bd/src/network/mcpe/handler/InGamePacketHandler.php#L333-L338

**Comment by dktapps** [comment] 2020-06-28 10:10
duplicate of #3301

**Closed by dktapps** 2020-06-28 10:10 UTC
