### ISSUE TITLE
Player->close() is not working properly.

### ISSUE THREAD

**Issue by xxFlare** [pmmp/PocketMine-MP#1060] opened 2017-06-10 16:01 UTC
### Issue description
This issue happens on vanilla servers with no plugins.

It is already well known that the close function has a lot of issues, but this issue is "new" (I found it weeks ago, but only got it again yesterday).

Sometimes, when the server kicks a player he is not actually being removed from the $players array in the server class.

Here is what I mean:
<img width="1044" alt="screen shot 2017-06-09 at 4 51 27 pm" src="https://user-images.githubusercontent.com/10011687/27004215-8b35c2fe-4dd3-11e7-9681-626701728cd3.png">

On my consoles title, you can see it says three players connected, but when you run /list only two show up (which is correct).

/list seems to only log players which are considered online, while the console player count simply counts() the players array. This points out a huge issue... and a possible memory leak.

I can't seem to reproduce this bug a lot. It happens when someone gets kicked, possibly during the login process (you can see someone got kicked from whitelist, and that is when this happened)

### Steps to reproduce the issue
It's hard to reproduce because it happens randomly, bad timing issue?
1. Kick player (possibly during login process?)
2. Look at consoles player count and /list

### OS and versions
* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/1aae9e03b6c41916d73a5eebb19f84e2f9d7b88d
* PHP: 7
* Server OS: Mac

### Plugins
I reproduced it without any plugins.

**Comment by Misteboss** [comment] 2017-06-10 22:34
Same issue as mine and the issue of Muqsit, Disconnect Packet doesn’t work.

**Comment by xxFlare** [comment] 2017-06-10 23:08
@Misteboss 
> When PlayerLoginEvent gets cancelled, PlayerLoginEvent::getPlayer() would not get the kick message and will have to wait for "Building Terrain" to change to "Disconnected from Server". PlayerPreLoginEvent, on the other hand, when cancelled, is guaranteed to show PlayerPreLoginEvent::getKickMessage().

Wrong. This issue has nothing to do with disconnection messages.

**Comment by MattWAnderson** [comment] 2017-06-11 03:13
This issue is likely what I was running into for kicking un-authed players. I reverted my code back to kicking rather than closing due to it not working correctly. Will need more debug, but that is my 2 cents.

**Comment by dktapps** [comment] 2017-06-11 09:42
- Is the extra player in the title count persistent or does it disappear after leaving the server for some time?
- Do you have resource packs on the server?

**Comment by dktapps** [comment] 2017-06-11 09:45
In the process of testing this issue I also discovered a crash which occurs when using /list when no players are online. Yippee.

**Comment by matcracker** [comment] 2017-06-11 22:52
This happens also when player starts to transfer in another server. See #497

**Comment by xxFlare** [comment] 2017-06-11 23:07
@dktapps No, I don't use texture packs. Unless I restart the server, the extra player will stay on forever.

PocketMine used to just call remove player without a connection check, though that seems rather hack.

**Comment by ImagicalGamer** [comment] 2017-06-15 18:54
Player::close() not $this->close() to make the title more precise, this is only happening (for me) if a player timeouts from the server.

**Comment by dktapps** [comment] 2017-06-19 12:39
Could you retest with the referenced commit?

**Comment by xxFlare** [comment] 2017-06-24 02:13
@dktapps Nothing new happening with referenced commit.

Also... I'm not so sure if this pertains to this issue, but it seems like PocketMine is leaking player objects. I set up a server that just transfers players, no gameplay whatsoever, and after a hour this was the result:
<img width="1092" alt="terminal" src="https://user-images.githubusercontent.com/10011687/27504826-ec6fe54a-585f-11e7-9838-20c146f0e9a4.png">


On the flip side, a easy way to reproduce this issue and the memory leak is to just transfer players until it the count is not the same as what console says. (Note: If the player is transferred the extra player on console seems to go away after awhile, but if this bug happens during a whitelist kick or timeout, the extra player does not go away)

**Comment by dktapps** [comment] 2017-07-04 09:53
@xxFlare next time you reproduce this, could you perform a memory dump and upload the results somewhere? Thanks.

**Closed** 2017-09-01 19:05 UTC
Labels: Category: Core, Status: Awaiting Response, Status: Unconfirmed
