### ISSUE TITLE
Movement-check bugs

### ISSUE THREAD

**Issue by VlaD3n** [pmmp/PocketMine-MP#119] opened 2016-11-22 11:29 UTC
### Issue description

Hello issue with PM 0.16.X
I found a mistake when you're trying to climb the rungs writes "* player * moved wrongly !!" the console and starts to shake Player

### Steps to reproduce the issue

1. Trying to get up the stairs
2. If there is a shake, but now look at the console

### OS and versions

* PocketMine-MP: 0.16.0.5 1.6.1dev-#82
* PHP: 7
* Server OS: Debian 7
* Game version: PE

### Crashdump, backtrace or other files

* ...

**Comment by iTCMega** [comment] 2016-11-23 06:52
its **_work fine_** at the console! and no **shake** ! :100:  :+1:

**Comment by VlaD3n** [comment] 2016-11-23 11:39
What? My friend tested it on my server is the core and he said that when the stairs climbed, it started to shake! While it may be under the stairs, he meant a ladder ...

**Comment by legoboy0215** [comment] 2016-11-25 08:56
The "{player} moved wrongly" is back again?

**Comment by dktapps** [comment] 2016-11-25 08:58
It was never gone, only in Genisys the anti cheat code responsible was simply commented out.

**Comment by legoboy0215** [comment] 2016-11-25 09:14
I noticed that.

**Comment by daterrell** [comment] 2016-11-25 18:07
I have also reproduced this, but you _must_ be in gamemode 0 (survival).  The default game mode can be either, but the player climbing the stairs must be in survival.  It also helps to run up the stairs instead of walking.

**Comment by dktapps** [comment] 2016-12-04 19:31
Also reproduced when walking through doors.

**Comment by dktapps** [comment] 2016-12-15 16:21
Door bounding boxes are off, by 0.005 of a block (3/15 in vanilla, 3/16 in PocketMine). Mega facedesk Mojang.

**Comment by dktapps** [comment] 2016-12-15 18:41
https://bugs.mojang.com/browse/MCPE-19214

**Comment by dktapps** [comment] 2016-12-29 01:06
Relates to #169

**Comment by dktapps** [comment] 2017-01-20 11:20
Most everything here should been have been fixed in #259, with the exception of stairs (and possibly doors, but that is a Mojang issue). Since stairs are due to wrong bounding boxes server-side, I'm going to close this with reference to #169.

**Closed by dktapps** 2017-01-20 11:20 UTC
Labels: Category: Gameplay, Status: Reproduced
