### ISSUE TITLE
Fake login

### ISSUE THREAD

**Issue by MrReskill** [pmmp/PocketMine-MP#2075] opened 2018-03-04 14:38 UTC
# «Fake Login»
### When I join the server, it indicates in the console that I am connected but on the game I am on the loading screen and those on more than 20 minutes before being disconnected. I have tried several times to reconnect etc and it still does not work ... I have access to other servers!

Expected result: That my player connects normally
Actual result: My player does not connect

PocketMine-MP: MASTER 49a39fc

PHP: 7.2

Server OS: VPS LINUX Debian 9.1

Game version: Win10 1.2.10

Plugins:
     - Devtools
Crashdumps:
     - 0 cd

=> The bug appears when I try to connect, I have no other results

**Comment by dktapps** [comment] 2018-03-04 14:50
Duplicate of #1933

**Closed by dktapps** 2018-03-04 14:50 UTC

**Comment by MrReskill** [comment] 2018-03-04 18:15
# It does not help me, what you indicate on the ticket does not work for me!  @dktapps

**Comment by robske110** [comment] 2018-03-04 19:19
@MrReskill please continue this on the https://forums.pmmp.io forums.
