### ISSUE TITLE
Fix the QueryRegenerateEvent !?

### ISSUE THREAD

**Issue by Pab450** [pmmp/PocketMine-MP#350] opened 2017-02-11 23:43 UTC
### Issue description

 The "QueryRegenerateEvent" in Pocketmine is now break ! setTimeout(), setMaxPlayerCount() and more is break.

### Steps to reproduce the issue

public function Query(QueryRegenerateEvent $event){
$event->setTimeout(10);//No change, why ?
$event->setMaxPlayerCount(30); //No change, why ?
}

### OS and versions

* PocketMine-MP: 1.6.2 dev api 3.0.0-ALPHA3
* PHP: php7
* Server OS: Mac OSX 
* Game version: Mcpe v1.0.3.0

### Crashdump, backtrace or other files
* ...

**Comment by dktapps** [comment] 2017-02-12 09:44
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)

**Comment by Pab450** [comment] 2017-02-12 10:15
Up

**Comment by Pab450** [comment] 2017-02-18 16:27
I think the "QueryRegenerateEvent" event can read the requested information, but can't change the informations..

**Comment by robske110** [comment] 2017-02-19 06:33
Invalid issue. This does work. 
[Query.php.zip](https://github.com/pmmp/PocketMine-MP/files/785626/Query.php.zip) I used that for testing. After the first call to the query event http://robskebueba.no-ip.biz/BannerForMCPE/MainCode(PHP)/banner1.php?host=robskebueba.no-ip.biz&port=6452 does show 0/2000 instead of 0/5. Did you register events in your plugin? Is your plugin loaded?

**Comment by dktapps** [comment] 2017-02-19 10:19
Closing due to not reproducible.

**Closed** 2017-02-19 10:20 UTC
Labels: Category: Plugin API, Status: Unconfirmed

**Comment by dktapps** [comment] 2019-03-24 18:08
This bug is fixed in the latest master branch commits and will work correctly in 4.0.
