### ISSUE TITLE
Error Crafting

### ISSUE THREAD

**Issue by sc00scoc** [pmmp/PocketMine-MP#1217] opened 2017-07-19 11:40 UTC
[13:40:12] [Server thread/CRITICAL]: ErrorException: "Undefined offset: 0" (EXCEPTION) in "src/pocketmine/Player" at line 3030
[13:40:12] [RakLibServer thread/NOTICE]: Blocked 5.94.40.198 for 5 seconds
Dont Craft from win10 last pmmp version

**Comment by dktapps** [comment] 2017-07-19 11:41
I'm going to ban the next person makes a duplicate report about this.

Duplicate of #45

**Closed by dktapps** 2017-07-19 11:41 UTC
