### ISSUE TITLE
Client crash when join

### ISSUE THREAD

**Issue by diamond-gold** [pmmp/PocketMine-MP#2573] opened 2018-12-15 07:21 UTC
### Issue description

Client 1.8.0 crashes after joining

- Expected result: Normal Join
- Actual result: Client crash

### Steps to reproduce the issue

1. fresh download c5262fd
2. client join

### OS and versions

* PocketMine-MP: This server is running PocketMine-MP 4.0.0+dev for Minecraft: Bedrock Edition v1.8.0 (protocol version 313)
git commit hash c5262fd
* PHP: 7.2.8
* Server OS: Windows 8.1
* Game version: PE 1.8.0

### Plugins
- Test on a clean server without plugins: Tested, still crashes

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here
Nothing shown in console, player logged out due to timeout

**Comment by dktapps** [comment] 2018-12-15 08:44
I tested that build yesterday and had no such issues. Please provide more information.

**Comment by dktapps** [comment] 2018-12-15 14:01
Closing due to not reproducible with the given information.

**Closed by dktapps** 2018-12-15 14:01 UTC
Labels: Category: Client (all), Resolution: Cannot Reproduce

**Comment by zKoz210** [comment] 2018-12-16 15:06
Reproduced, by my assumptions outdated runtime table with blocks

**Comment by dktapps** [comment] 2018-12-16 15:09
> not reproducible **with the given information**.

Without additional information I can't reproduce this, so it'll remain closed until I can. I have yet to encounter any joining crash in 1.8 across many joins.

**Comment by zKoz210** [comment] 2018-12-16 15:11
https://yadi.sk/i/ObxbjSti-3F73w

**Comment by JackMD** [comment] 2018-12-16 15:14
@zKoz210 that alone looks cool 😂

**Comment by dktapps** [comment] 2018-12-16 15:16
I cannot reproduce that either. You'll have to do better than that.
