### ISSUE TITLE
Console window does not close

### ISSUE THREAD

**Issue by Mathshyun** [pmmp/PocketMine-MP#91] opened 2016-11-08 08:14 UTC
### Issue description

When I enter "stop" in console,
plugins were disabled but console window wasn't closed 

### Steps to reproduce the issue

1. run start.cmd
2. when server is on, enter "stop"

### OS and versions

* PocketMine-MP: 1.6.1 dev
* PHP: 2.1.0
* Server OS: Windows
* Game version: PE

### Crashdump, backtrace or other files

* ...

![20161108_171354](https://cloud.githubusercontent.com/assets/20264947/20091558/c3880810-a5d6-11e6-8a46-d8710ba4774c.png)

**Comment by SOF3** [comment] 2016-11-08 08:15
Duplicate of #25

**Closed by SOF3** 2016-11-08 08:15 UTC

**Comment by TheDeibo** [comment] 2016-11-08 10:46
I will look into this. I know it doesn't close. That's because the PHP.exe has stopped, not MINTTY, or CMD.

I could add a function where it doesn't detect server, it will close down. I've done quite a few messing around with the Start.CMD lately, so this is now on my list.

**Comment by SOF3** [comment] 2016-11-08 10:48
Please discuss about this issue in #25. This is a **duplicate**. All discussion for this issue should be directed to #25.
