### ISSUE TITLE
Player quit issue - Player::getDisplayName()

### ISSUE THREAD

**Issue by gizanopatrica** [pmmp/PocketMine-MP#1221] opened 2017-07-20 07:33 UTC
### Issue description
Sometimes, when a player quits, the server crashes because it can't get the players name

### Steps to reproduce the issue
1. Start your server and let players join
2. Wait for a player to quit the server
3. Check the server log for an error

### OS and versions
* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/cca9cf2c8683fe14c3698d8da52bfd45a2febb8d
* PHP: 7.02
* Server OS: Linux
* Game version: PE

### Plugins
Reproducible on a server without plugins.

### Crashdump, backtrace or other files
```
[03:22:51] [Server thread/CRITICAL] TypeError: "Return value of pocketmine\Player::getDisplayName() must be of the type string, null returned" (EXCEPTION) in "src/pocketmine/Player" at line 694
[03:22:51] [Server thread/DEBUG] #0 src/pocketmine/Player(303): pocketmine\Player->getDisplayName()
[03:22:51] [Server thread/DEBUG] #1 src/pocketmine/network/mcpe/RakLibInterface(101): pocketmine\Player->getLeaveMessage()
[03:22:51] [Server thread/DEBUG] #2 src/raklib/server/ServerHandler(124): pocketmine\network\mcpe\RakLibInterface->closeSession(string 139.193.44.34:47616, string timeout)
[03:22:51] [Server thread/DEBUG] #3 src/pocketmine/network/mcpe/RakLibInterface(80): raklib\server\ServerHandler->handlePacket()
[03:22:51] [Server thread/DEBUG] #4 src/pocketmine/network/Network(86): pocketmine\network\mcpe\RakLibInterface->process()
[03:22:51] [Server thread/DEBUG] #5 src/pocketmine/Server(2469): pocketmine\network\Network->processInterfaces()
[03:22:51] [Server thread/DEBUG] #6 src/pocketmine/Server(2243): pocketmine\Server->tick()
[03:22:51] [Server thread/DEBUG] #7 src/pocketmine/Server(2122): pocketmine\Server->tickProcessor()
[03:22:51] [Server thread/DEBUG] #8 src/pocketmine/Server(1704): pocketmine\Server->start()
[03:22:51] [Server thread/DEBUG] #9 src/pocketmine/PocketMine(511): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar:///custom-phar.phar/, string /, string /plugins/)
[03:22:51] [Server thread/DEBUG] #10 /custom-phar.phar(1): require_once(string phar:///custom-phar.phar/src/pocketmine/PocketMine.php)
[03:22:51] [Server thread/CRITICAL] [Network] Stopped interface pocketmine\network\mcpe\RakLibInterface due to Return value of pocketmine\Player::getDisplayName() must be of the type string, null returned
```

**Comment by TheDiamondYT1** [comment] 2017-07-20 07:34
You just created 2 issues for the same thing....

Player extends Human so should be the same problem

**Comment by dktapps** [comment] 2017-07-20 07:41
Same root cause as #1220 . I'm going to close this in favour of that in order to not spam the issue tracker.

**Closed by dktapps** 2017-07-20 07:41 UTC
