### ISSUE TITLE
File is still locked after unloading the world

### ISSUE THREAD

**Issue by Nerahikada** [pmmp/PocketMine-MP#4487] opened 2021-10-04 05:06 UTC
### Issue description
On Windows, the `LOG` file is still locked even after unloading the world.

### Steps to reproduce the issue
1. Unload the world

### OS and versions
* PocketMine-MP: 4.0.0-BETA3
* PHP: 8.0.11
* Using JIT: no
* Server OS: Windows

### Plugins
It requires a plugin to reproduce.
```php
protected function onEnable() : void{
	$this->getServer()->getWorldManager()->loadWorld("world");
	$this->getScheduler()->scheduleDelayedTask(new ClosureTask(function() : void{
		$manager = $this->getServer()->getWorldManager();
		$manager->unloadWorld($manager->getWorldByName("world"));
	}), 20);
}
```

**Comment by dktapps** [comment] 2021-10-08 22:43
I'm not able to reproduce this.

**Comment by dktapps** [comment] 2021-10-08 23:17
It looks like this has something to do with the CLI subprocess. The parent process releases the locks correctly, but if the world was loaded before CommandReader started, the subprocess inherits those locks and keeps them alive.

**Comment by dktapps** [comment] 2021-10-09 15:32
Fixed by https://github.com/pmmp/leveldb/commit/1c7564468b41610da4f498430e795ca4de0931ff (upstream PR https://github.com/google/leveldb/pull/941).

**Closed by dktapps** 2021-10-09 15:32 UTC
Labels: Category: Core, Status: Debugged
