### ISSUE TITLE
Cobblestone generator stops after server restart

### ISSUE THREAD

**Issue by Erkam246** [pmmp/PocketMine-MP#3273] opened 2020-01-09 01:34 UTC
### Issue description
Cobblestone generator doesn't creates cobblestone

### Steps to reproduce the issue
Build an Cobblestone generator

### OS and versions

* PocketMine-MP: 3.11.3
* PHP: 7.3.11
* Server OS: Debian 10

**Comment by dktapps** [comment] 2020-01-09 08:54
duplicate of #2912 , #2943 , #2099

**Closed by dktapps** 2020-01-09 08:54 UTC
