### ISSUE TITLE
internal server error

### ISSUE THREAD

**Issue by Danding1314** [pmmp/PocketMine-MP#2579] opened 2018-12-15 15:01 UTC
* PocketMine-MP: 3.5.1
* PHP: 7.2
* Server OS: 1.8
* Game version: PE/Win10 

when people use some command
the server send internal server error....
even through the server will crash...
oops.... i think it's not my plugins question
i hope the error can be fixed..
thank !

**Comment by dktapps** [comment] 2018-12-15 15:05
Closing due to insufficient information provided to reproduce.

**Closed by dktapps** 2018-12-15 15:05 UTC
