### ISSUE TITLE
!spam

### ISSUE THREAD

**Issue by and7ey** [pmmp/PocketMine-MP#4068] opened 2021-03-12 18:06 UTC
SO reduced this issue because it is **spam** and Fe<sup>2+</sup> oxidized this issue to base64 because it is a 24-hour no-life disrespectful watcher of issues.
Original content: 
```
VGl0bGU6ICFzcGFtCkJvZHk6IA0KKiBQb2NrZXRNaW5lLU1QOiAzLjE3LjcNCiogR2FtZSB2ZXJz
aW9uOiBQRSwgaU9TIE1pbmVjcmFmdCAxLjE2LjIxMA0KDQpXaGVuIHRyeWluZyB0byBjb25uZWN0
IGZyb20gaVBhZCwgZ2V0dGluZyAiT3V0ZGF0ZWQgc2VydmVyIiBlcnJvcg==

```

**Comment by ZizzyZizzy** [comment] 2021-03-12 18:13
@and7ey 

1. This is not a bug report.
2. You completely ignored the pre-filled form that was provided.
3. Quit being selfish and wasting developers time on something that is clearly not a bug report
4. The devs will release the new version when it's ready. Bugging them about it only slows them down because they have to answer every single impatient person begging for an update.

Close this now please.

**Closed** 2021-03-12 18:49 UTC
Labels: Auto: Spam
