### ISSUE TITLE
Login timeout

### ISSUE THREAD

**Issue by Gaprix** [pmmp/PocketMine-MP#4607] opened 2021-11-30 19:39 UTC
### Steps to reproduce the issue
1. Join the server
2. Login timeout

### OS and versions
Server version: 4.0.0-BETA15 (git hash: d560cf17fc2496161c375324ec3fb52f17057c25)
Compatible Minecraft version: 1.18.0 (protocol version: 475)
PHP version: 8.0.12
PHP JIT: disabled
Operating system: win

### Plugins
none

### Crashdump, backtrace or other files
![изображение](https://user-images.githubusercontent.com/45711510/144116005-7d96135c-34fc-4700-9b60-8cea73d14d28.png)

**Comment by dktapps** [comment] 2021-11-30 19:41
Duplicate of #3733.

**Closed by dktapps** 2021-11-30 19:41 UTC
