### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by WinneRose** [pmmp/PocketMine-MP#3477] opened 2020-05-09 22:21 UTC
Error: "Call to a member function getSize() on array" (EXCEPTION) in "src/pocketmine/item/enchantment/Enchantment" at line 154

I get error every plugin in lasest pocketmine phar

**Comment by dktapps** [comment] 2020-05-09 22:43
duplicate of #3400, you're using a plugin that's doing something it shouldn't using reflection

**Closed by dktapps** 2020-05-09 22:43 UTC
