### ISSUE TITLE
Vanilla features don't work

### ISSUE THREAD

**Issue by daniktheboss** [pmmp/PocketMine-MP#902] opened 2017-05-09 03:43 UTC
Hello, my name is Daniil, also known as daniktheboss. I was recently using pmmp and i noticed some vanilla features don't work. 

Some features are listed below:
Spawner's (you cant give /give daniktheboss 52:20)
Farm's (you cant make auto farm grinder)

Thanks for reading this

**Comment by thebigsmileXD** [comment] 2017-05-09 05:19
- Follow the template
 - Search issues : Basically everything here: https://github.com/pmmp/PocketMine-MP/issues  and 25% here: https://github.com/pmmp/PocketMine-MP/issues?q=is%3Aissue+is%3Aclosed
 - Use plugins. For spawners i know you have a plugin that adds them to the blocks array. (aka SimpleSpawner)

**Comment by daniktheboss** [comment] 2017-05-09 05:38
- Plugins shouldn't be doing this
- This isn't really a issue, this is a more like a feature add on

**Comment by thebigsmileXD** [comment] 2017-05-09 05:54
I claim it a duplicate of https://github.com/pmmp/PocketMine-MP/issues/900. 

> Not implemented or known issues:
> Please do not report lacking features to the bug tracker, only report bugs on implemented features.
> 
> Entities / Entity AI
> No conversion for old levels (will be added later)
> No Minecarts
> Not all items are implemented
> Generated worlds use a basic generator
> Also:
> 
> pmmp/PocketMine are not affiliated with Mojang. PocketMine-MP is not a Mojang-approved software, nor is it associated with Mojang.

**Comment by daniktheboss** [comment] 2017-05-09 05:56
This is bug in the feature. And a feature that should be a prioritie

**Comment by thebigsmileXD** [comment] 2017-05-09 06:01
> This isn't really a issue, this is a more like a feature add on

**Comment by daniktheboss** [comment] 2017-05-09 06:03
Feature add on. The feature is there but needs fixing. If you have nothing else to say but to argue stop commenting

**Comment by dktapps** [comment] 2017-05-09 07:32
This is not a bug report, merely a request of things not yet implemented. Entities as a whole and most things related to them do not function yet due to lack of implementation. This is a work in progress, please be patient. You can't farm mobs effectively without mob AI, mob spawning and experience.

Do also be aware that mob spawners with damage values are a popular myth and do not actually spawn the entity with that ID. The spawned entity is a result of the spawner's NBT, not its block damage.

**Closed by dktapps** 2017-05-09 07:32 UTC

**Comment by daniktheboss** [comment] 2017-05-09 22:58
Ok thanks, and take a look at farms too

**Comment by thebigsmileXD** [comment] 2017-05-10 14:01
Maybe he means wheat/potato random ticking.

**Comment by jasonwynn10** [comment] 2017-05-10 14:02
I have a branch on my fork with an attempted fix for farms
