### ISSUE TITLE
Lava sometimes stops flowing

### ISSUE THREAD

**Issue by RedCraftGH** [pmmp/PocketMine-MP#2943] opened 2019-05-31 00:33 UTC
### Issue description

- Expected result: When I create a cobblestone generator, I expect the lava to flow into the water.
- Actual result: Sometimes, the lava gets "stuck" and doesn't flow at all, breaking the cobblestone generator.

### Steps to reproduce the issue
1. Create a basic cobblestone generator.
2. Mine the cobblestone until the lava stops flowing.

### OS and versions

* PocketMine-MP: 3.8.3
* PHP: 7.1.29
* Server OS: Windows
* Game version: Win10

### Plugins

Plugins (0):
- If you remove all plugins, does the issue still occur?
Yes.

No crash or error in console.

**Comment by dktapps** [comment] 2019-05-31 07:02
duplicate of #2912

**Closed by dktapps** 2019-05-31 07:02 UTC
