### ISSUE TITLE
[api3/network] Transfer method closes/disconnects player to early

### ISSUE THREAD

**Issue by SleepSpace9** [pmmp/PocketMine-MP#497] opened 2017-03-31 21:47 UTC
### Issue description
The method ```$playert->transfer(...) ``` is closing the player after sending the TransferPacket.
In most of my attempts the Transfer did not work because the TransferPacket never reached my client (confirmed by Wireshark) and I have only been disconnected from the server.
After I removed the line ```$this->close("", $ev->getMessage(), false);``` it worked at all of my attempts (same when I'm using a plugin which sends the TransferPacket and is not closing the player).

Maybe this timing issue does not affect all servers, but I think in my case the client is disconnected to early.
And I also think the close() is not needed because the client will disconnect the server session when the TransferPacket has reached. The only downside is that the disconnect reason would then be "logged out due to **client disconnect**" and not "logged out due to **transfer**".

Because the built-in **/transferserver** command is also using this method it can be used for testing.

_Expected result_: Client is disconnected from the server and then automatically connected to the new server.
_Actual result_: Client is only disconnected.

### Steps to reproduce the issue
1. use **/transferserver** _\<servername or IP\>_ _\<port\>_
2. be suprised if connection gets lost
(probably not in every environment, otherwise I would not be the first one who complaints about it)

### OS and versions
PocketMine-MP 1.6.2dev 「Unleashed」 implementing API version 3.0.0-ALPHA5 for Minecraft: PE v1.0.5.0 beta (protocol version 105)
* PocketMine-MP: branch 'api3/network' (I guess also other branches) - commit 845b124 
* PHP: PHP 7.0.17
* Server OS: Ubuntu 14.04.5 LTS
* Game version: PE/Win10 (tested on Android and Win10)

### Crashdump, backtrace or other files

* _none_

**Comment by jojoe77777** [comment] 2017-03-31 22:27
This literally always happened to me when I was sending TransferPacket and then using $player->close() or $player->kick(). 

> And I also think the close() is not needed because the client will disconnect the server session when the TransferPacket has reached.

What about mods that ignore TransferPackets?

**Comment by SleepSpace9** [comment] 2017-03-31 22:39
Oh mods - good point! And yes, a delayed task to kick the transfered player would probably help. I was hoping that a needed delay could be implemented into the server or that dktapps has another magical solution.

**Comment by madecode15** [comment] 2017-04-01 00:43
@SleepSpace9 @jojoe77777 

PocketMine-MP is single threaded, code should run and synchronize one line at a time. This seems to be a timing issue with packets being sent... PocketMine's RakLib library has actually a ton of problems with packets, just last summer dktapps fixed a bug where client disconnect messages would not show up most of the time.

By scheduling the close function, that is just a hack not a solution. The whole RakLib library needs a re-write though that is not a priority right now and dktapps is very busy with re-writing network handling. This issue is actually abstractly related to #465, which is a critical issue.

**Comment by jasonwynn10** [comment] 2017-04-01 02:05
That would be on the "rewrite-crap" branch of RakLib

**Comment by Guillaume351** [comment] 2017-04-01 07:49
Why do there need to be a close after the transfer ? The client sends back a disconnect packet after beeing transfered, no ?

**Comment by dktapps** [comment] 2017-04-01 09:01
@Guillaume351 read comments higher up before repeating the same questions.

As I recall, a similar issue occurred with regular disconnects not so long ago with RakNet disconnects reaching the client before the MCPE-layer DisconnectPacket, causing disconnect messages to not be shown.

@madecode15 it was @svilex , not me :P why do I get the credit for the weird bug fixes?

**Comment by dktapps** [comment] 2017-04-01 09:41
Could someone test the referenced commit? I cannot reproduce this issue on LAN.

**Comment by AppleDevelops** [comment] 2017-04-01 14:28
Unable to reproduce on latest commit

**Comment by jasonwynn10** [comment] 2017-04-01 14:41
Works for me 👍

**Comment by dktapps** [comment] 2017-04-01 14:43
Closing as Fixed, if the issue occurs again let me know.

**Closed by dktapps** 2017-04-01 14:43 UTC
Labels: Category: Gameplay, Category: Network, Resolution: Awaiting Response

**Comment by SleepSpace9** [comment] 2017-04-01 14:55
Yes - unable to reproduce after latest commit!  :tada:

**Big thanks dktapps!**

**Comment by matcracker** [comment] 2017-05-17 17:22
@dktapps you should read that [post](https://forums.pmmp.io/threads/playertransferevent-dont-transfer-more-players.2299/#post-24346) on the forum.

**Comment by thebigsmileXD** [comment] 2017-05-17 19:21
I stated that out after you added the close line, do you remember this? ;) @dktapps

**Comment by intagaming** [comment] 2017-06-07 08:18
Sometimes it works (I can confirm this, just did once), sometimes it doesn't. Please reproduce few times more with remote server, not the local one. Results may vary.
![image](https://user-images.githubusercontent.com/16471365/26868805-69c13a90-4b94-11e7-95e1-4d5ba992d156.png)
![image](https://user-images.githubusercontent.com/16471365/26868823-744e2b4e-4b94-11e7-8a00-029f6d221406.png)

**Comment by thebigsmileXD** [comment] 2017-06-07 09:52
I get the issue with closing too, when the transfer packet doesnt come to the client. Happens when the server has a short lag/peak, or the client has a really bad ping. Though this happens with all packets.
