### ISSUE TITLE
 TextFormat::OBFUSCATED Not working

### ISSUE THREAD

**Issue by ShushImSam** [pmmp/PocketMine-MP#3060] opened 2019-07-27 19:16 UTC
SO reduced this issue because it is **spam** and Fe<sup>2+</sup> oxidized this issue to base64 because it is a 24-hour no-life disrespectful watcher of issues.
Original content: 
```
VGl0bGU6IFRleHRGb3JtYXQ6Ok9CRlVTQ0FURUQgTm90IHdvcmtpbmcKQm9keTogIyMjIElzc3Vl
IGRlc2NyaXB0aW9uDQoNCi0gRXhwZWN0ZWQgcmVzdWx0OiBJIHdhcyBleHBlY3RlZCB0aGUgdGV4
dCBpbmdhbWUgdG8gYmVjb21lIE9CRlVTQ0FURUQuDQotIEFjdHVhbCByZXN1bHQ6IGl0IHN0YXlz
IHRoZSBsZXR0ZXIocykgd3JpdHRlbg0KDQojIyMgU3RlcHMgdG8gcmVwcm9kdWNlIHRoZSBpc3N1
ZQ0KMS4gYCAkc2VuZGVyLT5nZXRTZXJ2ZXIoKS0+YnJvYWRjYXN0TWVzc2FnZShUZXh0Rm9ybWF0
OjpPQkZVU0NBVEVEICAuICJpIik7YA0Kb3IgDQoyLiBJbiBjaGF0IGRvIMKna0JhZHNhDQoNCg0K
DQojIyMgT1MgYW5kIHZlcnNpb25zDQo8IS0tIHRyeSB0aGUgYHZlcnNpb25gIGNvbW1hbmQgfCBM
QVRFU1QgSVMgTk9UIEEgVkFMSUQgVkVSU0lPTiAtLT4NCiogUG9ja2V0TWluZS1NUDogMy45LjIr
ZGV2DQoqIFBIUDogNy4zDQoqIFNlcnZlciBPUzogV2luZG93czEwDQoqIEdhbWUgdmVyc2lvbjog
V2luMTAgDQoNCiMjIyBQbHVnaW5zDQo8IS0tLSB1c2UgdGhlIGBwbHVnaW5zYCBjb21tYW5kIGFu
ZCBwYXN0ZSB0aGUgb3V0cHV0IGJlbG93IC0tPg0KDQotIElmIHlvdSByZW1vdmUgYWxsIHBsdWdp
bnMsIGRvZXMgdGhlIGlzc3VlIHN0aWxsIG9jY3VyPw0KWWVzDQojIyMgQ3Jhc2hkdW1wLCBiYWNr
dHJhY2Ugb3Igb3RoZXIgZmlsZXMNCjwhLS0tIFVzZSBnaXN0IG9yIGFueXRoaW5nIGVsc2UgdG8g
YWRkIG90aGVyIGZpbGVzIGFuZCBhZGQgbGlua3MgaGVyZSAtLT4NCmh0dHBzOi8vZ2lzdC5naXRo
dWIuY29tL1NodXNoSW1TYW0vZWQwNjQ3NzBjMGNhNTZlY2ZlMDFmZGUzYTE3NmFlNDQ=

```

**Comment by dktapps** [comment] 2019-07-28 09:11
Closing due to unable to reproduce with the information provided.

**Closed by dktapps** 2019-07-28 09:11 UTC
Labels: Resolution: Invalid
