### ISSUE TITLE
Watchdog Timer (Force shutdown when freeze)

### ISSUE THREAD

**Issue by AkmalFairuz** [pmmp/PocketMine-MP#4134] opened 2021-03-31 07:11 UTC
## Description
Force shutdown server when main thread freeze within a certain time.
When the server freeze type /stop on console and CTRL+C not working, must kill PocketMine process id manually.

https://en.wikipedia.org/wiki/Watchdog_timer

## Justification
- Make server keep online.

**Comment by dktapps** [comment] 2021-03-31 11:49
On Linux, you can use ctrl+z and then `kill -9 $(cat server.lock)`. On Windows you can just close the terminal window or kill it from task manager.

**Comment by dktapps** [comment] 2021-04-17 12:01
I'm going to close this, because the way you did it in your PR can easily be implemented as a plugin.

This is addressing the symptoms of a problem and not its cause. Most of the time, this will be actively harmful, because it would get in the way of debugging (the server might kill itself before anyone got a chance to attach a debugger, denying any possibility of identifying the cause of the freeze). In addition, a freeze might occur for other reasons, such as the server running out of memory and thrashing swap, something else hogging the CPU, etc; in which cases a watchdog would be useless.

**Closed by dktapps** 2021-04-17 12:01 UTC
Labels: Category: Core, Type: Enhancement
