### ISSUE TITLE
New Update (1.16.220), lot of plugins crash

### ISSUE THREAD

**Issue by ZeroZipp-Studios** [pmmp/PocketMine-MP#4181] opened 2021-04-17 17:49 UTC
After the new update, a lot of plugins crash by using them.
And this comes up in the console:

[19:46:28] [Server thread/CRITICAL]: Error: "Undefined property: pocketmine\network\mcpe\protocol\InventoryTransactionPacket::$transactionType" (EXCEPTION) in "pmsrc/src/pocketmine/network/mcpe/protocol/DataPacket" at line 195
[19:46:28] [Server thread/CRITICAL]: #0 plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/event/EventListener(75): pocketmine\network\mcpe\protocol\DataPacket->__get(string[15] transactionType)
[19:46:28] [Server thread/CRITICAL]: #1 pmsrc/src/pocketmine/plugin/MethodEventExecutor(42): revivalpmmp\pureentities\event\EventListener->dataPacketReceiveEvent(object pocketmine\event\server\DataPacketReceiveEvent)
[19:46:28] [Server thread/CRITICAL]: #2 pmsrc/src/pocketmine/plugin/RegisteredListener(80): pocketmine\plugin\MethodEventExecutor->execute(object revivalpmmp\pureentities\event\EventListener, object pocketmine\event\server\DataPacketReceiveEvent)
[19:46:28] [Server thread/CRITICAL]: #3 pmsrc/src/pocketmine/event/Event(88): pocketmine\plugin\RegisteredListener->callEvent(object pocketmine\event\server\DataPacketReceiveEvent)
[19:46:28] [Server thread/CRITICAL]: #4 pmsrc/src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(108): pocketmine\event\Event->call()
[19:46:28] [Server thread/CRITICAL]: #5 pmsrc/src/pocketmine/network/mcpe/protocol/BatchPacket(130): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket)
[19:46:28] [Server thread/CRITICAL]: #6 pmsrc/src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(109): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
[19:46:28] [Server thread/CRITICAL]: #7 pmsrc/src/pocketmine/Player(3311): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
[19:46:28] [Server thread/CRITICAL]: #8 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
[19:46:28] [Server thread/CRITICAL]: #9 pmsrc/vendor/pocketmine/raklib/src/server/ServerHandler(95): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[19] 89.247.255.61 32730, object raklib\protocol\EncapsulatedPacket, integer 0)
[19:46:28] [Server thread/CRITICAL]: #10 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
[19:46:28] [Server thread/CRITICAL]: #11 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
[19:46:28] [Server thread/CRITICAL]: #12 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(113): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
[19:46:28] [Server thread/CRITICAL]: #13 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(75): pocketmine\snooze\SleeperHandler->processNotifications()
[19:46:28] [Server thread/CRITICAL]: #14 pmsrc/src/pocketmine/Server(2155): pocketmine\snooze\SleeperHandler->sleepUntil(double 1618681588.4158)
[19:46:28] [Server thread/CRITICAL]: #15 pmsrc/src/pocketmine/Server(1992): pocketmine\Server->tickProcessor()
[19:46:28] [Server thread/CRITICAL]: #16 pmsrc/src/pocketmine/Server(1586): pocketmine\Server->start()
[19:46:28] [Server thread/CRITICAL]: #17 pmsrc/src/pocketmine/PocketMine(291): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[16] /home/minecraft/, string[24] /home/minecraft/plugins/)
[19:46:28] [Server thread/CRITICAL]: #18 pmsrc/src/pocketmine/PocketMine(321): pocketmine\server()
[19:46:28] [Server thread/CRITICAL]: #19 pmsrc(11): require(string[68] phar:///home/minecraft/pocketmine.phar/src/pocketmine/PocketMine.php) 

Any one , an idea how to fix it?

**Comment by Mohagames205** [comment] 2021-04-17 17:53
Hello, this issue is caused by a plugin and thus should be fixed by the plugin author.

**Closed** 2021-04-17 18:07 UTC
Labels: Support request

**Comment by ZeroZipp-Studios** [comment] 2021-04-17 19:35
Ok, thaks. I gona try to reinstall all the plugins.
