### ISSUE TITLE
Cant See The Player whom you kill

### ISSUE THREAD

**Issue by Altamash347** [pmmp/PocketMine-MP#3818] opened 2020-09-07 18:00 UTC
### Issue description

- Expected result: I was expecting to kill him again after killing him once
- Actual result: He became invisible only for me and all players can see him

### OS and versions

* PocketMine-MP: 3.15.1
* PHP: 7.3
* Server OS: Linux
* Game version: PE/Win10 (delete as appropriate)

### Plugins

- I removed all the plugins but the issue is still happening

### Crashdump, backtrace or other files

There is not a crash anywhere. Its just a little bug

**Comment by dktapps** [comment] 2020-09-07 20:38
Can anyone else reproduce this?

**Comment by Altamash347** [comment] 2020-09-08 07:11
Yes its happening to everyone that when someone kill a player he cant see him again unless he rejoins the server.

**Comment by dktapps** [comment] 2020-09-08 11:36
I'm asking for someone else to independently reproduce it on a different server.

**Comment by Altamash347** [comment] 2020-09-09 08:47
I dont know then

**Comment by UnclassifiedX** [comment] 2020-09-12 15:11
Created a fresh server with the same PHP and PMMP version. Got my player on computer to kill my other account on my tablet, was visible after he was killed and re spawned.

**Comment by dktapps** [comment] 2020-09-12 15:18
so you're saying you can't reproduce this? @UnclassifiedX

**Comment by UnclassifiedX** [comment] 2020-09-12 15:20
Yes, I'm saying I wasn't able to reproduce this issue.

**Comment by dktapps** [comment] 2020-10-31 16:19
Closing this due to lack of movement or additional information, and not reproducible.

**Closed by dktapps** 2020-10-31 16:19 UTC
Labels: Category: Gameplay, Status: Unconfirmed
