### ISSUE TITLE
Resource pack error!!

### ISSUE THREAD

**Issue by AlicanCopur** [pmmp/PocketMine-MP#3028] opened 2019-07-14 15:07 UTC
### Issue description

- Expected result: join server
- Actual result: error

### Steps to reproduce the issue
1. Install a resource pack in the server.
2. Join the game.
3. It gives the error.
4. Error: There was a problem downloading or applying the source package

### OS and versions

* PocketMine-MP: 3.9.0
* PHP: 7.2
* Server OS: Linux CentOS
* Game version: PE

**Comment by dktapps** [comment] 2019-07-14 15:09
did you even glance at the top issue? I won't ask if you used the search box ...

**Comment by dktapps** [comment] 2019-07-14 15:09
Duplicate of #3023

**Closed by dktapps** 2019-07-14 15:09 UTC
