### ISSUE TITLE
Various health-related bugs

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#23] opened 2016-10-14 11:07 UTC
### Issue description

- [x] Double hit-animation when taking fall damage (not reproducible as of 1.0.0.16)
- [x] Players taking fall-damage enough to kill them frequently do not have the "You died!" screen displayed, instead staying alive at zero hearts and recovering up to 1 heart.
- [x] Hit-animation when players regain health ~~(health should be set using attributes, not SetHealthPacket)~~ (old client bug)
- [x] Cancelling health regeneration doesn't seem to work (#157)
- [ ] No death animation when dying from fall damage (to other players you literally just vanish when you hit the ground)
- [x] ~~Changing a player's max health doesn't update client attributes~~ (client bug?)
### OS and versions

- PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/2fba1073ddf4965eb5d2bbbbbfb4a5c5f9377db3
- PHP: doesn't matter
- OS: doesn't matter

**Comment by robske110** [comment] 2016-10-14 13:14
most bugs are related to the setHealthPacket() now only used for killing players/(decreasing health).

**Comment by Sandertv** [comment] 2016-10-14 14:30
Could I report another issue? I'm not sure if it's intended or not, but here it is anyways: When players attack using a tool of any kind they are able to hit the target about 5 times before the target even gets knocked back. This does not happen with normal items which is kind of weird...

**Comment by dktapps** [comment] 2017-01-09 14:16
Can anyone reproduce the double hit animation issue? I can't anymore.

**Comment by dktapps** [comment] 2017-01-09 14:36
3. not reproducible as of 1.0.0.16

**Comment by Muqsit** [comment] 2017-01-09 15:58
Small bug.
Player::setMaxHealth($amount) does not update until the player's health has changed (when Player::setHealth() is called)

**Comment by dktapps** [comment] 2017-01-09 16:03
Attributes issue, you can resend them manually if it's important to you.

**Comment by Muqsit** [comment] 2017-01-09 16:05
Exactly what I'm doing right now.
Thanks, anyways!

**Comment by dktapps** [comment] 2017-01-09 16:31
@Muqsit I believe that is a client bug, the server-side code is perfect as far as I can tell. Similar issues can be seen on Realms with the XP bar not updating, so I think that's a client issue.

**Comment by dktapps** [comment] 2017-03-18 22:10
#4 is due to client-sided health regeneration effects.

**Comment by dktapps** [comment] 2017-03-20 12:23
4 has been reported to Mojang as https://bugs.mojang.com/browse/MCPE-20507 .

**Comment by AppleDevelops** [comment] 2017-08-11 03:36
4 is still reproducible as of 1.2

**Comment by AppleDevelops** [comment] 2017-08-11 03:39
Just tested on 1.2 beta and 4 is still reproducible on it.

**Comment by dktapps** [comment] 2017-08-11 08:21
Read the comments. 4 is a client-sided bug, so there's nothing for us to do about it.

**Comment by AppleDevelops** [comment] 2017-08-17 19:18
I know it was a client bug, I voted on it. Just got a bit confused sorry

**Comment by Muqsit** [comment] 2017-08-23 13:26
`No death animation when dying from fall damage (to other players you literally just vanish when you hit the ground)`
I found out that sending EntityEventPacket::DEATH_ANIMATION to a client also despawns them. I think since the server sends EntityEventPacket::DEATH_ANIMATION + RemoveEntityPacket, RemoveEntityPacket overrides the death animation.

**Comment by Muqsit** [comment] 2017-09-06 17:06
**6th** was fixed in 1.2, tested.
A workaround for 1.1 clients is to `Player::setHealth(Player::getHealth())` after changing the player's max health.

**Closed** 2018-01-03 14:45 UTC
Labels: Category: Client (all), Category: Gameplay, Status: Reproduced
