### ISSUE TITLE
Skin Timeout / Feature request

### ISSUE THREAD

**Issue by Darker935** [pmmp/PocketMine-MP#5472] opened 2022-12-24 23:01 UTC
### Issue description

- Expected result: Normal login without timeout
- Actual result: Login Timeout

### Steps to reproduce the issue
1. Any Skin with more than 2MB size
2. PR: #3733

### Crashdump, backtrace or other files

```
[22:56:37.294] [RakLib thread/DEBUG]: [Session: 177.47.---.--- 45356] Received duplicate or out-of-window packet (sequence number 220, window 222-2270)
[22:56:37.299] [RakLib thread/DEBUG]: [Session: 177.47.---.--- 45356] Invalid split packet part, too many parts or invalid split index (part index 217, part count 218)
[22:56:37.601] [RakLib thread/DEBUG]: [Session: 177.47.---.--- 45356] Invalid split packet part, too many parts or invalid split index (part index 215, part count 218)
```

**Please add an option for change the limit that prevent ZIP Attacks, or disable it**

**Comment by IvanCraft623** [comment] 2022-12-24 23:21
Please do not open an issue if there is already one reporting that.

**Comment by dktapps** [comment] 2022-12-24 23:37
Duplicate of #3733

**Closed as completed by dktapps** 2022-12-24 23:37 UTC
Labels: Resolution: Duplicate, Category: Client, Category: Network
