### ISSUE TITLE
Strange shadows since new update

### ISSUE THREAD

**Issue by jarne** [pmmp/PocketMine-MP#970] opened 2017-06-02 15:50 UTC
### Issue description

Since the new update 1.1 has been released and I've updated my PocketMine-MP installation to the latest commit (3ac51e1095279f53cea19427f0c50748a2c40005), there are strange shadows im some worlds (not in every). I've also uploaded some screenshots and the affected world which is in PMAnvil format.

![img_3856](https://cloud.githubusercontent.com/assets/15860314/26733646/c2dbb966-47bb-11e7-8284-1c5d26636d19.PNG)

![img_3858](https://cloud.githubusercontent.com/assets/15860314/26733650/c54b88b6-47bb-11e7-9728-fe84e8c55c02.PNG)

[world.zip](https://github.com/pmmp/PocketMine-MP/files/1048183/world.zip)

### Steps to reproduce the issue

1. Download my world (or maybe the bug also appears in one of your worlds)
2. Join the game and see the shadows under trees or the grass

### OS and versions

* PocketMine-MP: 3ac51e1095279f53cea19427f0c50748a2c40005
* PHP: 7.0.19
* Server OS: macOS 10.12
* Game version: PE

### Crashdump, backtrace or other files

* Nothing

**Comment by dktapps** [comment] 2017-06-02 15:51
duplicate of #843 

Newly-generated worlds will not be affected by this issue.

**Closed by dktapps** 2017-06-02 15:51 UTC

**Comment by Misteboss** [comment] 2017-06-11 20:19
You can fix it by modifying Level.php on line 2654, you need to delete 
        `if(!$chunk->isLightPopulated() and $chunk->isPopulated() and $this->getServer()>getProperty("chunk-ticking.light-updates", false)){`  this condition.
Then restart your server join your world /save-all and re add the condition
