### ISSUE TITLE
Vertical movement more than 10 blocks triggers movement anti-cheat

### ISSUE THREAD

**Issue by DarkWav** [pmmp/PocketMine-MP#22] opened 2016-10-13 17:30 UTC
### Issue description

When a player climbs a high tower with ladders, its being dragged back. This also happens when anti flight is disabled, and in creative mode.

### Steps to reproduce the issue

1. Build a really high tower with ladders (at least 30 blocks (for safety that it happens))
2. Climb the ladder. you´ll be dragged back on the ground (note that it will not instantly happen, you´ll have to climb some blocks.

### OS and versions

- PocketMine-MP: github master (commit 2fba1073ddf4965eb5d2bbbbbfb4a5c5f9377db3)
- PHP: [7.0.11](https://github.com/DarkWav/PHP7-Windows-PocketMine/raw/master/PHP_7.0.11-PRO_x86_Windows.zip)
- OS: Windows 10 Pro
### Crashdump, backtrace or other files

none

**Comment by RocoWayne** [comment] 2016-10-13 17:43
im having the same problem!

**Comment by SOF3** [comment] 2016-10-14 07:56
> I am pretty sure its a bug in pocketmine because it will not happen on genisys. 

What's wrong even if this happens in genisys?

**Comment by dktapps** [comment] 2016-10-14 08:18
This is not a Genisys discussion forum. Please refrain from turning it into one.

**Comment by dktapps** [comment] 2016-10-14 11:01
This would appear to be a movement-check bug, but since I can't reproduce it, it's hard to say.

**Comment by DarkWav** [comment] 2016-10-14 11:58
@SOF3, im sorry for that "unrelatedness" but i thought it may help @dktapps .

**Comment by DarkWav** [comment] 2016-10-14 12:02
@dktapps maybe you can replace pocketmine´ s movement ckeck with genisys´ s movement check to fix the problem.

**Comment by dktapps** [comment] 2016-10-14 12:04
\>_> This project does not exist for the purposes of copy-pasting. How many times do I have to say it!

**Comment by legoboy0215** [comment] 2016-10-14 12:13
@DarkWav This is not some plugin project you own. You can't just copy paste code from other _**unrelated**_ projects...

**Comment by DarkWav** [comment] 2016-10-14 13:34
no just a suggestion you dont have to do it :D
@legoboy0215 WHen did i say i own this ?????????

**Comment by TheUSBFlash** [comment] 2016-12-07 13:18
Reason: Player's bounding box doesn't collide with Ladder's bounding box server side. Due to being in a free space/air part of the ladder, the server thinks you are flying.
If you make the AxisBB of the ladder bigger, it all works fine.
https://github.com/ClearSkyTeam/ClearSky/commit/c103fcb1ecf0a15492612d4e684e67a7912cc190

**Comment by dktapps** [comment] 2016-12-15 09:57
:facepalm: if it thought you were flying, this wouldn't be the case:
> This also happens when anti flight is disabled, and in creative mode.

**Comment by dktapps** [comment] 2017-01-04 22:16
Found the _actual_ bug this time. Let's all take a moment to #blame @shoghicp.

Vertical movement less than 2.3 blocks at once is treated as zero. Of course, while you are climbing a ladder you are _continuously moving smaller amounts_ than this, so the server thinks you are not moving. Once you travel 10 blocks, the anti-cheat kicks in, thinking you have moved more than 10 blocks in a single tick.

**Comment by dktapps** [comment] 2017-01-04 22:24
This is also the cause of the infamous pull-back bug in spectator mode when flying through blocks.

**Comment by dktapps** [comment] 2017-01-05 00:00
Forget the 2.3 thing, this line is so badly wrong that it will affect _all_ heights. Unbelievable.

https://github.com/pmmp/PocketMine-MP/blame/mcpe-1.0/src/pocketmine/Player.php#L1377

**Comment by jojoe77777** [comment] 2017-01-05 00:06
@dktapps Was https://github.com/pmmp/PocketMine-MP/commit/ef7a843fa3e0c0377ec0e8678da9f1b4e0484ddb heading in the right direction?

**Comment by dktapps** [comment] 2017-01-05 00:07
@jojoe77777 no, that made related bugs worse.

**Comment by Sandertv** [comment] 2017-01-05 07:15
I blame Shoghi.

**Comment by dktapps** [comment] 2017-01-20 11:21
Fixed in #259

**Closed by dktapps** 2017-01-20 11:21 UTC
Labels: Category: Gameplay, Status: Debugged
