### ISSUE TITLE
Server crashed with unsupported item in inventory in PM5

### ISSUE THREAD

**Issue by leolee3914** [pmmp/PocketMine-MP#5265] opened 2022-08-30 06:49 UTC
Link to crashdump: https://crash.pmmp.io/view/7444891

### Additional comments (optional)
1. join a server which is using PM4
2. /give (your ID) crossbow
3. update the server to PM5 (git hash: d5762d3f4487772ffb6b7c77af4cd659585f6520)
4. join the server

**Comment by dktapps** [comment] 2022-08-30 14:29
Duplicate of #5128

**Closed as completed by dktapps** 2022-08-30 14:29 UTC
Labels: Resolution: Duplicate, Category: Core
