### ISSUE TITLE
Water Logging

### ISSUE THREAD

**Issue by Prim69** [pmmp/PocketMine-MP#4056] opened 2021-03-02 00:20 UTC
### Issue description

- Expected result: The water to properly flow over the slab.
- Actual result: The water broke

### Steps to reproduce the issue
1. Place a slab in water, the water will flow over the slab.
2. Reload the chunk, the water will have broken (not flowing over the slab)

![image](https://user-images.githubusercontent.com/13991048/109577187-2ef5bc80-7ac3-11eb-912f-7decd6c23e79.png)
![image](https://user-images.githubusercontent.com/13991048/109577191-30bf8000-7ac3-11eb-9772-e2bb7f237a3a.png)

### OS and versions

* PocketMine-MP: 3.17.5
* PHP: 7.4
* Server OS: Ubuntu
* Game version: Windows 10, bug is noticeable on all os's

### Plugins
[00:19:06] [Server thread/INFO]: Plugins (4): BlockSniper v3.2.3, BuilderTools v1.2.0-beta2, DevTools v1.14.2, MultiWorld v1.5.2

- If you remove all plugins, does the issue still occur? Yes
- If the issue is **not** reproducible without plugins:

  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by dktapps** [comment] 2021-03-02 00:25
Duplicate of #3722

**Closed by dktapps** 2021-03-02 00:25 UTC

**Comment by GangMemberXuvah** [comment] 2021-03-02 02:26
FREE XSUPER
