### ISSUE TITLE
Crafting Error and skin

### ISSUE THREAD

**Issue by TimKunG1007** [pmmp/PocketMine-MP#3212] opened 2019-12-08 09:42 UTC
I can't craft item in craft table and Skin Bug
Fighting✌✌✌✌🤘🤞
### OS and versions

* PocketMine-MP: 1.13.1
* PHP: 7.3
* Server OS: Windows 2012
* Game version: 1.13.1

**Comment by DenielWorld** [comment] 2019-12-08 09:54
Read changelog, the skin issue isn't a bug. Try crafting items without any plugins, crafting should work just fine. PocketMine-MP and Game version are not the same thing.

**Comment by dktapps** [comment] 2019-12-08 10:04
duplicate of #3211 and still nobody figured out that **all** information in the template is required...

**Closed by dktapps** 2019-12-08 10:04 UTC
