### ISSUE TITLE
Pocketmine doesn't check if Item has enchantments or not.

### ISSUE THREAD

**Issue by AyzrixYTB** [pmmp/PocketMine-MP#4260] opened 2021-06-09 19:41 UTC
### Issue description

When you use the contain function on an Inventory, pocketmine don't check if the player has really the same item (enchantments, lores, and more).

- Expected result: What were you expecting to happen? Pocketmine detect the same item but it's not
- Actual result: What actually happened? The condition contain return true and the item is removed.

### Steps to reproduce the issue
1. Make a simple code with a contain and a remove function to a player. Check if the player has a diamond sword without any enchantment and take an enchanted sword on your inventory. Pocketmine return true.

### OS and versions

* PocketMine-MP: 3.20.0
* PHP: 7.4.9
* Server OS: Ubuntu 21.04
* Game version: Win10
### Plugins

Plugins (2): DevTools v1.14.1, TestPlugin v1.0.0

- If you remove all plugins, does the issue still occur? Yes

**Comment by dktapps** [comment] 2021-06-09 19:51
Duplicate of #4233.

**Closed by dktapps** 2021-06-09 19:51 UTC
