### ISSUE TITLE
crash after canceling EntityDamageEvent after $player->transfer();

### ISSUE THREAD

**Issue by Saehing** [pmmp/PocketMine-MP#3149] opened 2019-10-15 15:53 UTC
TypeError: "Return value of pocketmine\network\mcpe\NetworkSession::getInvManager() must be an instance of pocketmine\network\mcpe\InventoryManager, null returned" (EXCEPTION) in "src/network/mcpe/NetworkSession" at line 810

Decision:
 Player.php
 18003:

$entity->attack($ev);

if($ev->isCancelled()){
return false;
}

$entity->attack($ev); to put after the condition

crashdump: https://pastebin.com/MXLWp6fa

**Comment by dktapps** [comment] 2019-10-15 15:55
duplicate of #1239

**Comment by dktapps** [comment] 2019-10-15 15:56
whoops, wrong issue ... duplicate of #3139

**Closed by dktapps** 2019-10-15 15:55 UTC

**Comment by Saehing** [comment] 2019-10-15 15:57
I'm sorry I didn't notice
