### ISSUE TITLE
PM4 Fall damage bug

### ISSUE THREAD

**Issue by mleqo0** [pmmp/PocketMine-MP#4291] opened 2021-06-28 20:18 UTC
### PM4 Fall damage bug.

- Expected result: Damage taken on contact with surface.
- 
- Actual result: Damage taken when player hits wall while falling, after the damage has been dealt player can finish falling down without taking any damage when hitting the ground.

### Steps to reproduce the issue
1. Build a wall high enough for damage to be dealt. 
2. While falling force yourself onto the wall you are falling next to. On mcbe win10 use “W” key to push yourself onto the wall. On pe use forward button.

### OS and versions
* PocketMine-MP: master 444d902990e00125afb6f1182d95cc0543b134c3

* PHP: 8.0
* Server OS: Ubuntu 18.04
* Game version: PE and Win10

Plugins:
The issue is reproducible without plugins.

Video demonstration: https://www.youtube.com/watch?v=7pZ5DPNK92k&feature=youtu.be

**Comment by dktapps** [comment] 2021-06-29 19:21
Have you tried this using PHP 7.4?

**Comment by mleqo0** [comment] 2021-06-29 20:22
> Have you tried this using PHP 7.4?

Yep I did try this on php 7.4,  It’s also possible to recreate this on pm3 php 7.4, if you upload a world generated on mc java 1.8.8 and try the same thing on newly pocketmine generated terrain the bug will be visible.

However, on pm4 this bug can be reacreated anywhere, even if the world was generated by pocketmine.

**Comment by TheNewHEROBRINEX** [comment] 2021-07-02 00:00
Maybe this has the same cause of #3929

**Comment by Blackjack200** [comment] 2021-08-13 11:05
i think it maybe because of player boundingbox is not correct, and PM assmue that the player is step in the block, also gliches when place block

**Comment by CortexPE** [comment] 2021-08-23 10:00
Can reproduce: https://youtu.be/sg0UORibC-o

**Comment by dktapps** [comment] 2021-09-10 15:54
Fixed by 7701e1ff988af54eee167bc3e2281762b6c017d7.

**Closed by dktapps** 2021-09-10 15:54 UTC
Labels: Category: Gameplay, Status: Unconfirmed
