### ISSUE TITLE
Segmentation fault after 'opcache.so' load failure during PocketMine installation

### ISSUE THREAD

**Issue by markeev** [pmmp/PocketMine-MP#5876] opened 2023-07-05 08:11 UTC
I'm trying to set up PocketMine, but regardless of whether I use the command from pmmp.io or download everything from GitHub and compile the PHP binaries, I encounter the same issue.

Upon starting the server, I get this warning message:
`Warning: Failed loading Zend extension 'opcache.so' (tried: /home/runner/work/PHP-Binaries/PHP-Binaries/bin/php7/lib/php/extensions/no-debug-zts-20210902/opcache.so (/home/runner/work/PHP-Binaries/PHP-Binaries/bin/php7/lib/php/extensions/no-debug-zts-20210902/opcache.so: cannot open shared object file: No such file or directory), /home/runner/work/PHP-Binaries/PHP-Binaries/bin/php7/lib/php/extensions/no-debug-zts-20210902/opcache.so.so (/home/runner/work/PHP-Binaries/PHP-Binaries/bin/php7/lib/php/extensions/no-debug-zts-20210902/opcache.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0`

Subsequently, when a player connects or when the map is being generated, I get a Segmentation fault (core dumped) error and the server crashes.

The system is running on Ubuntu with PHP 8.2/8.1. I have ten other servers running on version 1.1.x on the same machine without any issues.

I have never dealt with a Segmentation fault before. Could you please advise what additional information I could provide to help solve this problem?

## Additional comments (optional)
# Environment:
OS: Ubuntu
PHP version: 8.2/8.1
PocketMine version: (please provide if applicable)
Installation method: both from the command on pmmp.io and from GitHub with compiled PHP binaries

# Steps to Reproduce:
1. Install PocketMine using either method.
2. Start the server.
3. Observe the 'opcache.so' warning.
4. Attempt to connect a player or generate a map.
5. Observe the Segmentation fault (core dumped) error.

**Comment by markeev** [comment] 2023-07-05 08:25
[!] Be sure to check it, if you have to forward and you skip that, no external players will be able to join. [Press Enter]

[08:25:00.426] [Server thread/INFO]: Loading server configuration
[08:25:00.432] [Server thread/INFO]: Selected English (eng) as the base language
[08:25:00.434] [Server thread/INFO]: Starting Minecraft: Bedrock Edition server version v1.20.0
[08:25:00.457] [Server thread/INFO]: Online mode is enabled. The server will verify that players are authenticated to Xbox Live.
[08:25:00.482] [Server thread/INFO]: This server is running PocketMine-MP version 5.2.0
[08:25:00.482] [Server thread/INFO]: PocketMine-MP is distributed under the LGPL License
[08:25:00.654] [Server thread/INFO]: Loading resource packs...
[08:25:00.720] [Server thread/INFO]: Preparing world "world"
[08:25:00.730] [Server thread/NOTICE]: Spawn terrain for world "world" is being generated in the background
**Segmentation fault (core dumped)**

**Comment by dktapps** [comment] 2023-07-05 08:30
The opcache.so error is unrelated. See FAQ: https://doc.pmmp.io/en/rtfd/faq/installation/opcache.so.html

**Comment by markeev** [comment] 2023-07-05 13:36
ok, it fixed opcache.so error, but still crush

**Comment by dktapps** [comment] 2023-07-05 16:48
I'm not able to reproduce this. I need more information.

**Comment by markeev** [comment] 2023-07-05 18:04
Could you please guide me to resources or provide links that will help me better understand how to handle issues such as a Segmentation Fault? This information would be incredibly useful not only for resolving the current issue, but also for future troubleshooting. I appreciate your time and assistance in this matter.

**Comment by dktapps** [comment] 2023-07-06 09:00
Do `ulimit -c unlimited`. When the segfault occurs, it will generate a file called `core` (or something similar) which can be used to debug the problem. Zip the file up and send it to dktapps@pmmp.io.

**Comment by markeev** [comment] 2023-07-07 09:18
I have sent the dump that I obtained. I also want to mention that when I changed the value of "async-workers:" in pocketmine.yml to 0, the program started working correctly.

**Comment by dktapps** [comment] 2023-07-07 09:28
Which PM version did you use?

**Comment by markeev** [comment] 2023-07-07 09:29
PM 5

**Comment by dktapps** [comment] 2023-07-07 09:31
Exact version. "5" could be any version released in the last 6 weeks.

**Comment by dktapps** [comment] 2023-07-07 10:58
How often does this error occur? The crash trace is pretty obscure (it winds up somewhere in `zend_execute_ex` which is nearly impossible to track down due to lack of debugging symbols)

**Comment by markeev** [comment] 2023-07-07 12:43
> Exact version. "5" could be any version released in the last 6 weeks.

PM - https://github.com/pmmp/PocketMine-MP/releases/tag/5.2.0
PHP - https://github.com/pmmp/PHP-Binaries/releases/tag/php-8.1-latest

**Comment by markeev** [comment] 2023-07-07 12:45
> How often does this error occur? The crash trace is pretty obscure (it winds up somewhere in `zend_execute_ex` which is nearly impossible to track down due to lack of debugging symbols)

Anytime when a player joins or a card is generated.

**Comment by dktapps** [comment] 2023-07-07 13:02
I don't know what "a card is generated" means.

**Comment by markeev** [comment] 2023-07-08 17:33
map, sorry :0
When map is being generated.

**Comment by dktapps** [comment] 2023-07-08 19:54
Please try it again with this binary: https://github.com/pmmp/PHP-Binaries/suites/14139010382/artifacts/791841875

When you get another core file with this binary, please send it to me.

**Comment by dktapps** [comment] 2023-07-13 11:51
Bump. Is this still an issue?

**Comment by dktapps** [comment] 2023-07-18 12:05
Closing due to lack of response.

**Closed as completed by dktapps** 2023-07-18 12:05 UTC
Labels: Category: PHP, Resolution: Awaiting Response
