### ISSUE TITLE
Players getting stuck after respawning

### ISSUE THREAD

**Issue by isoz** [pmmp/PocketMine-MP#1518] opened 2017-11-04 21:03 UTC
### Steps to reproduce the issue
Players are not respawning in the spawn point on some of my worlds after dying, they get stuck in the air in other coordinates, I already downloaded the world myself and checked level.dat with NBTExplorer to make sure the spawn was set at the right coords. This server has 3 worlds, only happening in 2 of them, one you spawn underground and die, the other one in the sky with spasms.

### OS and versions
Ubuntu 14.04, Latest commit / eab7b934833f275b9f61d0682ea0438f11fb9922

Tried with and without plugins

**Comment by dktapps** [comment] 2017-11-04 21:11
I assume the world where everything is fine, is the default world?

**Comment by isoz** [comment] 2017-11-04 21:11
Correct

**Comment by isoz** [comment] 2017-11-04 21:13
Not sure if this is relevant or not, but the place "where you get stuck" mid-respawning, you could see a mirror of the default world there. Like ghost chunks and floating text from the default world in a completely different world.

**Comment by isoz** [comment] 2017-11-04 21:18
Changing the default to world to one of the worlds that was being affected, resolves the problem in said world.

**Comment by thebigsmileXD** [comment] 2017-11-04 21:22
Hey @dktapps , that is exactly what i've shown you once - that the spawn for some reason defaults to 255 70 255

**Comment by isoz** [comment] 2017-11-04 21:23
Those coords seem to be the same where me and my players are getting stuck at.
245 76 262

**Comment by dktapps** [comment] 2017-11-04 21:23
@thebigsmileXD your description was confusing, this issue better describes it.

**Comment by dktapps** [comment] 2017-11-04 22:06
@isoz would you mind testing https://github.com/pmmp/PocketMine-MP/commit/20d2ef9d38f9144e550c63e25d611cc30f6e9b49 ?

**Comment by isoz** [comment] 2017-11-04 22:09
The player is still stuck but now it's not in the air, they got sent back to the Lobby(default) world for some reason. I teleported to him while he was stuck, he says he can't see anything.

**Comment by dktapps** [comment] 2017-11-04 22:14
The commit I just pushed fixes players spawning in the wrong world when a respawn involves a level change, so the chances are that originally he was getting teleported to the default world's spawn coordinates, but in the other world.

**Comment by isoz** [comment] 2017-11-04 22:17
I can't confirm that because the coords he was getting stuck at were 245 76 262 and default world spawn is at -25 26 325

**Comment by dktapps** [comment] 2017-11-04 22:21
Currently, being teleported to the default world when you die is expected behaviour, because the player spawn point will be set in the world they first spawned in. I'm not sure about your problem with getting stuck though.

**Comment by isoz** [comment] 2017-11-04 22:30
Ok I can confirm that the 'getting stuck' part was caused by the plugin EssentialsTP, the player is teleported to default level after respawning, no problems.

**Comment by dktapps** [comment] 2017-11-07 11:33
EssentialsTP teleports players on PlayerRespawnEvent instead of changing the respawn position. This will likely cause undesirable behaviour, since the core will also teleport them immediately after the event.

The remaining issue here (getting stuck) is therefore a plugin at fault, so I'm going to close this.

**Closed by dktapps** 2017-11-07 11:33 UTC
Labels: Category: Gameplay, Status: Unconfirmed

**Comment by dktapps** [comment] 2017-11-07 18:03
I've fixed the bug in essentialsTP, you can grab a dev build from https://poggit.pmmp.io/ci/poggit-orphanage/essentialsTP
