### ISSUE TITLE
broadcast sound bug

### ISSUE THREAD

**Issue by Nayddddd** [pmmp/PocketMine-MP#6329] opened 2024-04-08 16:23 UTC
Hello, when I fight a player who has any armor it makes the sound of when he puts on the armor (see video)
could you solve this problem?

https://medal.tv/games/minecraft/clips/25VEmuvYrIIq1o/d1337sDf8JYB?invite=cr-MSw1MnksMjE5MDU1NTY3LA

**Comment by dktapps** [comment] 2024-04-08 18:15
Duplicate of #6325

**Closed as completed by dktapps** 2024-04-08 18:15 UTC
Labels: Resolution: Duplicate, Category: Gameplay
