### ISSUE TITLE
addChunkPacket() on null

### ISSUE THREAD

**Issue by HipsterAF** [pmmp/PocketMine-MP#1497] opened 2017-10-24 15:55 UTC
### Issue description

Server froze load was 100% and there was this error - 
24.10 09:38:04 [Server] Server thread/CRITICAL Error: "Call to a member function addChunkPacket() on null" (EXCEPTION) in "src/pocketmine/inventory/ChestInventory" at line 90
24.10 09:38:04 [Server] Server thread/CRITICAL Unhandled exception executing command 'home pvp' in home: Call to a member function addChunkPacket() on null

### Steps to reproduce the issue

1. i dont know what players did for this error to pop up
2. ...

### OS and versions

* PocketMine-MP: 93d60a9
* PHP: 7.2
* Server OS: Linux
* Game version: PE 1.2 (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)
Plugins (29): DevTools v1.12.4, StackingMobs v0.0.1, iProtector v3.1b, NoAdvertisingPE v1.0.1, ItemCloud v1.3, 1vs1 v0.0.5, Sell v1.1, EconomyAPI v2.0.9, WorldProtect v2.3.0, EconomySell v2.0.7, PurePerms v1.3.7, EconomyShop v2.0.7, MineReset v3, TapToDo v2.2.1, AutoInv v0.0.2, BuycraftPM v0.2, Slapper v1.3.4, EconomyPShop v2.0.2, SimpleAuth v2.1.1-1.alpha9, AuctionHousePHP v1, VoteReward v3.0.2, EconomyPotionDispenser v0.0.2, SimpleAuthHelper v2.0.6-1.alpha8, EssentialsPE, RankUp v0.3.1, PureChat v1.4.0, MyPlot v1
### Crashdump, backtrace or other files
Backtrace - 
24.10 09:38:04 [Server] Server thread/DEBUG #24 /PocketMine-MP.phar(1): require_once(string phar:///PocketMine-MP.phar/src/pocketmine/PocketMine.php)
24.10 09:38:04 [Server] Server thread/DEBUG #23 src/pocketmine/PocketMine(556): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar:///PocketMine-MP.phar/, string /, string /plugins/)
24.10 09:38:04 [Server] Server thread/DEBUG #22 src/pocketmine/Server(1715): pocketmine\Server->start()
24.10 09:38:04 [Server] Server thread/DEBUG #21 src/pocketmine/Server(2133): pocketmine\Server->tickProcessor()
24.10 09:38:04 [Server] Server thread/DEBUG #20 src/pocketmine/Server(2254): pocketmine\Server->tick()
24.10 09:38:04 [Server] Server thread/DEBUG #19 src/pocketmine/Server(2497): pocketmine\network\Network->processInterfaces()
24.10 09:38:04 [Server] Server thread/DEBUG #18 src/pocketmine/network/Network(89): pocketmine\network\mcpe\RakLibInterface->process()
24.10 09:38:04 [Server] Server thread/DEBUG #17 src/pocketmine/network/mcpe/RakLibInterface(84): raklib\server\ServerHandler->handlePacket()
24.10 09:38:04 [Server] Server thread/DEBUG #16 src/raklib/server/ServerHandler(97): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 79.71.12.7:63341, raklib\protocol\EncapsulatedPacket object, integer 0)
24.10 09:38:04 [Server] Server thread/DEBUG #15 src/pocketmine/network/mcpe/RakLibInterface(143): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
24.10 09:38:04 [Server] Server thread/DEBUG #14 src/pocketmine/Player(3072): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
24.10 09:38:04 [Server] Server thread/DEBUG #13 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(92): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
24.10 09:38:04 [Server] Server thread/DEBUG #12 src/pocketmine/network/mcpe/protocol/BatchPacket(118): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\CommandRequestPacket object)
24.10 09:38:04 [Server] Server thread/DEBUG #11 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(92): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
24.10 09:38:04 [Server] Server thread/DEBUG #10 src/pocketmine/network/mcpe/protocol/CommandRequestPacket(47): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleCommandRequest(pocketmine\network\mcpe\protocol\CommandRequestPacket object)
24.10 09:38:04 [Server] Server thread/DEBUG #9 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(220): pocketmine\Player->chat(string /home pvp)
24.10 09:38:04 [Server] Server thread/DEBUG #8 src/pocketmine/Player(2182): pocketmine\Server->dispatchCommand(pocketmine\Player object, string home pvp)
24.10 09:38:04 [Server] Server thread/DEBUG #7 src/pocketmine/Server(1968): pocketmine\command\SimpleCommandMap->dispatch(pocketmine\Player object, string home pvp)
24.10 09:38:04 [Server] Server thread/DEBUG #6 src/pocketmine/command/SimpleCommandMap(255): EssentialsPE\Commands\Home\Home->execute(pocketmine\Player object, string home, array Array())
24.10 09:38:04 [Server] Server thread/DEBUG #5 EssentialsPE_v2.0.0/src/EssentialsPE/Commands/Home/Home(53): pocketmine\Player->teleport(EssentialsPE\BaseFiles\BaseLocation object)
24.10 09:38:04 [Server] Server thread/DEBUG #4 src/pocketmine/Player(3656): pocketmine\Player->removeAllWindows()
24.10 09:38:04 [Server] Server thread/DEBUG #3 src/pocketmine/Player(3829): pocketmine\Player->removeWindow(pocketmine\inventory\DoubleChestInventory object, boolean )
24.10 09:38:04 [Server] Server thread/DEBUG #2 src/pocketmine/Player(3815): pocketmine\inventory\BaseInventory->close(pocketmine\Player object)
24.10 09:38:04 [Server] Server thread/DEBUG #1 src/pocketmine/inventory/BaseInventory(399): pocketmine\inventory\DoubleChestInventory->onClose(pocketmine\Player object)
24.10 09:38:04 [Server] Server thread/DEBUG #0 src/pocketmine/inventory/DoubleChestInventory(98): pocketmine\inventory\ChestInventory->broadcastBlockEventPacket(pocketmine\tile\Chest object, boolean )
24.10 09:38:04 [Server] Server thread/CRITICAL Error: "Call to a member function addChunkPacket() on null" (EXCEPTION) in "src/pocketmine/inventory/ChestInventory" at line 90
24.10 09:38:04 [Server] Server thread/CRITICAL Unhandled exception executing command 'home pvp' in home: Call to a member function addChunkPacket() on null

**Comment by dktapps** [comment] 2017-10-24 16:00
duplicate of #1449

**Closed by dktapps** 2017-10-24 16:00 UTC

**Comment by HipsterAF** [comment] 2017-10-24 16:56
is this related too?
```
Server thread/DEBUG #17 /PocketMine-MP.phar(1): require_once(string phar:///PocketMine-MP.phar/src/pocketmine/PocketMine.php)
24.10 10:39:06 [Server] Server thread/DEBUG #16 src/pocketmine/PocketMine(556): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar:///PocketMine-MP.phar/, string /, string /plugins/)
24.10 10:39:06 [Server] Server thread/DEBUG #15 src/pocketmine/Server(1715): pocketmine\Server->start()
24.10 10:39:06 [Server] Server thread/DEBUG #14 src/pocketmine/Server(2133): pocketmine\Server->tickProcessor()
24.10 10:39:06 [Server] Server thread/DEBUG #13 src/pocketmine/Server(2254): pocketmine\Server->tick()
24.10 10:39:06 [Server] Server thread/DEBUG #12 src/pocketmine/Server(2497): pocketmine\network\Network->processInterfaces()
24.10 10:39:06 [Server] Server thread/DEBUG #11 src/pocketmine/network/Network(89): pocketmine\network\mcpe\RakLibInterface->process()
24.10 10:39:06 [Server] Server thread/DEBUG #10 src/pocketmine/network/mcpe/RakLibInterface(82): raklib\server\ServerHandler->handlePacket()
24.10 10:39:06 [Server] Server thread/DEBUG #9 src/raklib/server/ServerHandler(97): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 90.201.63.80:53794, raklib\protocol\EncapsulatedPacket object, integer 0)
24.10 10:39:06 [Server] Server thread/DEBUG #8 src/pocketmine/network/mcpe/RakLibInterface(143): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
24.10 10:39:06 [Server] Server thread/DEBUG #7 src/pocketmine/Player(3072): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
24.10 10:39:06 [Server] Server thread/DEBUG #6 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(92): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
24.10 10:39:06 [Server] Server thread/DEBUG #5 src/pocketmine/network/mcpe/protocol/BatchPacket(118): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\InventoryTransactionPacket object)
24.10 10:39:06 [Server] Server thread/DEBUG #4 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(92): pocketmine\network\mcpe\protocol\InventoryTransactionPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
24.10 10:39:06 [Server] Server thread/DEBUG #3 src/pocketmine/network/mcpe/protocol/InventoryTransactionPacket(149): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleInventoryTransaction(pocketmine\network\mcpe\protocol\InventoryTransactionPacket object)
24.10 10:39:06 [Server] Server thread/DEBUG #2 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(132): pocketmine\Player->handleInventoryTransaction(pocketmine\network\mcpe\protocol\InventoryTransactionPacket object)
24.10 10:39:06 [Server] Server thread/DEBUG #1 src/pocketmine/Player(2354): pocketmine\level\Level->useItemOn(pocketmine\math\Vector3 object, pocketmine\item\ItemBlock object, integer 2, pocketmine\math\Vector3 object, pocketmine\Player object, boolean 1)
24.10 10:39:06 [Server] Server thread/DEBUG #0 src/pocketmine/level/Level(1797): pocketmine\block\Chest->onActivate(pocketmine\item\ItemBlock object, pocketmine\Player object)
24.10 10:39:06 [Server] Server thread/CRITICAL Error: "Call to a member function getBlock() on null" (EXCEPTION) in "src/pocketmine/block/Chest" at line 127
```
