### ISSUE TITLE
Internal Server error (after patch)

### ISSUE THREAD

**Issue by xDanub** [pmmp/PocketMine-MP#2586] opened 2018-12-16 19:57 UTC
Issue description:
Now instead of logging due to internal server error a few seconds after crafting it now does it as I transfer items into the crafting table.
Steps to reproduce the issue:
 - Start server
 - Attempt to craft a wooden button
OS and versions
PocketMine-MP: 3.5.1
PHP: I dunno where to find this ¯\_(ツ)_/¯ 
Server OS: Also I dunno sorry ¯\_(ツ)_/¯ 
Plugins
 - Tested on clean server
`
thread/CRITICAL ErrorException: "Uninitialized string offset: 8245" (EXCEPTION) in "vendor/pocketmine/binaryutils/src/Binary" at line 448
`

**Comment by dktapps** [comment] 2018-12-17 08:34
Closing due to not reproducible. If you find a reproducing method on the latest build, please describe it _exactly_ in detail so that it can be identified and debugged and the issue will be reopened.

**Closed by dktapps** 2018-12-17 08:34 UTC
