### ISSUE TITLE
EventPriority is misleading

### ISSUE THREAD

**Issue by MINTEDCLICKS** [pmmp/PocketMine-MP#5768] opened 2023-05-26 14:24 UTC
Event priorities should be renamed.

They are currently misleading as one may assume that a priority of HIGHEST means that it will execute first, when the opposite is the case.

**Comment by Nerahikada** [comment] 2023-05-26 14:27
duplicate of #5687

**Closed as completed** 2023-05-26 14:55 UTC
Labels: Resolution: Duplicate, Category: API

**Comment by dktapps** [comment] 2023-05-26 14:56
Duplicate of #5685 

(#5687 is a different issue)
