### ISSUE TITLE
Whitelist permissions ignore root permission

### ISSUE THREAD

**Issue by Wumpotamus** [pmmp/PocketMine-MP#2849] opened 2019-03-31 06:11 UTC
### Issue description
Some arguments when using the permission works, others don't unless I grant them, which defeats the permission of the "pocketmine" and "pocketmine.command" permissions
- Expected result: Using the "pocketmine" permission grants me access to use all commands
- Actual result: All commands except whitelist works.

### Steps to reproduce the issue
1. Add an attachment with the pocketmine root permission
2. Try to execute whitelist commands
3. Profit

### OS and versions

* PocketMine-MP: 3.7.1
* PHP: 7.2.15
* Server OS: Windows
* Game version: PE/Win10

### Plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by dktapps** [comment] 2019-03-31 08:10
There's no spec on this, so I can't tell you if this is intended behaviour or not.

**Comment by iZeaoGamer** [comment] 2019-03-31 11:45
Just to clarify - This isn’t intended behavior, and DKtapps will fix it soon. Thanks.

**Comment by dktapps** [comment] 2019-03-31 11:51
please don't put words in my mouth, thank you.

**Comment by iZeaoGamer** [comment] 2019-03-31 11:56
I’m just saying you’ll fix it. Problem?

**Comment by iZeaoGamer** [comment] 2019-03-31 11:58
It’s clearly a bug you need to fix, so fix it. Don’t ignore those that use your software.

**Comment by Sandertv** [comment] 2019-03-31 11:59
Nobody said it wasn't a bug and it wasn't going to be fixed. If that was the case, the issue would be closed. Please leave discussion on the forums or Discord.

**Comment by iZeaoGamer** [comment] 2019-03-31 11:59
Nah.

**Comment by iZeaoGamer** [comment] 2019-03-31 12:00
Github will do me thank you.

**Comment by dktapps** [comment] 2019-03-31 12:02
I've applied a temporary ban to @iZeaoGamer to end this stupid discussion. 

Readers: Unless you have something of value to add to the issue discussion, please shut up and go elsewhere.

**Comment by SOF3** [comment] 2019-03-31 12:05
Enabling all permissions is an unwise action whatsoever. Remember there is a `notop` default value for permissions, i.e. a permission does not necessarily imply something powerful. I recommend closing this issue as intended

**Comment by dktapps** [comment] 2019-03-31 12:06
I'm not closing this until we've identified whether or not there is a bug here.

**Comment by Wumpotamus** [comment] 2019-03-31 15:10
Regardless if it’s unwise or not, it seems like it should work. Every other permission except whitelist command applies, I don’t think that should be intended.

**Comment by dktapps** [comment] 2019-03-31 15:12
![image](https://user-images.githubusercontent.com/14214667/55290797-c0d48680-53cf-11e9-9251-5834d304d2e7.png)

**Comment by Wumpotamus** [comment] 2019-03-31 16:10
I have not overridden the whitelist permission, I just had something to grant the root node only and then tested everything to make sure it worked.

**Comment by dktapps** [comment] 2019-04-06 14:37
I cannot reproduce this issue. I need more information on this.

**Comment by Wumpotamus** [comment] 2019-04-08 02:29
I stand corrected with some of the command. All but `whitelist on` and `whitelist off` work with the code.

```php
$player->addAttachment($this->plugin, "pocketmine", true);
```

**Comment by dktapps** [comment] 2019-04-08 07:36
ok, I can see the issue. The correct permissions for whitelist on/off are `pocketmine.command.whitelist.enable` and `pocketmine.command.whitelist.disable` respectively, but the command checks for `pocketmine.command.whitelist.on` and `pocketmine.command.whitelist.off` instead.

**Closed** 2019-04-15 15:14 UTC
Labels: Category: Core, Status: Debugged
