### ISSUE TITLE
crafting issue

### ISSUE THREAD

**Issue by charliegustard** [pmmp/PocketMine-MP#246] opened 2017-01-11 06:28 UTC
### Issue description
Items CAN be crafted but then when an item is placed in an inventory slot it disappears. (but only in survival mode) get this error in console: Notice: Undefined offset: 0 in phar://C:/Users/Admin/Creative Cloud Files/Desktop/PymePE/PrymePE-Server1/PocketMine-MP.phar/src/pocketmine/Player.php on line 2656

### Steps to reproduce the issue
1. Craft any item
2. put it in an inventory slot and hold it. It disappears.

### OS and versions
1.6.2dev "Unleashed" (API 3.0.0-ALPHA2)
windows 10 and PE

**Comment by dktapps** [comment] 2017-01-11 08:58
Duplicate of #45

**Closed by dktapps** 2017-01-11 08:58 UTC
