### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by MateusBlackyOFC** [pmmp/PocketMine-MP#5896] opened 2023-07-13 21:27 UTC
Link to crashdump: https://crash.pmmp.io/view/8957687

**Comment by dktapps** [comment] 2023-07-14 12:34
How did you come across this crash?

**Comment by MateusBlackyOFC** [comment] 2023-07-30 23:23
Simply doing nothing.

**Comment by dktapps** [comment] 2023-07-31 07:56
Without reproducing steps there's nothing I can do.

If it happens a lot, try removing some of your plugins and see if you can find which one is causing the problem.

**Comment by dktapps** [comment] 2024-02-13 15:32
Closing due to lack of useful information.

**Closed as completed by dktapps** 2024-02-13 15:32 UTC
Labels: Category: Network, Resolution: Lacks Basic Information
