### ISSUE TITLE
Error showing in console and signs dissapeared

### ISSUE THREAD

**Issue by kabluinc** [pmmp/PocketMine-MP#490] opened 2017-03-31 11:35 UTC
This error is showing in console and after server restart signs go invisible. 

`Warning: Creating default object from empty value in phar://C:/Desktop/New folder (100001)/PocketMine-MP.phar/src/pocketmine/tile/Tile.php on line 145
[11:30:35] [Server thread/INFO]: [CONSOLE: Saved the world]

Notice: Undefined property: stdClass::$Text1 in phar://C:/Desktop/New folder (100001)/PocketMine-MP.phar/src/pocketmine/tile/Sign.php on line 78

Notice: Undefined property: stdClass::$Text2 in phar://C:/Desktop/New folder (100001)/PocketMine-MP.phar/src/pocketmine/tile/Sign.php on line 79

Notice: Undefined property: stdClass::$Text3 in phar://C:/Desktop/New folder (100001)/PocketMine-MP.phar/src/pocketmine/tile/Sign.php on line 80

Notice: Undefined property: stdClass::$Text4 in phar://C:/Desktop/New folder (100001)/PocketMine-MP.phar/src/pocketmine/tile/Sign.php on line 81`

### Steps to reproduce the issue

I used the MineReset plugin to reset a mine and this error showed up followed by the errors above after doing /save-all

`Notice: A non well formed numeric value encountered in C:\Desktop\New folder (100001)\plugins\MineReset-master\src\minereset\MineResetTask.php on line 63`

### OS and versions

* PocketMine-MP: 1.6.2 Dev API3/Network branch
* PHP: 7.0.14
* Server OS: Windows 10
* Game version: PE 1.0.5

### Crashdump, backtrace or other files

* ...

**Comment by dktapps** [comment] 2017-03-31 11:38
Something on your server is leaking closed Tile objects. I've seen this issue frequently, but as yet I've been unable to identify the cause of the issue.

**Comment by kabluinc** [comment] 2017-03-31 11:46
Now theres some new errors showing up.

`Notice: Trying to get property of non-object in phar://C:/Desktop/New folder (100001)/PocketMine-MP.phar/src/pocketmine/tile/Sign.php on line 78

Notice: Trying to get property of non-object in phar://C:/Desktop/New folder (100001)/PocketMine-MP.phar/src/pocketmine/tile/Sign.php on line 79

Notice: Trying to get property of non-object in phar://C:/Desktop/New folder (100001)/PocketMine-MP.phar/src/pocketmine/tile/Sign.php on line 80

Notice: Trying to get property of non-object in phar://C:/Desktop/New folder (100001)/PocketMine-MP.phar/src/pocketmine/tile/Sign.php on line 81
[11:43:55] [Server thread/CRITICAL]: Could not tick level "World": Call to a member function getName() on null
[11:43:55] [Server thread/CRITICAL]: Error: "Call to a member function getName() on null" (EXCEPTION) in "/src/pocketmine/nbt/tag/CompoundTag" at line 37
`

**Comment by kabluinc** [comment] 2017-03-31 12:08
Can confirm this error did not happen when the master branch was just updated to 1.0.4.  Testing on a 1.0.4 server, all works fine. Testing on the current branches, these errors appear

**Comment by dktapps** [comment] 2017-03-31 12:10
That's because of some measures I put in place to reduce the impact of tiles and entities being leaked. However, due to bad NBT implementation, I cannot restrict access to them once the tile is closed.

Previously you would have seen no errors, correct, but the tiles would have been silently leaked instead,

**Comment by dktapps** [comment] 2017-04-18 13:22
I haven't been able to reproduce this on a local server, but on our development server this happens very frequently. Will investigate this in more detail.

**Comment by dktapps** [comment] 2017-04-18 13:51
This issue should be resolved by the referenced commit, so I'm going to close this. If it is not, please comment with appropriate errors and/or crashdumps and the issue will be reopened.

**Closed by dktapps** 2017-04-18 13:51 UTC
Labels: Category: Core, Status: Reproduced
