### ISSUE TITLE
PlayerDropItemEvent bug

### ISSUE THREAD

**Issue by ipad54** [pmmp/PocketMine-MP#3518] opened 2020-05-20 13:34 UTC
### Issue description

- Expected result: If you cancel PlayerDropItemEvent, fill out the inventory in the creative, put items in the crafting cell, items will not drop out
- Actual result: If you cancel PlayerDropItemEvent, fill out the inventory in the creative, put items in the crafting cell, items will drop out

### Steps to reproduce the issue
1. Change you gamemode to Creative
2. fill out the inventory, put items in the crafting cell and close inventory

### OS and versions

* PocketMine-MP: 3.12.2
* PHP: 7.3
* Server OS: Linux
* Game version: PE/Win10 

### Plugins

- Plugins(0)

### Crashdump, backtrace or other files
No

**Comment by dktapps** [comment] 2020-05-20 13:54
duplicate of #3284

**Closed by dktapps** 2020-05-20 13:54 UTC
