### ISSUE TITLE
Can’t load plugins

### ISSUE THREAD

**Issue by INSANEIRON** [pmmp/PocketMine-MP#2574] opened 2018-12-15 11:15 UTC
When I used the latest pmmp it says it can’t decompress the .phar file
Here’s what I see
👍 [Server thread/CRITICAL]: ErrorException: "include(phar:///home/gs/gs/data/servers/11072116/plugins/AlwaysSpawn.phar/src/philipshilling/alwaysspawn/Loader.php): failed to open stream: phar error: Cannot open temporary file for decompressing phar archive "/home/gs/gs/data/servers/11072116/plugins/AlwaysSpawn.phar" file "src/philipshilling/alwaysspawn/Loader.php"" (EXCEPTION) in "vendor/pocketmine/spl/BaseClassLoader" at line 126
[Server thread/DEBUG]: #0 vendor/pocketmine/spl/BaseClassLoader(126): pocketmine\utils\Utils::errorExceptionHandler(integer 2, string include(phar:///home/gs/gs/data/servers/11072116/plugins/AlwaysSpawn.phar/src/philipshilling/alwaysspawn/Loader.php): failed to open stream: phar error: Cannot open temporary file for decompressing phar archive "/home/gs/gs/data/servers/11072116/plugins/AlwaysSpawn.phar" file "src/philipshilling/alwaysspawn/Loader.php", string phar:///home/gs/gs/data/servers/11072116/PocketMine-MP.phar/vendor/pocketmine/spl/BaseClassLoader.php, integer 126, array Array())
[Server thread/DEBUG]: #1 vendor/pocketmine/spl/BaseClassLoader(126): include()
[Server thread/DEBUG]: #2 (): BaseClassLoader->loadClass(string philipshilling\alwaysspawn\Loader)
[Server thread/DEBUG]: #3 (): spl_autoload_call(string philipshilling\alwaysspawn\Loader)
[Server thread/DEBUG]: #4 src/pocketmine/plugin/PluginManager(155): class_exists(string philipshilling\alwaysspawn\Loader, boolean 1)
[Server thread/DEBUG]: #5 src/pocketmine/plugin/PluginManager(320): pocketmine\plugin\PluginManager->loadPlugin(string /home/gs/gs/data/servers/11072116/plugins/AlwaysSpawn.phar, array Array())
[Server thread/DEBUG]: #6 src/pocketmine/Server(1650): pocketmine\plugin\PluginManager->loadPlugins(string /home/gs/gs/data/servers/11072116/plugins/)
[Server thread/DEBUG]: #7 src/pocketmine/PocketMine(249): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/gs/gs/data/servers/11072116/, string /home/gs/gs/data/servers/11072116/plugins/)
[Server thread/DEBUG]: #8 /home/gs/gs/data/servers/11072116/PocketMine-MP.phar(1): require(string phar:///home/gs/gs/data/servers/11072116/PocketMine-MP.phar/src/pocketmine/PocketMine.php)
[Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[Server thread/EMERGENCY]: Please upload the "/home/gs/gs/data/servers/11072116/crashdumps/Sat_Dec_15-06.11.37-EST_2018.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.

**Comment by dktapps** [comment] 2018-12-15 11:35
Duplicate of #2576

**Closed by dktapps** 2018-12-15 11:35 UTC

**Comment by INSANEIRON** [comment] 2018-12-15 11:44
What’s tmp
