### ISSUE TITLE
Wrong Event Called When Cactus Placed

### ISSUE THREAD

**Issue by thehexmor** [pmmp/PocketMine-MP#4203] opened 2021-04-30 17:17 UTC
i was trying to make a plugin then i found this . when you place a cactus block on the side of another it will not work right ? block will not get spawned . but the PlaceBlockEvent Will get Called And its not even cancelled . so how should i know that the player really placed block ?

**Comment by dktapps** [comment] 2021-04-30 17:21
Duplicate of #3719

**Closed by dktapps** 2021-04-30 17:21 UTC
