### ISSUE TITLE
Multyworld bug / remnants of the old chunks

### ISSUE THREAD

**Issue by bajimu** [pmmp/PocketMine-MP#283] opened 2017-01-21 21:35 UTC
If you wiil teleport player to other world that you can see this bug. Some parts of chunks saves on the player's client and if player want to destroy this blocks, that  they are dont dropping him. After relogin to server all bug disappears.
Php7
Kernel : the last from Mcpe_1.0 branch 
![15626013_1790360894564764_1914704028016775573_o](https://cloud.githubusercontent.com/assets/19263759/22177936/154ac0a8-e032-11e6-8819-97699d62a8e2.jpg)
![gradient_of_a_calm_sea_by_eddy_all_die_for-d5mzz0s-e1438846971544](https://cloud.githubusercontent.com/assets/19263759/22177937/154cad78-e032-11e6-80e6-0f07136ab30c.jpg)
![hv_qj0zx3ak](https://cloud.githubusercontent.com/assets/19263759/22177941/295b7c9a-e032-11e6-944f-c96078022dda.jpg)

**Comment by dktapps** [comment] 2017-01-21 21:36
Duplicate of #260

**Closed by dktapps** 2017-01-21 21:36 UTC
