### ISSUE TITLE
RakLibInterface Issue when transferring 

### ISSUE THREAD

**Issue by xZeroMCPE** [pmmp/PocketMine-MP#1270] opened 2017-08-04 05:12 UTC
### Issue description

If you try to transfer the player when interacting it will cause the server to stop its interface due to an undefined index.  This issue is caused mainly because of this [line](https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/Player.php#L3220)
It's maybe closing the player too early which. After removing it, I was not able to reproduce it. Or maybe the `sendHeldItem()` shouldn't get triggered if the player is not online. Well, try to reproduce it and see what happens.

### Steps to reproduce the issue

1. Make a basic plugin that listens on `PlayerInteractEvent`
2. Make it transfer the player to any server (doesn't matter) has to be through the `$player->transfer()`
3. Watch the transfer goes successful, but the server stopped its interface.

### OS and versions

* PocketMine-MP: b912b91 
* PHP: 7.0.3
* Server OS: Ubuntu
* Game version: Win10

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

No, you can't reproduce it without any plugins...  Only had 1 plugin that only handles the `PlayerInteractEvent`

### Crashdump, backtrace or other files
* https://hastebin.com/esoraduvoy.vbs   (Crash)
* https://hastebin.com/ejaniqesor.xml  (Example plugin)

**Comment by dktapps** [comment] 2017-08-04 08:21
Duplicate of #1239

**Closed by dktapps** 2017-08-04 08:21 UTC

**Comment by xZeroMCPE** [comment] 2017-08-04 15:58
It's not really a duplicate. Take a look at my issue, then take a look at his.

**Comment by dktapps** [comment] 2017-08-04 16:00
If you'd read the issue discussion you would see for yourself that it is indeed a duplicate. The root cause of the bug is the same.

**Comment by xZeroMCPE** [comment] 2017-08-04 20:52
@dktapps Ah, indeed.
