### ISSUE TITLE
 [Server thread/CRITICAL]: ErrorException: "Undefined offset: 0" (EXCEPTION) in "src/pocketmine/Player" at line 2883

### ISSUE THREAD

**Issue by totor29** [pmmp/PocketMine-MP#1254] opened 2017-07-28 09:10 UTC
### Issue description
Critical Error 
 [Server thread/CRITICAL]: ErrorException: "Undefined offset: 0" (EXCEPTION) in "src/pocketmine/Player" at line 2883

### Steps to reproduce the issue

PocketMine-MP_1.6.2dev-316

### OS and versions
* PocketMine-MP:  1.6.2dev-316_c1542d85_API-3.0.0

* PHP: 7.0.17
* Server OS:  Linux ns3023271.ip-151-80-230.eu 4.4.19-mod-std-ipv6-64 #1 SMP Mon Aug 22 13:05:01 CEST 2016 x86_64

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
no
PurePerms 1.4.1-dev1; BlockPets 1.1.0; AlwaysSpawn 2.2.3-dev1; SimpleAuth 1.8.1-dev1; SimpleAuthHelper 2.0.5-dev1; essentialsTP 1.1.1-dev3; ChatToDiscord 1.1.0; Parkour 1.5.3

If the issue is **not** reproducible without plugins:
?

### Crashdump, backtrace or other files

2017-07-28 [10:48:05]  [Server thread/WARNING]: Steeve_ moved wrongly! 
2017-07-28 [10:48:40]  [Server thread/CRITICAL]: ErrorException: "Undefined offset: 0" (EXCEPTION) in "src/pocketmine/Player" at line 2883 
2017-07-28 [10:48:40]  [RakLibServer thread/NOTICE]: Blocked XXX.65.22.35 for 5 seconds 
2017-07-28 [10:48:45]  [Server thread/CRITICAL]: ErrorException: "Undefined offset: 0" (EXCEPTION) in "src/pocketmine/Player" at line 2883 
2017-07-28 [10:48:45]  [RakLibServer thread/NOTICE]: Blocked XXX.65.22.35 for 5 seconds 
2017-07-28 [10:48:52]  [Server thread/CRITICAL]: ErrorException: "Undefined offset: 0" (EXCEPTION) in "src/pocketmine/Player" at line 2883

**Comment by dktapps** [comment] 2017-07-28 09:18
This must be about the 50th duplicate of #45 now

**Closed** 2017-07-28 09:18 UTC

**Comment by totor29** [comment] 2017-07-28 09:23
sorry I'm a newbies

**Comment by dktapps** [comment] 2017-07-28 09:25
too newb to use a search box?

**Comment by totor29** [comment] 2017-07-28 09:35
Sorry I will not do it again
