### ISSUE TITLE
Specified LevelDB world format version (8) is not supported by PocketMine-MP

### ISSUE THREAD

**Issue by CarmeloCampos** [pmmp/PocketMine-MP#2972] opened 2019-06-20 02:54 UTC
Link to crashdump: https://crash.pmmp.io/view/2505648

I downloaded a minecraft map, and I tried to execute it here

**Comment by Tarik02** [comment] 2019-06-20 05:01
Stable PocketMine does not support LevelDB worlds version 8.

**Comment by dktapps** [comment] 2019-06-20 07:25
Duplicate of #2930

**Closed by dktapps** 2019-06-20 07:25 UTC
