### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by ItzLightyHD** [pmmp/PocketMine-MP#3252] opened 2019-12-18 17:35 UTC
Link to crashdump: https://pastebin.com/D3hvJut4

### What happened
My PC just crashed, and while opening the server, i got this crash

**Comment by dktapps** [comment] 2019-12-18 18:01
duplicate of #3250 , your world is corrupted.

**Closed by dktapps** 2019-12-18 18:01 UTC

**Comment by ItzLightyHD** [comment] 2019-12-18 18:32
Ok, let's go to Christmas update on my server :)
