### ISSUE TITLE
Client destroying when teleported to ungenerated chunk

### ISSUE THREAD

**Issue by Eren5960** [pmmp/PocketMine-MP#4138] opened 2021-04-01 10:45 UTC
### Issue description

- Expected result: Safely teleport.
- Actual result: Client destroyed.

### Steps to reproduce the issue
1. Teleport to ungenerated chunk.
```
[12:43:24.752] [Server thread/INFO]: Eren5960 joined the game
[12:43:37.270] [Server thread/DEBUG]: [World: world] Entity 2 is in ungenerated terrain, flagging for despawn
[12:43:37.270] [Server thread/INFO]: [Eren5960: Teleported Eren5960 to 1000, 90, 1000]
[12:43:37.291] [Server thread/INFO]: [NetworkSession: Eren5960] Session closed due to Player destroyed
[12:43:37.292] [RakLibServer thread/DEBUG]: [Session: 127.0.0.1 53202] Requesting graceful disconnect because "server disconnect"
[12:43:37.315] [RakLibServer thread/DEBUG]: [Session: 127.0.0.1 53202] Client cleanly disconnected, marking session for destruction
[12:43:37.320] [Server thread/INFO]: Eren5960 left the game
```

### OS and versions

* PocketMine-MP: 4eaa600f35691fd45d1b55c58c655e94a2c4feaf
* PHP: 7.4
* Server OS: Win10
* Game version: Win10

**Comment by dktapps** [comment] 2021-04-01 11:11
Duplicate of #3947

**Closed by dktapps** 2021-04-01 11:11 UTC
