### ISSUE TITLE
WaterdogPE does not work

### ISSUE THREAD

**Issue by RadJaguar2005** [pmmp/PocketMine-MP#4577] opened 2021-11-17 00:00 UTC
I always get this error when I try to join via my proxy (WaterdogPE) 
**[Server thread/ERROR]: [NetworkSession: 127.0.0.1 46319] Bad packet (error ID 62df2f37130f): Error processing LoginPacket: JSON property "Waterdog_XUID" does not exist in object of type pocketmine\network\mcpe\protocol\types\login\ClientData**

**Comment by dktapps** [comment] 2021-11-17 00:56
Duplicate of #4473.

**Closed by dktapps** 2021-11-17 00:56 UTC

**Comment by morcheysha77** [comment] 2021-12-04 19:55
> I always get this error when I try to join via my proxy (WaterdogPE) **[Server thread/ERROR]: [NetworkSession: 127.0.0.1 46319] Bad packet (error ID 62df2f37130f): Error processing LoginPacket: JSON property "Waterdog_XUID" does not exist in object of type pocketmine\network\mcpe\protocol\types\login\ClientData**

This problem has been fixed, you can now disable this via the WaterdogPE's config.yml file

use_login_extras: true to use_login_extras: false
