### ISSUE TITLE
Player doesn't leave server when shutting down while in Form

### ISSUE THREAD

**Issue by xTornaido** [pmmp/PocketMine-MP#4821] opened 2022-02-12 00:23 UTC
### Issue description

- Expected result: Player to leave
- Actual result: Player still in server with form open.

### Steps to reproduce the issue
1. Have player open form
2. Shutdown server

### OS and versions
* PocketMine-MP: 4.2.0
* PHP: 8.0
* Using JIT: no
* Server OS: Windows 11
* Game version: Windows

### Plugins
BuilderTools v1.3.1, DEVirion v1.2.8, DevTools v1.15.0, MultiWorld v1.7.0-beta4, SiaHCF v1.0.0

- If you remove all plugins, does the issue still occur? Yes.

Possible fix: Remove forms from all players on shutdown.

**Comment by alvin0319** [comment] 2022-02-12 00:27
It is a client bug

**Comment by xTornaido** [comment] 2022-02-12 00:51
> 

It can be fixed if form is closed upon shutdown.

**Comment by AkmalFairuz** [comment] 2022-02-12 13:11
Server can't close player form

**Comment by dktapps** [comment] 2022-02-12 13:26
Duplicate of #4779

**Closed as completed by dktapps** 2022-02-12 13:26 UTC
Labels: Resolution: Duplicate, Category: Client
