### ISSUE TITLE
Crafted Items vanish.

### ISSUE THREAD

**Issue by Sonnenwerk** [pmmp/PocketMine-MP#933] opened 2017-05-21 12:48 UTC
### Issue description

Can´t build birchwood from wood, that stays persistent in the world. It can be built, but vanishes after a few seconds. The same with other crafting stuff like chest and so on. 

### Steps to reproduce the issue

1. chop tree, collect wood
2. craft something
3. wait some seconds  (leave crafting table)
4. it´s gone again

### OS and versions

* PocketMine-MP: PocketMine-MP_1.6.2dev-85_aecff7c7_API-3.0.0-ALPHA5.phar	
* PHP: 7
* Server OS: linux
* Game version: PE/Win10 (delete as appropriate): V1.09 Win10

### Crashdump, backtrace or other files

* ...

[14:25:13] [Server thread/DEBUG]: #13 (1): require(string phar:///home/s1229630/pocketmine/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

Notice: Undefined offset: 0 in phar:///home/s1229630/pocketmine/PocketMine-MP.phar/src/pocketmine/Player__64bit.php on line 2987
[14:25:13] [Server thread/DEBUG]: Packet pocketmine\network\mcpe\protocol\BatchPacket 0xfe062378da93326760e0bd942ffd6a7a8c94a0474b450bdf5d2f06c60d2c1c0c0c006fc3077d
**[14:25:13] [Server thread/CRITICAL]: Error: "Call to a member function getCount() on null" (EXCEPTION) in "/src/pocketmine/Player__64bit" at line 2989**

**Comment by dktapps** [comment] 2017-05-21 12:49
duplicate of #45

**Comment by Sonnenwerk** [comment] 2017-05-21 12:50
[14:46:16] [Server thread/DEBUG]: Tried to equip Item Birch Wood Planks (5:2)x16 but have Item Birch Wood (17:2)x4 in target slot
[14:46:16] [Server thread/DEBUG]: Unhandled MobEquipmentPacket received from Goldtaler: 0x20c5070aa00800000a0100

**Closed by dktapps** 2017-05-21 12:49 UTC
