### ISSUE TITLE
Textures do not download for most players

### ISSUE THREAD

**Issue by MihaSmit** [pmmp/PocketMine-MP#3232] opened 2019-12-13 03:08 UTC
### Issue description

There was a problem after the release of update 1.13 and the textures of most players are still not loading. Download stops at 1-2%.
Personally, when I try to log in from a PC, everything loads up instantly

### Steps to reproduce the issue
1. Try to enter the server with textures with android

### OS and versions

* PocketMine-MP: 3.11.1
* PHP: 7.3
* Server OS: last build PMMP
* Game version: PE/Win10 

### Plugins
DevTools v1.13.2, MapImageEngine v1.1.2, ScoreboardAPI v1.0.2-1, Auth v6.0.2, WallWeapons v1, StairSeat v1.4.1, gWorks v0.0.1, Apartments v1.1.2, gHLCode v1, InCoin v2.0.9, iAdminManager v1, Slapper v1.5.0, MIE_Protector v1.0.4, aSkinSaver v1.5, MagicWE v0.4.0, aFormAPI v0.1, AdminPanel v1.4.2-c2a, HeadMessage vfull, DEVirion v1.2.5-ALPHA12, RotateNPC v1, Dino v1.0.0, FormAPI v1.2.0, iPrinter v1, RespawnSelector v1.1.3, ProfileUI v4.2.0, PECollide v1, aHalfLifeCore v0.1, MultiWorld v1.5.1-beta1, EconomyAPI v2.0.9, PurePerms v1.4.0-INDEV, gFractions v2, HLapi v2.2.8

### Crashdump, backtrace or other files
![изображение](https://user-images.githubusercontent.com/16068635/70766328-fe2b4980-1d8f-11ea-8112-77ab5327347c.png)

**Comment by dktapps** [comment] 2019-12-13 08:05
duplicate of #3127, #3214 , #3213

**Closed by dktapps** 2019-12-13 08:05 UTC

**Comment by Amircoder777** [comment] 2020-05-12 16:06
Михаил, я могу дать решение.

**Comment by Amircoder777** [comment] 2020-05-12 16:07
на загрузку хоть 5000 мб

**Comment by Amircoder777** [comment] 2020-05-12 16:16
хотя я опоздал, ведь ты слил текстуры с хл, так что
