### ISSUE TITLE
Entity ticking very slow in the mili seconds...

### ISSUE THREAD

**Issue by mcpe4ever** [pmmp/PocketMine-MP#1167] opened 2017-07-04 19:53 UTC
### Issue description
Hi sorry for English..

It seem entity ticking very slow... it eats all my TPS ahead of the chunk load and network compression lag

you see the picture,
<img width="817" alt="screen shot 2017-07-04 at 1 11 18 pm" src="https://user-images.githubusercontent.com/29046229/27841460-840e4c8a-60cf-11e7-8ff6-f5cf89891956.png">

28ms to tick about 80 entities.. bad for performance

Now I try with with steadfast and the result is half (about 14ms to tick 80 entities) of what it takes PMMP... something is eating TPS when entity get ticked..  even though steadfast does all the thing pmmp do with the entitie except it use the 1.4 PM API..... (entite burns, move, flow in the water, get pick up, die after the 5 minute, moves when it is in the block... all with old pmmp api..)

maybe investigation needed in entity code..it happens in I think spike so

1 tick:
0.05 -> good
0.05 -> good
0.05 -> good
0.05 -> bad entite lag spike
etc

**Comment by dktapps** [comment] 2017-07-04 19:56
Duplicate of #954 . This was already discussed.

**Closed by dktapps** 2017-07-04 19:56 UTC

**Comment by mcpe4ever** [comment] 2017-07-04 20:00
Hi @dktapps .. im sorry but I think might be problem

even shoghic acknowledged it when steadfast was being made that there was performance problem...
https://twitter.com/shoghicp/status/606521083555135489
