### ISSUE TITLE
Console cannot read the command except english on Windows

### ISSUE THREAD

**Issue by alvin0319** [pmmp/PocketMine-MP#4556] opened 2021-11-06 03:30 UTC
### Issue description

- Expected result: What were you expecting to happen? Console shoule be able to read commands
- Actual result: What actually happened? Console cannot read commands except english

### Steps to reproduce the issue
1. Start PocketMine-MP
2. Type any command that is not english

### OS and versions

* PocketMine-MP:
```
[11:06:32.446] [Server thread/INFO]: This server is running PocketMine-MP
[11:06:32.446] [Server thread/INFO]: Server version: 4.0.0-BETA12+dev (git hash: f81c55ce6c76972f7828f17a16ea68d7c8eb37c5-dirty)
[11:06:32.446] [Server thread/INFO]: Compatible Minecraft version: 1.17.40 (protocol version: 471)
[11:06:32.446] [Server thread/INFO]: PHP version: 8.0.12
[11:06:32.446] [Server thread/INFO]: PHP JIT: disabled
[11:06:32.446] [Server thread/INFO]: Operating system: win
```
* Server OS: Windows 11 (also confirmed on Windows 10)
* Game version: This is not in-game bug

### Plugins

Plugins(0): 

- If you remove all plugins, does the issue still occur? Yes
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

### Crashdump, backtrace or other files

![image](https://user-images.githubusercontent.com/32565818/140595563-ce1118d9-767e-4f4a-b612-9f97db9eb7db.png)
![image](https://user-images.githubusercontent.com/32565818/140595579-c242ad81-2b48-4ecc-b81c-a6b55f7b1f17.png)

**Comment by dktapps** [comment] 2021-11-06 13:13
Duplicate of #2228.

**Closed by dktapps** 2021-11-06 13:13 UTC

**Comment by dktapps** [comment] 2021-11-06 13:22
FWIW, I recommend using an alternative terminal on Windows like git bash, it doesn't have this corruption issue.
