### ISSUE TITLE
addChunkPacket() on null

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [pmmp/PocketMine-MP#1557] opened 2017-11-19 11:25 UTC
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP:
* PHP:
* Server OS:
* Game version: PE/Win10 (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here 

* ...

[11:20:54] [Server thread/ERROR]: Error while unloading a chunk: Call to a member function addChunkPacket() on null
[11:20:54] [Server thread/CRITICAL]: Error: "Call to a member function addChunkPacket() on null" (EXCEPTION) in "src/pocketmine/inventory/ChestInventory" at line 90
[11:20:54] [Server thread/DEBUG]: #0 src/pocketmine/inventory/DoubleChestInventory(120): pocketmine\inventory\ChestInventory->broadcastBlockEventPacket(pocketmine\tile\Chest object, boolean )
[11:20:54] [Server thread/DEBUG]: #1 src/pocketmine/inventory/BaseInventory(399): pocketmine\inventory\DoubleChestInventory->onClose(pocketmine\Player object)
[11:20:54] [Server thread/DEBUG]: #2 src/pocketmine/Player(3803): pocketmine\inventory\BaseInventory->close(pocketmine\Player object)
[11:20:54] [Server thread/DEBUG]: #3 src/pocketmine/inventory/BaseInventory(375): pocketmine\Player->removeWindow(pocketmine\inventory\DoubleChestInventory object, boolean 1)
[11:20:54] [Server thread/DEBUG]: #4 src/pocketmine/tile/Chest(60): pocketmine\inventory\BaseInventory->removeAllViewers(boolean 1)
[11:20:54] [Server thread/DEBUG]: #5 src/pocketmine/level/format/Chunk(715): pocketmine\tile\Chest->close()
[11:20:54] [Server thread/DEBUG]: #6 src/pocketmine/level/format/io/region/McRegion(360): pocketmine\level\format\Chunk->unload(boolean 1)
[11:20:54] [Server thread/DEBUG]: #7 src/pocketmine/level/Level(2661): pocketmine\level\format\io\region\McRegion->unloadChunk(integer 26, integer 7, boolean 1)
[11:20:54] [Server thread/DEBUG]: #8 src/pocketmine/level/Level(2947): pocketmine\level\Level->unloadChunk(integer 26, integer 7, boolean 1)
[11:20:54] [Server thread/DEBUG]: #9 src/pocketmine/level/Level(693): pocketmine\level\Level->unloadChunks()
[11:20:54] [Server thread/DEBUG]: #10 src/pocketmine/Server(2372): pocketmine\level\Level->doTick(integer 22046)
[11:20:54] [Server thread/DEBUG]: #11 src/pocketmine/Server(2525): pocketmine\Server->checkTickUpdates(integer 22046, double 1511090454.6005)
[11:20:54] [Server thread/DEBUG]: #12 src/pocketmine/Server(2269): pocketmine\Server->tick()
[11:20:54] [Server thread/DEBUG]: #13 src/pocketmine/Server(2144): pocketmine\Server->tickProcessor()
[11:20:54] [Server thread/DEBUG]: #14 src/pocketmine/Server(1734): pocketmine\Server->start()
[11:20:54] [Server thread/DEBUG]: #15 src/pocketmine/PocketMine(552): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar:///root/12/PocketMine-MP.phar/, string /root/12/, string /root/12/plugins/)
[11:20:54] [Server thread/DEBUG]: #16 /root/12/PocketMine-MP.phar(1): require(string phar:///root/12/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

**Comment by dktapps** [comment] 2017-11-19 11:26
Duplicate of #1449

**Closed by dktapps** 2017-11-19 11:26 UTC

**Comment by TDMidkwhatisxd** [comment] 2017-11-19 11:33
ok, thanks ^=^
