### ISSUE TITLE
Fall calculation is not vanilla.

### ISSUE THREAD

**Issue by ghost** [pmmp/PocketMine-MP#4922] opened 2022-03-22 22:52 UTC
### Issue description

- Expected result: Fall damage should count as falling from *4.5-8 blocks, like in vanilla.
- Actual result: The fall is counted if you fall from *2.5-8 blocks.

### Steps to reproduce the issue
1. Drop, along with the jump, from 2 blocks high.
2. As in vanilla, no damage should be dealt.
- https://youtu.be/6Pj_bTGQcRI

### OS and versions

* PocketMine-MP: 4.2.4
* PHP: 8.1
* Using JIT: no
* Server OS: Arch Linux
* Game version: Any

### Plugins
- none

### Crashdump, backtrace or other files
- none

**Comment by IvanCraft623** [comment] 2022-03-22 22:56
Duplicate of #4686

**Closed as completed** 2022-03-22 23:04 UTC
Labels: Resolution: Duplicate, Category: Gameplay

**Comment by ghost** [comment] 2022-03-22 23:06
> Duplicate of #4686

Isn't that "fixed"?

**Comment by IvanCraft623** [comment] 2022-03-22 23:10
> > Duplicate of #4686
> 
> Isn't that "fixed"?

No

**Comment by dktapps** [comment] 2022-03-22 23:16
If it was fixed, it wouldn't still be open...

**Comment by ghost** [comment] 2022-03-23 15:50
> > > Duplicate of #4686
> > 
> > 
> > Isn't that "fixed"?
> 
> No

It's just that I remember seeing a commit that fixed it.
