### ISSUE TITLE
PM4: When a player is kicked, the reason is not shown to the client

### ISSUE THREAD

**Issue by IvanCraft623** [pmmp/PocketMine-MP#4592] opened 2021-11-24 01:37 UTC
### Issue description
Exactly like the title.

- Expected result: What were you expecting to happen?
The disconnection reason should be shown to the kicked client.
- Actual result: What actually happened?
Player is disconnected without showing reason

### Steps to reproduce the issue
1. Run `/kick` command with the reason specified
2. Look at the client logout screen.

### OS and versions

* PocketMine-MP: 4.0.0-BETA12
* PHP: 8.0.12
* Using JIT: disabled
* Server OS: win

### Plugins

No plugins

**Comment by dktapps** [comment] 2021-11-24 02:05
Duplicate of #4588

**Closed by dktapps** 2021-11-24 02:05 UTC
