### ISSUE TITLE
Disappearance of GUI after teleport a player.

### ISSUE THREAD

**Issue by matcracker** [pmmp/PocketMine-MP#1319] opened 2017-08-25 20:37 UTC
### Issue description

When you teleport a player with a window opened to another position, the player's GUI disappear.
EDIT:
If you teleport again the player with window opened and GUI disappeared, it will be display the blue sky.
### Steps to reproduce the issue

1. Log-in with 2 players.
2. Open a chest with a player.
3. Teleport the player with opened chest to other one.
EDIT:
4. Open again a chest with the same player who the GUI is disappeared.
5. Teleport the player again.

### OS and versions

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/7c212d3d53f9478cfd48ac1e3f930f1f6c3a4472
* PHP: 7.0
* Server OS: Windows 10
* Game version: PE/Win10 (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded? Yes

**Comment by jasonwynn10** [comment] 2017-08-25 20:46
It's because the player moves away from the source. It's the same in vanilla

**Comment by matcracker** [comment] 2017-08-25 20:47
@jasonwynn10 In vanilla works fine. The chest inventory is closed correctly and the player teleported as well.

**Comment by jasonwynn10** [comment] 2017-08-25 20:49
Oh, you didn't specify the issue

**Comment by matcracker** [comment] 2017-08-25 20:51
Because I've already talked to dktapps about this problem. I opened it just to remind him.

**Comment by vzlomka76** [comment] 2017-08-26 07:40
I can confirm. It can be fixed with removing code:  
`$this->removeAllWindows();`

**Comment by matcracker** [comment] 2017-08-26 08:09
@vzlomka76 where do you see it? 🤔

**Comment by vzlomka76** [comment] 2017-08-26 08:40
in teleport method (in Player class)

**Comment by vzlomka76** [comment] 2017-08-26 08:43
@matcracker I'm now talking about mcpe-1.2 branch.
In master branch you will delete this code from teleport method:
`foreach($this->windowIndex as $window){
				if($window === $this->inventory){
					continue;
				}
				$this->removeWindow($window);
			}`

**Comment by Muqsit** [comment] 2017-08-26 08:58
do not do that^ it might solve your problem but will create many more.

**Comment by vzlomka76** [comment] 2017-08-26 09:04
@Muqsit i know this, but I gave the reason for this bug

**Comment by AvivShopen** [comment] 2017-08-28 13:33
This will work (i think)
`$packet = new \pocketmine\network\mcpe\protocol\ContainerClosePacket();
$packet->windowid = 0;
$player->dataPacket($packet);`

**Comment by dktapps** [comment] 2017-09-02 18:14
I cannot reproduce this bug with MCPE 1.2.0.25.

**Comment by matcracker** [comment] 2017-09-02 18:15
This issue is referred to MCPE 1.1.5

**Comment by dktapps** [comment] 2017-09-02 18:16
My point is that since it doesn't occur on the beta, this is more likely to be down to a quirk in the client which has been fixed in 1.2.

**Comment by dktapps** [comment] 2017-09-02 18:17
I don't have MCPE 1.1.5, but I also cannot reproduce the bug on 1.1.4.51.

**Comment by matcracker** [comment] 2017-09-02 18:22
I will try again... But I'm sure that this happens

**Comment by AppleDevelops** [comment] 2017-09-02 18:25
I can’t reproduce this issue on 1.2 but yeah, it affects me on 1.1.

**Closed** 2017-09-21 13:27 UTC
Labels: Category: Client (all), Status: Unconfirmed
