### ISSUE TITLE
ConcretePowder: Inconsistently calling BlockFormEvent

### ISSUE THREAD

**Issue by ColinHDev** [pmmp/PocketMine-MP#5228] opened 2022-08-14 23:21 UTC
### Issue description
While working on #5226, I noticed that the `BlockFormEvent` is not always called when `ConcretePowder` forms into regular `Concrete` after touching `Water`.
It is only called if a neighbouring block changed: https://github.com/pmmp/PocketMine-MP/blob/stable/src/block/ConcretePowder.php#L46
But not if the powder block fell from a higher position and touched water while landing (or falling mid-air): https://github.com/pmmp/PocketMine-MP/blob/stable/src/block/ConcretePowder.php#L56-L58

### Steps to reproduce the issue
0. Register an event listener for the `BlockFormEvent`, so you can actually observe this.
1. Build a small tower, place water beneath and a concrete powder block above it.
2. Watch the concrete powder block turn into a `FallingBlock` entity.
3. The entity turns into a regular concrete block without the event being called.

### OS and versions

* PocketMine-MP: 5.0.0-ALPHA3, 4.7.1
* PHP: 8.0.19
* Using JIT: no
* Server OS: linux
* Game version: Win10

### Plugins
\---

### Crashdump, backtrace or other files
\---

**Comment by dktapps** [comment] 2022-08-15 13:15
I'm not sure this actually qualifies as a bug, since there isn't actually a causing block in this case. Instead, EntityBlockChangeEvent is fired for this.

**Comment by ColinHDev** [comment] 2022-08-15 16:15
Yes, there is a causing block. This is not about a `FallingBlock` turning into a regular block, but specifically about a falling `ConcretePowder` (entity) turning into a `Concrete` block, due to nearby water.
The [`tickFalling()` method](https://github.com/pmmp/PocketMine-MP/blob/next-major/src/block/ConcretePowder.php#L56-L61), which gets called [here](https://github.com/pmmp/PocketMine-MP/blob/next-major/src/entity/object/FallingBlock.php#L125) only returns a regular `Concrete`, if a water block is nearby. Because of this, a falling `ConcretePowder` can turn into a regular one without touching the ground just because it fell next to a water block.

**Comment by dktapps** [comment] 2022-08-15 16:20
The point is that this is an entity-block interaction, not a block-block interaction. The falling concrete powder block doesn't actually exist within the world grid, so BlockFormEvent can't really be applied.

**Comment by ColinHDev** [comment] 2022-08-15 19:10
My idea was, that due to there being a block instance, `tickFalling()` could call the BlockFormEvent and return null if it got cancelled. But I understand your point that calling it would be wrong because the block does not exist.
Yes, EntityBlockChangeEvent exists but using it for this particular use case... well, we end up right at the motivation for #5226.
But feel free to close this, if you think it's fine as it is.

**Comment by dktapps** [comment] 2022-08-16 13:42
If we were to use BlockFormEvent for this, you would see a water block (old state) randomly form into concrete (new state) for no obvious reason, with a water block as the cause, since there's no way to connect the falling block to BlockFormEvent. The behaviour would already differ from the behaviour of water touching concrete powder. I'm unconvinced that this would be any better.

**Comment by dktapps** [comment] 2022-09-28 22:04
Closing this since it's impractical and already covered by other events.

**Closed as completed by dktapps** 2022-09-28 22:04 UTC
Labels: Category: API, Resolution: Declined
