### ISSUE TITLE
Durable Class

### ISSUE THREAD

**Issue by LolNova** [pmmp/PocketMine-MP#2009] opened 2018-02-11 16:56 UTC
What I expected : For the item to be unbreakable
What happened : Item still breaks

* PocketMine-MP: PocketMine-MP version 1.7dev-698 "[REDACTED]" (API 3.0.0-ALPHA11)
* PHP: 7.2
* Game version: PE

- Tested on a clean server with only the plugin and it still didn't work
If the issue is **not** reproducible without plugins:

Code:

item = Item::get(Item::DIAMOND_PICKAXE);

  if($item instanceof Durable){
   $item->setUnbreakable();
}

**Comment by dktapps** [comment] 2018-02-11 16:57
Please provide example code to demonstrate what you're doing. Code > words.

Also, you can edit your issue, so no need to create a new one next time.

**Comment by LolNova** [comment] 2018-02-11 17:00
Done

**Comment by dktapps** [comment] 2018-02-11 17:06
```php
public function onPlayerJoin(PlayerJoinEvent $event){
		$p = $event->getPlayer();
		$item = ItemFactory::get(Item::DIAMOND_AXE);
		if($item instanceof Durable){
			$item->setUnbreakable();
			var_dump($item->isUnbreakable());
		}

		$p->getInventory()->setItemInHand($item);
		$p->getInventory()->sendHeldItem($p);
}
```
works for me.

Closing due to not reproducible. Please seek code assistance on the forums; do not use this issue tracker for support requests.

**Closed by dktapps** 2018-02-11 17:06 UTC
Labels: Category: Plugin API, Status: Unconfirmed

**Comment by LolNova** [comment] 2018-02-11 17:09
Ok thanks
