### ISSUE TITLE
load level with other worlds block

### ISSUE THREAD

**Issue by ibookcc** [pmmp/PocketMine-MP#289] opened 2017-01-24 06:28 UTC
### Issue description
when you leaving for yours world to another world.
some chunks top you head, are the old world's .()

### Steps to reproduce the issue
1. load worlds (make sure one world spawn-place's Z is under the other world spawn-place'Z)
2. join one world
2. leaving for another world which spawn-place's Z is less.
3. look at you top 

### OS and versions
* PocketMine-MP: 1.0.2
* PHP: 7.0.2 
* Server OS: centOs
* Game version: PE and Win10

**Comment by robske110** [comment] 2017-01-24 06:29
Do you really have the latest PM? This was fixed

**Comment by yescallop** [comment] 2017-01-24 06:42
It's not fixed. Sometimes that hack is useless.

**Comment by dktapps** [comment] 2017-01-24 08:53
If you don't start paying attention to the [contribution guidelines](CONTRIBUTING.md) you're getting a permaban.

**Comment by dktapps** [comment] 2017-01-24 08:53
Duplicate of #260

**Closed by dktapps** 2017-01-24 08:53 UTC

**Comment by ibookcc** [comment] 2017-01-25 13:26
@dktapps I don't no sorry, but i can't download from jenkins for a long time.The jenkins always say it offline and display Error 522 Ray ID: 326c0a0a188c540e • 2017-01-25 13:23:21 UTC;

**Comment by ibookcc** [comment] 2017-01-25 13:27
@dktapps So, how can i get the latest PM

**Comment by dktapps** [comment] 2017-01-25 13:28
Compile your own or run from source, but stop spamming. For the final time, _this is not a support forum._
