### ISSUE TITLE
Block::onEntityInside() method is not called when the entity is on the block

### ISSUE THREAD

**Issue by Govdim** [pmmp/PocketMine-MP#4361] opened 2021-08-11 15:13 UTC
### Issue description

- Expected result: entity takes damage when standing on a magma block
- Actual result: entity does not take damage when standing on a magma block

### OS and versions
* PocketMine-MP: 4.0.0
* PHP: 8.0
* Using JIT: no
* Server OS: Ubuntu 20.04
* Game version: Android/iOS/Win10/Xbox/PS4/Switch

### Plugins
NO

**Comment by dktapps** [comment] 2021-08-11 15:19
The title and the issue body are two different issues. The title is a non-issue (works as intended), and the issue body is a duplicate of #2041.

**Closed by dktapps** 2021-08-11 15:19 UTC
