### ISSUE TITLE
Mobs won't spawn

### ISSUE THREAD

**Issue by TheRasPiGuy** [pmmp/PocketMine-MP#2801] opened 2019-03-08 01:13 UTC
### Issue description

- Expected result: Mobs spawn
- Actual result: Mobs won't spawn (with spawn egg or naturally)

### Steps to reproduce the issue
1. Load world, and try spawning with a spawn egg

### OS and versions
* PocketMine-MP: PocketMine-MP 3.6.4 for Minecraft: Bedrock Edition v1.9.0 (protocol version 332)
* PHP: 7.2.13.0
* Server OS: Windows 10 Build 17134.590
* Game version: PE & Win10

**Comment by Anders233** [comment] 2019-03-08 01:32
I recommend you use this plugin: PureEntitiesX
https://poggit.pmmp.io/p/PureEntitiesX/0.6.0

**Comment by ZizzyZizzy** [comment] 2019-03-08 01:59
Please read this:
https://pmmp.readthedocs.io/en/rtfd/faq/playing/missingfeatures.html

and then close this. No need to waste the developers' time on something that can be answered by google in 5 seconds.

http://lmgtfy.com/?q=pocketmine+no+mobs+spawning

**Comment by 95CivicSi** [comment] 2019-03-08 02:39
This is a duplicate of 
https://github.com/pmmp/PocketMine-MP/issues/123
https://github.com/pmmp/PocketMine-MP/issues/902
https://github.com/pmmp/PocketMine-MP/issues/1042
https://github.com/pmmp/PocketMine-MP/issues/1139

Natural mob spawning and mob AI have not been added yet.  You may be able to find a plugin that can help you with this until it is added.

**Closed** 2019-03-08 08:11 UTC
Labels: Category: Gameplay, Resolution: Invalid

**Comment by Levi68DJ** [comment] 2022-03-28 17:09
I used PureEntitiesX and it say "Nested permissions are not longer supported". What should i do?
