### ISSUE TITLE
Import map PC to PMMP

### ISSUE THREAD

**Issue by towuk118** [pmmp/PocketMine-MP#3114] opened 2019-09-04 22:44 UTC
1. i copy and paste world to PMMP server and **not all blocks converted** from JAVA to PE ids...
2. Please create import correct for PMMP from JAVA world (**region** folder and **level.dat** file)
dont crasher on import, just not correct convert blocks!

### OS and versions

* PocketMine-MP:
This server is running PocketMine-MP 3.9.4 for Minecraft: Bedrock Edition v1.12.0 (protocol version 361)

* PHP: 7.3 64bit (latest jenkins)
* Server OS: win10 pro 64bit
* Game version: PE/Win10 (delete as appropriate)

### Plugins
clear server

**Comment by dktapps** [comment] 2019-09-05 07:36
duplicate of #2799

**Closed by dktapps** 2019-09-05 07:36 UTC
