### ISSUE TITLE
inventory clearAll or remove 

### ISSUE THREAD

**Issue by SurvivalHive** [pmmp/PocketMine-MP#2200] opened 2018-05-21 16:28 UTC
### Issue description

if u have a damage tool in your hand it
does not delete after using clearAll()

if you cancell the drop event and try to delete the block/item with remove function
is doesnt work anymore

### Steps to reproduce the issue
hold an item and try to remove it with the inventory->remove function

use a tool with damage and hold it in hand then
try the clearall event

* PocketMine-MP: #1034 
* PHP: 7
* Server OS: debian
* Game version: PE/Win10 (delete as appropriate)

**Comment by Muqsit** [comment] 2018-05-21 16:50
Might be duplicate of https://github.com/pmmp/PocketMine-MP/issues/2010

**Comment by SurvivalHive** [comment] 2018-05-21 17:30
dont see it, thx...

**Closed** 2018-05-21 17:31 UTC
