### ISSUE TITLE
Malformed messages when players join or leave the server

### ISSUE THREAD

**Issue by YTiStrafeNubzHD** [pmmp/PocketMine-MP#2001] opened 2018-02-08 17:18 UTC
### Issue description

Since the new version when a player joins or leaves the server the message is formed incorrectly. I think the issue was produced with commit 906d7eb1767401e1b925712cd5f0ba1871acdd0d (also see comments)

- Expected result: What were you expecting to happen? 
Message: _ExamplePlayer joined the game_ and _ExamplePlayer left the game_

- Actual result: What actually happened? 
Message: _{%0} joined the game_ and _{%0} left the game_

### Steps to reproduce the issue

1. start the server
2. wait for a player to join

### OS and versions

* PocketMine-MP: PocketMine-MP 1.7dev-699 (54f7a88fbb2e0eb1cb69d9b67a378af192adec94)
* PHP: 7.2.0RC4
* Server OS: Linux, linux
* Game version: PE/Win10

### Plugins
Not tested without plugins
Plugins (22): MagicWE v0.4.0, DevTools v1.12.9, ZipPluginLoader v1.2.1, EssentialsPE v2.0.0, VoteReward v3.0.2, PocketGuard v2.1.1, ItemCasePE v1.2.1-1, AllAPILoader v1.0.0, BlockSniper v2.3.0, iProtector v4.0.3#3.1b, PixelgamesTapToDo v3.1#, KillBearBoyshk v3.0.0, PortalTP v1.0.0-PortalTP, essentialsTP v1.2.0-4, EconomyAPI v5.7.1-4, PurePerms v1.4.1-3, SimpleAuth v2.1.2-4, SimpleAuthHelper v2.0.6-5, ManyWorlds v2.1.0, FactionsProBeta v1.4.5-9, AdvancedKits v5.1.0-9, PureChat v1.4.10-4

### Crashdump, backtrace or other files
X

**Comment by dktapps** [comment] 2018-02-08 17:20
As already mentioned on the referenced commit, I tested this and it does not reproduce on my local server. Additionally it is unlikely that that would make any difference since it is just a namespace refactor.

Please ensure that your submodules are up to date using `git submodule update` and try to reproduce again.

**Comment by dktapps** [comment] 2018-02-08 17:38
I'm closing this as a plugin issue since it does not reproduce on a clean server.

**Closed** 2018-02-08 17:38 UTC
Labels: Category: Other, Status: Unconfirmed

**Comment by YTiStrafeNubzHD** [comment] 2018-02-09 18:02
ok I understand 👍  @dktapps 
and thank you very much, that solves the problem @zKoz210
