### ISSUE TITLE
Add normal capes to Pocketmine

### ISSUE THREAD

**Issue by MrBlasyMSK** [pmmp/PocketMine-MP#4908] opened 2022-03-18 19:11 UTC
## Description
I wish you could show the capes you have in the dressing room.

## Alternative methods
Video showing that it doesn't work in Pocketmine and it does in a normal world
https://streamable.com/pn4efz

**Comment by dktapps** [comment] 2022-03-18 19:17
Duplicate of #4907

**Closed as completed by dktapps** 2022-03-18 19:17 UTC
Labels: Resolution: Duplicate, Category: Gameplay, Category: Client
