### ISSUE TITLE
(api3/blocks) Worlds don't save

### ISSUE THREAD

**Issue by LCraftPE** [pmmp/PocketMine-MP#1261] opened 2017-07-30 13:44 UTC
### Issue description
I noticed that when I place blocks on a PMAnvil world (I have not yet tested with any other type of world) just before restarting the server, the changes are not saved.

### Steps to reproduce the issue
1. Create a PMAnvil world 
2. Place blocks
3. Restart the server just after
4. Return on the server after the restart

### OS and versions
* PocketMine-MP: 1.6.2dev-318 (branch api3/blocks)
* PHP: 7.1.6
* Server OS: Linux
* Game version: PE

### Plugins
* DevTools

### Crashdump, backtrace or other files
N/A

**Comment by dktapps** [comment] 2017-07-30 13:47
I cannot reproduce this and your versions are invalid. Closing.

**Closed by dktapps** 2017-07-30 13:47 UTC

**Comment by jasonwynn10** [comment] 2017-07-30 17:36
did you make sure to leave world autosaving on?
