### ISSUE TITLE
Error on crafting in classic mode

### ISSUE THREAD

**Issue by Assblocker** [pmmp/PocketMine-MP#351] opened 2017-02-12 06:24 UTC
### Issue description

Getting this error when trying to craft in classic mode
'Notice: Undefined offset: 0 in E:\PocketMine-MP\src\pocketmine\Player.php on line 3276'
### Steps to reproduce the issue

1. Just try to craft in classic mode on mcpe v1.0.3
2. ...

### OS and versions

* PocketMine-MP: 6dc6e32
* PHP: 7.0.14
* Server OS: Linux Ubuntu
* Game version: McPE v1.0.3

### Crashdump, backtrace or other files

* ...

**Comment by dktapps** [comment] 2017-02-12 09:43
Duplicate of #45

**Closed by dktapps** 2017-02-12 09:43 UTC
