### ISSUE TITLE
birch_door problem

### ISSUE THREAD

**Issue by erickwoc** [pmmp/PocketMine-MP#167] opened 2016-12-15 06:18 UTC
### Issue description

When I using a birch door (ID: 194), strange things happen like this
![](http://ww1.sinaimg.cn/mw690/b0ea9931gw1fargdnkzf8j21120ku46u.jpg)
![](http://ww3.sinaimg.cn/mw690/b0ea9931gw1fargcwy0ukj21120kutgr.jpg)
![](http://ww3.sinaimg.cn/mw690/b0ea9931gw1fargdzqoqnj21120ku41j.jpg)
I can't put the door on dirt block (haven't test other blocks yet). And it can't work properly either. 
I place it on dirt block, and then half of the door seems to be disappeared. I try to open it and it just disappears. Then I looked into my Inventory, that door is still there, just like I've never used it. 
    First I thought it might be the network problem, but no matter which network I'm in - LTE or Wi-Fi, it just looks like the same. 

### Steps to reproduce the issue

1. ... Get a birch door (ID: 194)
2. ... Place it on dirt block (ID: 3)

### OS and versions

* PocketMine-MP: PocketMine-MP_1.6.1dev-115_e790573f_API-2.1.0.phar 
[link](https://jenkins.pmmp.io/job/PocketMine-MP/lastSuccessfulBuild/artifact/PocketMine-MP_1.6.1dev-115_e790573f_API-2.1.0.phar)
* PHP: PHP 5.6.27-0+deb8u1 (cli) (built: Oct 15 2016 15:53:28)
* Server OS: Debian 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux
* Game version: PE v0.16.2 on iOS 10.1.1 (iPhone 6s)

### Crashdump, backtrace or other files

* ...

**Comment by dktapps** [comment] 2016-12-15 07:48
Thanks for the report, but this is not a bug, it's simply Not Implemented.

**Comment by dktapps** [comment] 2017-03-09 21:14
#336 provides a better overview of non-implemented stuff, will close this.

**Closed by dktapps** 2017-03-09 21:14 UTC
Labels: Category: Gameplay, Status: Not Implemented
