### ISSUE TITLE
Cancelling PlayerItemConsumeEvent will still give effects

### ISSUE THREAD

**Issue by sero583** [pmmp/PocketMine-MP#3707] opened 2020-07-16 19:52 UTC
### Issue description

- Expected result: When cancelling the event (e.g. Gold Apple) should not give extra gold hearts.
- Actual result: Cancelling will stop the item getting removed/stack count getting lowered, but not stop giving the player the effect

### Steps to reproduce the issue
1. Cancel PlayerItemConsumeEvent
2. Eat golden apple
3. You will still receive the effects, without item count going down/item getting removed

### OS and versions

* PocketMine-MP: PocketMine-MP 3.14.2+dev
* PHP: 7.3
* Server OS: Windows 10

**Comment by dktapps** [comment] 2020-07-16 21:09
this sounds to me like a client-side prediction bug. I don't think your PR will do anything (as I already commented on there).

**Comment by sero583** [comment] 2020-07-17 15:31
After a lot of tests I noticed, it was some kind of lag or luck whatever but this seems to be very rare. I doubt this is worth a issue, that's why I'm closing it.

**Comment by dktapps** [comment] 2020-07-17 15:44
I'd rather this stays open until a maintainer investigates it. Happening rarely doesn't mean there isn't a bug.

**Comment by dktapps** [comment] 2021-06-26 20:25
I'm closing this since I've never been able to reproduce it.

**Closed by dktapps** 2021-06-26 20:25 UTC
Labels: Category: Gameplay, Status: Unconfirmed
