### ISSUE TITLE
Wrong block showing destruction time

### ISSUE THREAD

**Issue by udwarf** [pmmp/PocketMine-MP#1124] opened 2017-06-21 18:32 UTC
Server wrongly displays block breaking process/. 
For example on the diamond block cracks are shown for 8 seconds instead of 25.

Looks like server makes mistake by calculating block damage state or block removing time
when clients sends  PlayerActionPacket with action ACTION_CONTINUE_BREAK

### Steps to reproduce the issue

1. place diamond_block
2. start to break it with bare hands
3. Cracks appears on the block
    in 8 seconds it will be show like block is broken, but the block appears back without cracks
4. continue to break the block with bare hands. No cracks will appear on the block
5. in 17 seconds block will dissapear

### OS and versions
* PocketMine-MP: PocketMine-MP 1.6.2dev 「Unleashed」 implementing API version 3.0.0-ALPHA5 for Minecraft: PE v1.1.0.55 (protocol version 113)
commit 86742fcf3008daa2197469af7e8d1af43ae727d9
* PHP: PHP 7.0.3 (cli) (built: Feb  2 2016 14:38:29) ( ZTS )
* Server OS: Windows 8
* Game version: Tested on Win10 and Android versions

**Comment by dktapps** [comment] 2017-06-21 18:33
Duplicate of #211

**Closed by dktapps** 2017-06-21 18:33 UTC
