### ISSUE TITLE
Bug in Creative

### ISSUE THREAD

**Issue by ruslantopchik** [pmmp/PocketMine-MP#3652] opened 2020-06-28 19:51 UTC
Issue description

- Expected result: If you fill in the inventory in GAMEMODE 1 completely, and put the item in the place for crafting in the inventory, then after closing the inventory, it will fall out

- Actual result: If you fill in the inventory in GAMEMODE 1 completely, and put the item in the place for crafting in the inventory, then after closing the inventory, it will fall out

Steps to reproduce the issue:

1. Fill inventory in GAMEMODE 1 fully, and in place for crafting put the item, close the inventory and the item will fall out

OS and versions
* PocketMine-MP: 3.14.0
* PHP: 7.3
* Server OS: Ubuntu
* Game version: PE/Win10

Plugins
None

Crashdump, backtrace or other files
None

**Comment by dktapps** [comment] 2020-06-28 20:13
duplicate of #3284

**Closed by dktapps** 2020-06-28 20:13 UTC
