### ISSUE TITLE
Can't break blocks as op in spawn protection.

### ISSUE THREAD

**Issue by thebigsmileXD** [pmmp/PocketMine-MP#245] opened 2017-01-10 18:20 UTC
### Issue description

I directly used the installer and didn't touch the pocketmine.yml/server.properties.
On the question Spawn protection i've used '-1'

Now as OP i can build in a certain circle around the spawn, but when i break blocks and 'tap' the position/adjacent blocks the block reappears.
### Steps to reproduce the issue

1. Installer: -1 on spawn protection
2. place and break blocks

### OS and versions

* PocketMine-MP: Commit 8f797442b3c6d207bca1a10834cadecfa53b89ef
[18:17:06] [Server thread/INFO]: This server is running PocketMine-MP 1.6.2dev ÒÇîUnleashedÒÇì implementing API version 3.0.0-ALPHA2 for Minecraft: PE v1.0.0.16 (protocol version 100)
* PHP: PHP 7.0.13 (cli) (built: Nov  8 2016 13:33:54) ( ZTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.13, Copyright (c) 1999-2016, by Zend Technologies
* Server OS: Windows, using PowerShell script

### Crashdump, backtrace or other files

* properties attached below.
```#Properties Config file
#Tue Jan 10 18:17:41 UTC 2017
motd=Minecraft: PE Server
server-name=Minecraft: PE Server
server-port=19132
gamemode=1
max-players=5
spawn-protection=-1
white-list=off
enable-query=on
enable-rcon=off
announce-player-achievements=on
allow-flight=off
spawn-animals=on
spawn-mobs=on
force-gamemode=off
hardcore=off
pvp=on
difficulty=1
generator-settings=
level-name=world
level-seed=
level-type=DEFAULT
rcon.password=75u4ukHy2/
auto-save=on
```

**Comment by Infernus102** [comment] 2017-01-13 15:01
yes! same thing happening with me

**Comment by Infernus102** [comment] 2017-01-13 15:02
breaking/placing not working, the destroyed block reappears when something else is placed there.

**Comment by dktapps** [comment] 2017-01-31 19:21
Closing due to not reproducible.

**Closed by dktapps** 2017-01-31 19:21 UTC
Labels: Category: Core, Category: Gameplay, Status: Unconfirmed
