### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by gamegam** [pmmp/PocketMine-MP#5915] opened 2023-07-18 20:06 UTC
Link to crashdump: 
[04:05:12.874] [Server thread/ERROR]: [NetworkSession: ::1 54833] Bad packet: Error processing LoginPacket: JSON property "sandboxId" does not exist in object of type pocketmine\network\mcpe\protocol\types\login\AuthenticationData

### Additional comments (optional)

php 8.1

pocketmine-mp: 5.3.1

**Comment by JavierLeon9966** [comment] 2023-07-18 20:27
Duplicate of https://github.com/pmmp/PocketMine-MP/issues/5914

**Closed as completed** 2023-07-18 20:28 UTC
Labels: Resolution: Duplicate
