### ISSUE TITLE
Add a UserException class

### ISSUE THREAD

**Issue by SOF3** [pmmp/PocketMine-MP#3472] opened 2020-05-07 04:37 UTC
## Description
Create a `UserException` class that plugins can throw when a user mistake (such as misconfiguration, mismatched plugin dependency, incorrect installation) occurred.

Depending on the final decision on #2826, throwing this exception during `onEnable` may either disable a related plugin or stop the server.

Otherwise, `UserException` must not be caught by any code, and should fall back straight to the lifecycle primitives in Server.php to get displayed as a final critical error.

## Justification
Right now plugins use `PluginManager->disablePlugin($this)` in `onEnable` all the time, sometimes incorrectly using `setEnabled(false)`, sometimes forgetting `return;`, etc. General case exceptions tend to be user-unfriendly, and hence plugins would reinvent their own version of error reporting with a lot of `Logger->error()` boilerplate.

A standard exception to throw when a mistake that the user should understand and handle directly would reduce boilerplate. Furthermore, if PocketMine displays these error messages in a more eye-catching manner (in particular, without stack trace, with background color, with line paddings, etc.; see composer error formatting for comparison), developers would have more incentive to use this, and eventually converge the ecosystem's user error handling.

## Alternative methods
Reuse `PluginException`. However `PluginException` is not guaranteed user-friendly as it tends to contain technical information.

Merge with `CommandException`. However this is a slippery slope. If a command handler sends error message to user when `UserException`, would users expect `PlayerMoveEvent` handlers to send error message to the user when the player moves. In this case, which player should the event be sent to when an `InventoryTransactionEvent` happens?

**Comment by dktapps** [comment] 2020-05-19 09:53
Non-specific `UserException` would be little better than `\Exception` in terms of its usefulness.

**Comment by dktapps** [comment] 2021-10-30 20:06
This appears to be a duplicate of #2671.

**Closed by dktapps** 2021-10-30 20:06 UTC
Labels: Category: API
