### ISSUE TITLE
Raklib Session closed incorrectly

### ISSUE THREAD

**Issue by Blackjack200** [pmmp/PocketMine-MP#4369] opened 2021-08-13 12:53 UTC
### Issue description

- Expected result: The server-side session should `Client cleanly disconnected, marking session for destruction`
- Actual result: The server-side session always `Timeout during graceful disconnect, forcibly closing session` when client use the quit button to quit game

### Steps to reproduce the issue
1. Join server(enable debug)
2. Quit Game (pause, quit game button)
3. look at the debug message
4. Rejoin and then use kick command to kick player
5. look at the debug message
6. the debug message should always be same, but in fact, no.

### OS and versions
* PocketMine-MP: 4.0.0
* PHP: 8.0.9
* Using JIT: no
* Server OS: MacOS
* Game version: Android

### Plugins
Plugins (1): DevTools v1.15.0+dev

#### kick
```
[20:50:17.456] [Server thread/INFO]: IPlayfordev 退出了游戏
[20:50:17.457] [RakLib thread/DEBUG]: [Session: 192.168.86.100 40054] Requesting graceful disconnect because "server disconnect"
[20:50:17.461] [Server thread/INFO]: [CONSOLE: 已將 IPlayfordev 踢出游戏]
[20:50:17.475] [RakLib thread/DEBUG]: [Session: 192.168.86.100 40054] Client cleanly disconnected, marking session for destruction
[20:50:17.584] [Server thread/DEBUG]: [Player: IPlayfordev] Destroyed by garbage collector
```

#### Common Quit

```
[20:51:18.867] [Server thread/INFO]: IPlayfordev 加入了游戏
[20:51:20.280] [RakLib thread/DEBUG]: [Session: 192.168.86.100 40054] Requesting graceful disconnect because "client disconnect"
[20:51:20.280] [Server thread/INFO]: IPlayfordev 退出了游戏
[20:51:20.286] [Server thread/INFO]: [NetworkSession: IPlayfordev] Session closed due to client disconnect
[20:51:20.588] [Server thread/DEBUG]: [Player: IPlayfordev] Destroyed by garbage collector
[20:51:30.284] [RakLib thread/DEBUG]: [Session: 192.168.86.100 40054] Forcibly disconnecting session due to "timeout"
```

**Comment by Blackjack200** [comment] 2021-08-13 12:53
related to #4311

**Comment by dktapps** [comment] 2021-08-13 18:30
I'm not able to reproduce this.

**Comment by Blackjack200** [comment] 2021-08-14 01:41
> I'm not able to reproduce this.

1. (Client quit commonly)
2. Server handle the notification
3. flag for disconnect(disconnecting)
4. client is disconnect already, the sendLayer and receiveLayer don't need to update(update always fail because client don't read/write packet anymore)
5.  session detected session timeout and close forcibly

**Comment by dktapps** [comment] 2021-08-14 01:59
If sendLayer and recvLayer don't need to update, false is returned and graceful disconnect completes. The only scenario I can see this happening in is if there's something left for the send/recv layers to do when the disconnect arrives, but I haven't been able to reproduce the issue anyway, even with that in mind.

**Comment by Blackjack200** [comment] 2021-08-14 02:51
Session.php
# debug code
```php
if($this->state === self::STATE_DISCONNECTING){
			//by this point we already told the event listener that the session is closing, so we don't need to do it again
			$b1 = $this->sendLayer->needsUpdate();
			$b2 = $this->recvLayer->needsUpdate();
			var_dump(null);
			var_dump($b1, $b2);
			$b = !$b1 and !$b2;
			if($b){
				$this->state = self::STATE_DISCONNECTED;
				$this->logger->debug("Client cleanly disconnected, marking session for destruction");
				return;
			}elseif($this->disconnectionTime + 2 < $time){
				$this->state = self::STATE_DISCONNECTED;
				$this->logger->debug("Timeout during graceful disconnect, forcibly closing session");
				return;
			}
		}
```
## client disconnect
always 
```
[10:48:10.278] [Server thread/INFO]: IPlayfordev joined the game
[10:48:12.157] [RakLib thread/DEBUG]: [Session: 192.168.86.100 45296] Requesting graceful disconnect because "client disconnect"
NULL
bool(true)
bool(true)
[10:48:12.159] [Server thread/INFO]: IPlayfordev left the game
NULL
bool(true)
bool(false)
[10:48:12.165] [Server thread/INFO]: [NetworkSession: IPlayfordev] Session closed due to client disconnect
NULL
bool(true)
bool(false)
NULL
bool(true)
bool(false)
.....................................................(deleted message due to spam)
[10:48:12.451] [Server thread/DEBUG]: [Player: IPlayfordev] Destroyed by garbage collector
NULL
bool(true)
bool(false)
NULL
bool(true)
bool(false)
NULL
bool(true)
bool(false)
NULL
bool(true)
bool(false)
NULL
bool(true)
bool(false)
.....................................................(deleted message due to spam)
[10:48:14.159] [RakLib thread/DEBUG]: [Session: 192.168.86.100 45296] Timeout during graceful disconnect, forcibly closing session
```

## Kicked by admin
```
[10:45:20.868] [Server thread/INFO]: [NetworkSession: IPlayfordev] Session closed due to Kicked by admin.
[10:45:20.868] [Server thread/INFO]: IPlayfordev left the game
[10:45:20.870] [RakLib thread/DEBUG]: [Session: 192.168.86.100 45296] Requesting graceful disconnect because "server disconnect"
NULL
bool(true)
bool(false)
[10:45:20.871] [Server thread/INFO]: [CONSOLE: Kicked IPlayfordev from the game]
NULL
bool(true)
bool(false)
NULL
bool(true)
bool(false)
NULL
bool(false)
bool(false)
[10:45:20.886] [RakLib thread/DEBUG]: [Session: 192.168.86.100 45296] Client cleanly disconnected, marking session for destruction
[10:45:21.078] [Server thread/DEBUG]: [Player: IPlayfordev] Destroyed by garbage collector
```

**Comment by dktapps** [comment] 2021-09-29 14:56
Closing as duplicate of pmmp/RakLib#120.

**Closed by dktapps** 2021-09-29 14:56 UTC
Labels: Status: Unconfirmed, Category: Network
