### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by ManiakMCPE** [pmmp/PocketMine-MP#3088] opened 2019-08-10 04:09 UTC
"touch(): Unable to create file /worlds/is-0.48316500 1565397754/region/r.0.-1.mcapm because Too many open files" (EXCEPTION) in "src/pocketmine/level/format/io/region/RegionLoader" at line 89
10.08 00:42:41 [Server] Server thread/DEBUG #0 (): pocketmine\utils\Utils::errorExceptionHandler(integer 2, string[153] touch(): Unable to create file /worlds, string[119] phar:///jar/pocketmine/pocketmine.phar/src/pocketmine/, integer 89, array[1])
10.08 00:42:41 [Server] Server thread/DEBUG #1 src/pocketmine/level/format/io/region/RegionLoader(89): touch(string[94] /worlds/is-0.48316500 1565397754/regio)
10.08 00:42:41 [Server] Server thread/DEBUG #2 src/pocketmine/level/format/io/region/McRegion(349): pocketmine\level\format\io\region\RegionLoader->open()
10.08 00:42:41 [Server] Server thread/DEBUG #3 src/pocketmine/level/format/io/region/McRegion(388): pocketmine\level\format\io\region\McRegion->loadRegion(integer 0, integer -1)
10.08 00:42:41 [Server] Server thread/DEBUG #4 src/pocketmine/level/format/io/BaseLevelProvider(170): pocketmine\level\format\io\region\McRegion->readChunk(integer 0, integer -1)
10.08 00:42:41 [Server] Server thread/DEBUG #5 src/pocketmine/level/Level(2826): pocketmine\level\format\io\BaseLevelProvider->loadChunk(integer 0, integer -1)
10.08 00:42:41 [Server] Server thread/DEBUG #6 src/pocketmine/level/Level(2419): pocketmine\level\Level->loadChunk(integer 0, integer -1, boolean )
10.08 00:42:41 [Server] Server thread/DEBUG #7 src/pocketmine/level/Level(2454): pocketmine\level\Level->getChunk(integer 0, integer -1, boolean )
10.08 00:42:41 [Server] Server thread/DEBUG #8 src/pocketmine/level/generator/PopulationTask(53): pocketmine\level\Level->getAdjacentChunks(integer 0, integer 0)
10.08 00:42:41 [Server] Server thread/DEBUG #9 src/pocketmine/level/Level(3133): pocketmine\level\generator\PopulationTask->__construct(object pocketmine\level\Level, object pocketmine\level\format\Chunk)

I have tried increasing ram all the way to 30GB and it hasn't helped with this crash.

**Comment by Encritary** [comment] 2019-08-10 04:30
That's an issue tracker, not a support forum.

Your problem is related to the Linux's open file limit, not PMMP.
You can temporarily increase it by executing:
``# sysctl -w fs.file-max=N``
Where N is your number.

To increase it permanently, edit the same setting in ``/etc/sysctl.conf``.

**Comment by SOF3** [comment] 2019-08-10 05:05
There is most likely a plugin that leaks resources, opening files without closing. PocketMine itself most likely does not leak resources, since you're the first person to report such an issue after quite a while (which means your plugins are the most likely cause).

Another possible reason is that you have to many players scattered in different parts of the world, then @Encritary's advice is relevant. But that is an unlikely reason. Check your plugins.

Until you have evidence of reproducing this when the server is at low load without plugins, I am marking this as a plugin-caused issue.

**Closed by SOF3** 2019-08-10 05:05 UTC

**Comment by dktapps** [comment] 2019-08-10 06:24
I recognize the world name. This is caused by a SkyBlock plugin which generates a new world for every player.

**Comment by ManiakMCPE** [comment] 2019-08-10 06:59
This didn't happen the last few months with the same plugin. Just started happening today when I reset the server. Might be because there are so many being created at the same time?
