### ISSUE TITLE
Chunk loading issues

### ISSUE THREAD

**Issue by mal0ne-23** [pmmp/PocketMine-MP#1095] opened 2017-06-15 15:26 UTC
### Issue description

When teleporting to a new world (with my testing they both have similar spawn points, so the same chunk areas loaded in each world), the chunks of the old world will stay on the new world and not update until you break a block on the border of the chunk.

### Steps to reproduce the issue

1. Teleport to a new world with a spawnpoint close to the spawnpoint of the first world

### OS and versions

* PocketMine-MP: eb05f2ecde72bbc844b86b3c8c24175e15376b96
* PHP: 7.0.idk
* Server OS: Linux
* Game version: Both

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
You can't really teleport to another world without plugins, so no.

### Crashdump, backtrace or other files

Teleporting code:
`	public function tpToArena(Player $player){
		$level = $this->plugin->getServer()->getLevelByName("KitArena");
		$positions = [
			new Position(152,75,89,$level),
			new Position(128,58,113,$level),
			new Position(128,57,124,$level),
			new Position(139,59,114,$level),
			new Position(170,71,108,$level),
			new Position(154,69,127,$level),
			new Position(138,69,139,$level),
			new Position(117,69,143,$level),
			new Position(105,69,123,$level),
			new Position(108,69,106,$level),
			new Position(105,68,90,$level),
			new Position(118,71,86,$level),
			new Position(129,71,84,$level),
			new Position(146,68,88,$level),
			new Position(147,69,99,$level),
			new Position(161,70,95,$level),
			new Position(168,84,101,$level),
			new Position(164,84,93,$level),
			new Position(145,87,82,$level),
			new Position(131,83,82,$level),
			new Position(112,83,84,$level),
			new Position(103,82,88,$level),
			new Position(101,68,94,$level),
			new Position(109,69,92,$level),
			new Position(87,70,122,$level),
			new Position(96,71,154,$level),
		];
		$tpto = $positions[mt_rand(0,count($positions) - 1)];
		$player->teleport($tpto);
	}`

Image of problem:
http://imgur.com/a/my9df
As you can see, I'm in an arena world, but the spawn still shows right below me.

**Comment by dktapps** [comment] 2017-06-15 15:28
duplicate of #843 and many other closed duplicate issues...

**Closed** 2017-06-15 15:27 UTC

**Comment by mal0ne-23** [comment] 2017-06-15 15:28
This has never happened to me before 1.1 though.

**Comment by dktapps** [comment] 2017-06-15 15:29
I'm aware of this... this is still one of many duplicate issues. It is a client-sided issue.

**Comment by mal0ne-23** [comment] 2017-06-15 15:30
Damn, alright. #BlameShoghi
