### ISSUE TITLE
Add ways to disallow uncancelling cancelled events

### ISSUE THREAD

**Issue by alvin0319** [pmmp/PocketMine-MP#4641] opened 2021-12-12 03:53 UTC
## Description

Currently, we don't have ways to prevent plugins from uncancelling events.

This is really not good for plugin developers who want to disallow uncancelling cancelled events.

so we should add ways to prevent uncancelling cancelled event

## Justification
Let's suppose some anticheat plugin like [AntiInstaBreak](https://github.com/pmmp/AntiInstaBreak) wants to cancel the event to prevent unexpected behaviour from players, and they want event should not be uncancelled by other plugins.

In this case, you have to make another plugin that listens on `EventPriorty::HIGHEST` and cancells it again if it got uncancelled from other plugins.

but setting priority isn't a good solution for us. because in the same priority we cannot set the order of event handlers.

## Alternative methods

1. Let the `PluginManager->registerEvent()` take one more argument that disallows uncanceling cancelled events. This should be false by default.
and add Annotation like `@disallowUncancel`.
2. Add method `CancelableTrait->setDisallowUncancel()` to prevent event from being uncancelled by other plugins. this would be easier to implement than the first one.

**Comment by dktapps** [comment] 2021-12-12 14:25
This is pretty much a dupe of #3823 .

**Closed by dktapps** 2021-12-12 14:25 UTC
