### ISSUE TITLE
Craft stack crash

### ISSUE THREAD

**Issue by Sulfuritium** [pmmp/PocketMine-MP#4009] opened 2021-01-24 10:37 UTC
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue
1. Craft a stack of items at once
2. Crash

### OS and versions

* PocketMine-MP: 3.17.2
* PHP: 7.4
* Server OS: windows ( not sure i am on a web host and i dont know how to tell. )
* Game version: PE/Win10 

### Plugins

Plugins (67): AddNetherite-HiroTeam v2.0.0, AfkKick v1.1, AntiVPN v1.0.0, AnvilUI v0.1, ArmorEffect-Patched_By_GamingFR91 v1.0.0, AuctionHouse v1.3.0-PRERELEASE, AutoRestarter v1.0.0, BPSignShop v1, Backup-HiroTeam v1.0.0, BetterVoting v1.7, BlockItemFrame v2.0.0, BuilderTools v1.2.0-beta2, BurgerSpawners v0.1.5, CobbleBreaker v1.0.0, CombatLogger v0.0.6, CoreCommand v1.0.0, CoreEvent v1.0.0, CoreTask v1.0.0, CoreUI v1.0.0, CustomCraftPlus virvolta_0.3, DevTools v1.14.0, EC-TableUI v1.1.1-pre, EconomyAPI v5.7.2, EnderChestSlots v1.0.1, FormAPI v1.3.0, InvCrashFix v0.0.1, InvSee v1.0.0, KDR v1.0.0, KitUI v1.3.6, KygekWhitelistKick v1.3.0, LoadAllWorlds v1.1.1, LuckyBlock v1, MCPEDiscordRelay v1.0.8, MCPEToDiscord v1.4.1, MOTDShuffle v1.1.7, Minion v1.9.5, NameSpaceRemover v1.0.0, OnlineATM v1.0.0, OnlineTime v1.3, OreGen v1.2.5, PersonaToSkin v0.0.1, PiggyCrates v2.0.9, PiggyCustomEnchants v2.3.0, Ping v0.1, PlayerInfo v2.1.3, PlayerSelectors v1.0.0, PocketLotto v1.1.1, ProtectArmor v1.0.0, ProtectedItemFrame v1.0.0, PureChat v1.4.11, PurePerms v1.4.2, RedstoneCircuit v2.0.0, SkyBlock v3.0.0, SkyTPA v1, Slapper v1.6.1, SlapperRotation v1.2.1, Spy v1.0.0, SulfuCapes v2.0.3, Sword2 v1, Tebex v0.0.1, VMMPE-Action v1.0.0-BETA, WarpsPro v1.3.0, WorldGuard v1.1.91, WorldProtect v2.3.8, Worlds v3.0.4, iProtector v3.1.1, VanishV2 v1.1

- If you remove all plugins, does the issue still occur?
Yes

### Crashdump, backtrace or other files
 https://ibb.co/sQwDsLj

**Comment by TheNewHEROBRINEX** [comment] 2021-01-24 11:04
Duplicate of #3954

**Closed** 2021-01-24 12:48 UTC
