### ISSUE TITLE
crafting issue

### ISSUE THREAD

**Issue by daniel022302** [pmmp/PocketMine-MP#1533] opened 2017-11-11 01:52 UTC
crafting issue

`Server thread/CRITICAL RuntimeException: "Index invalid or out of range" (EXCEPTION) in "src/pocketmine/inventory/BaseInventory" at line 95
11.11 02:51:40 [Server] Server thread/DEBUG #0 src/pocketmine/inventory/transaction/action/SlotChangeAction(78): pocketmine\inventory\BaseInventory->getItem(integer 4)
11.11 02:51:40 [Server] Server thread/DEBUG #1 src/pocketmine/inventory/transaction/InventoryTransaction(125): pocketmine\inventory\transaction\action\SlotChangeAction->isValid(pocketmine\Player object)
11.11 02:51:40 [Server] Server thread/DEBUG #2 src/pocketmine/inventory/transaction/InventoryTransaction(236): pocketmine\inventory\transaction\InventoryTransaction->matchItems(array Array(), array Array())
11.11 02:51:40 [Server] Server thread/DEBUG #3 src/pocketmine/inventory/transaction/InventoryTransaction(258): pocketmine\inventory\transaction\InventoryTransaction->canExecute()
11.11 02:51:40 [Server] Server thread/DEBUG #4 src/pocketmine/Player(2255): pocketmine\inventory\transaction\InventoryTransaction->execute()
11.11 02:51:40 [Server] Server thread/DEBUG #5 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(132): pocketmine\Player->handleInventoryTransaction(pocketmine\network\mcpe\protocol\InventoryTransactionPacket object)
11.11 02:51:40 [Server] Server thread/DEBUG #6 src/pocketmine/network/mcpe/protocol/InventoryTransactionPacket(149): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleInventoryTransaction(pocketmine\network\mcpe\protocol\InventoryTransactionPacket object)
11.11 02:51:40 [Server] Server thread/DEBUG #7 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(92): pocketmine\network\mcpe\protocol\InventoryTransactionPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
11.11 02:51:40 [Server] Server thread/DEBUG #8 src/pocketmine/network/mcpe/protocol/BatchPacket(115): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\InventoryTransactionPacket object)
11.11 02:51:40 [Server] Server thread/DEBUG #9 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(92): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
11.11 02:51:40 [Server] Server thread/DEBUG #10 src/pocketmine/Player(3012): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
11.11 02:51:40 [Server] Server thread/DEBUG #11 src/pocketmine/network/mcpe/RakLibInterface(143): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
11.11 02:51:40 [Server] Server thread/DEBUG #12 src/raklib/server/ServerHandler(97): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 76.114.254.161:39064, raklib\protocol\EncapsulatedPacket object, integer 0)
11.11 02:51:40 [Server] Server thread/DEBUG #13 src/pocketmine/network/mcpe/RakLibInterface(82): raklib\server\ServerHandler->handlePacket()
11.11 02:51:40 [Server] Server thread/DEBUG #14 src/pocketmine/network/Network(89): pocketmine\network\mcpe\RakLibInterface->process()
11.11 02:51:40 [Server] Server thread/DEBUG #15 src/pocketmine/Server(2497): pocketmine\network\Network->processInterfaces()
11.11 02:51:40 [Server] Server thread/DEBUG #16 src/pocketmine/Server(2253): pocketmine\Server->tick()
11.11 02:51:40 [Server] Server thread/DEBUG #17 src/pocketmine/Server(2132): pocketmine\Server->tickProcessor()
11.11 02:51:40 [Server] Server thread/DEBUG #18 src/pocketmine/Server(1714): pocketmine\Server->start()
11.11 02:51:40 [Server] Server thread/DEBUG #19 src/pocketmine/PocketMine(558): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar://C:/Bitnami/multicraft-2.1.1-2/apps/multicraft/servers/server206/custom7.2.phar/, string \, string \plugins\)
11.11 02:51:40 [Server] Server thread/DEBUG #20 C:/Bitnami/multicraft-2.1.1-2/apps/multicraft/servers/server206/custom7.2.phar(1): require(string phar://C:/Bitnami/multicraft-2.1.1-2/apps/multicraft/servers/server206/custom7.2.phar/src/pocketmine/PocketMine.php)`

**Comment by jasonwynn10** [comment] 2017-11-11 01:58
So much for following the issue template...
This issue won't be looked at

**Comment by dktapps** [comment] 2017-11-11 08:29
duplicate of #1480

**Closed** 2017-11-11 12:45 UTC
Labels: Category: Core, Resolution: Duplicate
