### ISSUE TITLE
Movement buffering system causes various bugs on net lag spikes

### ISSUE THREAD

**Issue by sylvrs** [pmmp/PocketMine-MP#1215] opened 2017-07-18 04:52 UTC
### Issue description
When a player sprints and jumps at the same time continuously, the anti-cheat gets triggered.

Expected result: What were you expecting to happen? Sprint jump with no problems
Actual result: What actually happened? Lots of players being pulled to the ground after sprint jumping continuously

### Steps to reproduce the issue

1. Join the server
2. Start sprint jumping continuously

### OS and versions

* PocketMine-MP: 4bd65b4
* PHP: 7.0.3
* Server OS: Linux
* Game version: PE/Win10

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded? Yes, it is.

### Crashdump, backtrace or other files

* N/A

**Comment by SuperMaXAleX** [comment] 2017-07-18 06:19
That’s never happened to me

**Comment by AppleDevelops** [comment] 2017-07-18 16:28
I’ve had this issue on a few PM servers, but I haven’t had the issue on my servers unless I cancel PlayerIllegalMoveEvent

**Comment by SuperMaXAleX** [comment] 2017-07-18 16:30
I cancelled it too

**Comment by IrishPacks** [comment] 2017-07-18 18:14
I use it too, but nonetheless it's still an issue.

**Comment by dktapps** [comment] 2017-07-18 18:40
[Minecraft_ Windows 10 Edition 18_07_2017 19_21_17Trim.mp4.zip](https://github.com/pmmp/PocketMine-MP/files/1156950/Minecraft_.Windows.10.Edition.18_07_2017.19_21_17Trim.zip)

**Comment by IrishPacks** [comment] 2017-07-18 19:08
So it's just jumping in general?

**Comment by IrishPacks** [comment] 2017-07-18 19:47
Update: Easier to reproduce when turning and sprint-jumping.

**Comment by dktapps** [comment] 2017-07-27 07:57
It's the anti-flight that causes this bug. When you're jumping like that, the client frequently doesn't send their on-ground position (it sends it a maximum of once per tick).

**Comment by IrishPacks** [comment] 2017-07-27 08:01
No, I'm aware of that, the question would be better rephrased as this: "So instead of it being sprinting and jumping, it's just jumping in general?"

**Comment by dktapps** [comment] 2017-07-27 09:42
@IrishPacks Set `always-tick-players` to `true`, or `auto-tick-rate` to `false` in pocketmine.yml, does the bug still occur? I'm only able to reproduce the issue when the level has a tick rate > 1.

**Comment by IrishPacks** [comment] 2017-07-27 16:18
That seems to have fixed it, hm, it'd make sense though.

**Comment by bettylovedertderrdy** [comment] 2017-09-14 03:32
genisyspro better !

**Comment by dktapps** [comment] 2018-11-03 22:11
The anti-flight responsible for this has been removed from the core for 3.4 (#2428). Not exactly fixed, but won't be an issue anymore, so... closing...

**Comment by dktapps** [comment] 2019-01-03 19:50
A bit late to mention this, since the shitty anti cheat is already dead, but the root cause of this has been identified.

In a nutshell, the problem is PM's buffered movement processing. This is already being eyed for removal because it causes performance issues with laggy players (O(xyz) complexity, or O(n^3), which means bigger movement distance exponentially increases complexity). However, in a nutshell what's happening is this:
![image](https://user-images.githubusercontent.com/14214667/50658176-6bcfd280-0f90-11e9-9871-bb6168b71fe9.png)

The image leaves out some finer details, but I'm sure readers can figure out what I mean.

When a net lag spike happens, a bunch of movements may arrive all on the same tick. When this happens, only the latest one is processed. This means that a move down -> hit ground -> bounce up may not be noticed. I was able to reproduce this problem even on a local server with 12ms latency.

I'm going to reopen this since the core issue is still present, even though the anti-cheat is gone.

**Closed** 2020-06-04 19:01 UTC
Labels: Category: Core, Status: Debugged
